{1405}{1494}On les a entendus crier pendant 2 heures.|C'était pas nouveau.
{1504}{1573}Puis le fusil est parti.|Des deux canons.
{1597}{1645}Un crime passionnel.
{1696}{1755}Regarde-moi la passion sur ce mur.
{1763}{1835}En tout cas, c'est classé.|Sauf la paperasse.
{1930}{1971}Le gamin a tout vu ?
{1971}{2002}Quoi ?
{2010}{2046}Le gamin.
{2055}{2110}D'où tu la sors, celle-là ?
{2127}{2211}On va être contents|d'être débarrassés de toi, Somerset.
{2235}{2297}Tes questions !|"Le gamin a tout vu ?"
{2297}{2369}On s'en tape !|Il est mort. Sa femme l'a tué.
{2379}{2439}Le reste, c'est pas nos oignons.
{2655}{2703}Inspecteur Somerset ?
{2724}{2770}Inspecteur Mills.
{2844}{2911}J'arrive en ville,|ils m'expédient ici.
{2945}{3017}Mills, on va trouver un bar|et on parlera...
{3033}{3093}Allons au poste,|si ça ne vous fait rien.
{3093}{3168}On n'a pas le temps|de me mettre dans le bain.
{3192}{3280}Je voulais vous demander,|quand on s'est parlé au téléphone...
{3326}{3367}Pourquoi ici ?
{3367}{3403}Pardon ?
{3410}{3477}Tous ces efforts|pour vous faire muter.
{3506}{3578}C'est la première question|qui m'est venue.
{3585}{3623}La même raison que vous.
{3623}{3688}Avant que vous décidiez|de raccrocher.
{3760}{3810}On se connaît à peine.
{3820}{3885}Je ne comprends pas bien|la question.
{3906}{3947}C'est simple.
{3961}{4028}Vous vous êtes battu|pour être muté ici.
{4069}{4117}Je n'avais jamais vu ça.
{4117}{4194}Je voulais me rendre utile.|Ne commençons pas...
{4213}{4268}en nous bottant les burnes.
{4309}{4366}C'est vous qui menez la danse.
{4403}{4480}Je veux que vous ouvriez|les yeux et les oreilles.
{4487}{4543}Je montais pas la garde|devant un McDo.
{4543}{4586}J'ai 5 ans de criminelle.
{4586}{4626}Pas ici.|Je comprends.
{4626}{4718}Les 7 jours prochains, faites-moi|le plaisir de vous en souvenir.
{9057}{9091}LUNDI
{10222}{10258}Répétez.
{10323}{10407}On n'a pas déménagé|pour échapper à ce genre de réveil ?
{10544}{10589}Serpico doit partir.
{10625}{10714}Faudrait peut-être t'enlever|cette croûte. Cet oeil, Serpico.
{10733}{10784}- Tu l'as eue ?|- Oui.
{11201}{11234}Café ?
{11340}{11416}On n'a rien touché.|Tout est comme je l'ai trouvé.
{11419}{11457}A quand remonte la mort ?
{11457}{11517}Comme je disais, j'ai rien touché.
{11551}{11635}Mais il a la tête dans|les spaghettis depuis 45 minutes.
{11635}{11707}Personne n'a observé|les fonctions vitales ?
{11709}{11735}Je bégaie ?
{11735}{11819}Il respire pas, ou alors|il respire de la sauce tomate.
{11826}{11867}Drôle de méthode.
{11867}{11958}Excusez-moi, mais il est assis|sur un tas de pisse et de merde.
{11975}{12042}S'il était pas mort,|il se serait levé.
{12364}{12404}Une question...
{12452}{12524}Ca menait à quoi,|cette petite conversation ?
{12555}{12591}Combien de fois
{12591}{12675}ce naze a trouvé des cadavres|qui n'étaient pas morts ?
{12716}{12759}Laissez tomber.
{13486}{13555}Faut appeler Guinness.|On bat des records.
{13960}{14018}Ou plutôt|"Maisons et Jardins".
{14270}{14320}Qui dit|que c'est un meurtre ?
{14320}{14356}Personne.
{14399}{14430}Il doit avoir
{14430}{14483}le coeur comme un jambon.
{14545}{14601}Si c'est pas un infarctus...
{14641}{14682}Je sais pas...
{15289}{15329}Pas mal, ça !
{15576}{15620}On a eu un cas...
{15648}{15725}un mec mort, par terre,|un couteau dans le dos...
{15737}{15778}Meurtre, non ?
{15823}{15857}Putain !
{15866}{15929}Enfin,|grosse assurance à la clé...
{15931}{15984}Il s'était planté la lame
{16001}{16046}entre les omoplates.
{16046}{16123}Et il avait merdé :|il y avait plusieurs coups.
{16133}{16178}Taisez-vous un peu.
{16413}{16447}Attendez.
{16447}{16480}Quoi ?
{16538}{16581}Il y a un seau.
{16603}{16641}Et dedans ?
{16770}{16818}Putain, de la gerbe !
{16897}{16936}Y a du sang ?
{16945}{16998}J'en ai pas vu. Servez-vous.
{17123}{17168}On l'a empoisonné ?
{17197}{17248}Superbe ! Très feutré...
{17259}{17300}A votre avis ?
{17303}{17379}Les légistes attendent.|On pourra pas tous entrer.
{17426}{17495}Il y a de la place,|mais c'est mal éclairé.
{17536}{17613}Mills, voulez-vous|aller interroger les voisins ?
{17694}{17718}Quoi ?
{17718}{17771}Faites entrer les légistes.
{18140}{18179}Il est mort.
{18210}{18251}Merci, docteur.
{18392}{18455}Vous avez vu mes états de service ?
{18574}{18651}J'ai fait du porte-à-porte|et j'ai arpenté le bitume
{18651}{18694}pendant un bail.
{18713}{18745}Et ?
{18749}{18824}Sur ma plaque, il y a "inspecteur".|Comme vous.
{18855}{18910}J'ai dû prendre une décision
{18922}{19008}pour préserver l'intégrité|de la scène. Je n'ai pas calculé
{19030}{19092}votre temps sur le terrain de jeux.
{19147}{19222}Ne me jetez pas,|c'est tout ce que je demande.
{19387}{19414}Il est mort
{19414}{19502}depuis longtemps, et je peux|te dire que c'est pas du poison.
{19519}{19577}Se laisser aller à ce point-là !
{19586}{19665}Il a fallu quatre hommes|pour le hisser sur la table.
{19730}{19790}Comment il pouvait passer sa porte ?
{19790}{19845}C'était évidemment un reclus.
{19848}{19907}Regardez la taille de cet estomac.
{19924}{19991}Et, ce qui est bizarre,|il est distendu.
{19996}{20075}Et la dimension du cardia,|par où la nourriture...
{20075}{20154}Je vois ce que vous constatez,|mais où ça nous mène ?
{20159}{20198}Dilatation
{20205}{20243}du duodénum.
{20246}{20279}La paroi interne
{20279}{20315}a craqué.
{20320}{20375}Il a mangé jusqu'à éclater ?
{20382}{20442}Pas vraiment éclaté.|Pas jusqu'au bout.
{20442}{20502}Il a fait une hémorragie interne,
{20507}{20564}il y a eu un hématome du grand droit
{20564}{20610}et des muscles abdominaux.
{20610}{20641}Il est mort de bouffe ?
{20641}{20679}Oui et non.
{20727}{20778}Et ces contusions, là ?
{20819}{20869}Je n'ai pas encore trouvé.
{20869}{20917}Un revolver sur le front ?
{20917}{20946}Appuyé fort.
{20946}{20986}J'te dis pas !
{20986}{21049}L'empreinte du canon en rouge sang.
{21101}{21181}Mesdames, messieurs,|on s'est dégotté un homicide !
{21253}{21293}Il a mis un seau sous le mec
{21293}{21360}et a servi la soupe.|Il a pris son temps.
{21360}{21435}Selon le légiste,|ça a duré plus de 12 heures.
{21440}{21511}La gorge était gonflée,|sans doute par l'effort.
{21511}{21581}Il y a eu un moment|où il s'est évanoui.
{21588}{21639}A coups de pied, l'assassin
{21639}{21667}l'a fait éclater.
{21667}{21703}Sado taré !
{21703}{21763}On veut la mort de quelqu'un,|on l'abat.
{21763}{21842}On ne prend pas le risque|que ça dure si longtemps...
{21842}{21914}à moins que l'acte lui-même|n'ait un sens.
{21921}{22010}Quelqu'un avait un problème|avec un gros lard et l'a torturé.
{22025}{22056}Dans les sacs d'épicerie,
{22056}{22142}on a trouvé deux tickets.|L'assassin a tout laissé en plan
{22185}{22240}pour retourner au supermarché.
{22264}{22343}C'est son truc.|J'ai pris la pluie toute la journée.
{22351}{22391}Ce n'est qu'un début.
{22391}{22442}On a un mort, pas trois.
{22442}{22480}Sans mobile.
{22497}{22550}Ne commence pas à triturer
{22554}{22600}ton gros cerveau.
{22610}{22662}Je veux changer de mission.
{22710}{22765}Qu'est-ce que tu me chantes ?
{22770}{22859}Ca ne peut pas être ma dernière|enquête. Ca n'en finira pas.
{22871}{22928}Tu prends ta retraite.|Encore six jours
{22928}{22976}et t'es parti pour de bon.
{22976}{23015}Tu as déjà laissé tomber...
{23015}{23103}Des enquêtes qui avaient été menées|aussi loin que possible.
{23118}{23180}- Puis-je être franc ?|- On est entre amis.
{23180}{23233}Il manque d'expérience...
{23238}{23322}J'en étais sûr ! C'est pas|ma première mission, banane !
{23322}{23350}C'est trop tôt.
{23350}{23422}Je suis là.|Vous pouvez me le dire en face.
{23434}{23478}Trop tôt pour vous.
{23513}{23566}Je peux vous parler seul à seul ?
{23566}{23614}Il en a contre moi...
{23617}{23650}Fermez-la.
{23650}{23691}Je n'ai personne d'autre
{23691}{23775}à mettre là-dessus, tu le sais.|C'est la police urbaine,
{23775}{23816}on ne permute pas.
{23816}{23854}Donnez-la-moi.
{23854}{23876}Pardon ?
{23876}{23916}Il n'en veut pas. Ciao !
{23916}{23962}A plus. Profitez bien.
{23962}{23988}Donnez-la-moi.
{23988}{24048}Non, je vous mets sur autre chose.
{24101}{24156}Vous pouvez disposer, Mills.
{24302}{24369}Désolé, vieux,|mais tu n'y coupes pas.
{24374}{24439}C'est toi|qui te torches Gras-double.
{24609}{24640}MARDI
{24719}{24789}{y:i}MEURTRE|{y:i}DANS LES BEAUX QUARTIERS !
{24789}{24837}{y:i}UN AVOCAT ASSASSIN...
{24837}{24887}Bon, on y va. Du calme.
{24914}{24990}On se calme.|Un peu de silence, s'il vous plaît.
{25091}{25153}Voilà comment nous allons procéder.
{25156}{25204}Je réponds à vos questions
{25204}{25257}dix minutes, montre en main.
{25257}{25348}Si ça ne se passe pas dans l'ordre|et la dignité, je m'en vais.
{25376}{25415}Inspecteur !
{25427}{25477}Vous avez une minute ?
{25592}{25686}Je ne dévoilerai rien de l'enquête|en cours. Ne vous fatiguez pas.
{26175}{26254}- Qu'est-ce que vous avez pour moi ?|- Rien, patron.
{26326}{26400}Vous ne voulez pas...|aller prendre un café ?
{26439}{26530}{y:i}Flash spécial. Nous allons en|{y:i}direct au centre-ville,
{26537}{26599}{y:i}où l'avocat Eli Gould|{y:i}a été trouvé assassiné
{26599}{26664}{y:i}ce matin.|{y:i}Le procureur Talbot
{26666}{26741}{y:i}répond aux questions|{y:i}des journalistes.
{26760}{26813}{y:i}Y a-t-il conflit d'intérêts entre...
{26813}{26863}{y:i}C'est ridicule et insultant.
{26863}{26916}{y:i}Il n'y a de conflit d'aucune nature
{26916}{26995}{y:i}et toute insinuation|{y:i}serait irresponsable.
{27016}{27081}{y:i}- Attendez...|{y:i}Votre associé est soupçonné ?
{27081}{27100}{y:i}Je réponds.
{27100}{27172}{y:i}J'ai vu les représentants|{y:i}des forces de l'ordre
{27172}{27268}{y:i}et ils m'ont certifié que leurs|{y:i}meilleurs hommes sont à l'oeuvre.
{27290}{27342}{y:i}Ce sera l'exemple même
{27381}{27436}{y:i}d'une justice diligente.
{27534}{27575}{y:i}AVARICE
{27985}{28026}Pardon, George.
{28136}{28186}- Somerset...|- Entrez.
{28222}{28251}Tu es au courant ?
{28251}{28292}Non. Je ne sais rien.
{28292}{28361}Eli Gould a été trouvé|assassiné ce matin.
{28361}{28407}Quelqu'un a pénétré|dans son cabinet
{28407}{28455}et l'a saigné à mort.
{28462}{28529}Et a écrit le mot "avarice"|sur le sol.
{28656}{28716}- Avarice ?|- Oui, avec du sang.
{28733}{28783}Mills dirige l'enquête.
{28810}{28851}Excusez-moi...
{28870}{28918}Vous pouvez arrêter de faire ça ?
{28980}{29026}Tant mieux pour lui.
{29057}{29114}A quoi tu vas pouvoir t'occuper ?
{29114}{29193}Je travaillerai.|Une ferme, peut-être. Ma maison...
{29198}{29241}Tu ne ressens rien ?
{29241}{29299}Ca ne te fait aucune impression ?
{29299}{29347}Tu ne seras plus flic.
{29368}{29412}C'est ça, l'idée.
{29455}{29493}Impossible.
{29500}{29558}Tu ne peux pas quitter tout ça.
{29613}{29663}Un type promène son chien.
{29663}{29707}Il se fait attaquer.
{29707}{29774}On lui vole sa montre,|son portefeuille.
{29774}{29802}Et pendant qu'il est là,
{29802}{29860}sur le trottoir, sans défense,
{29862}{29934}l'agresseur le poignarde|dans les deux yeux.
{29965}{30040}Ca s'est passé hier soir,|à quatre rues d'ici.
{30054}{30088}J'ai lu.
{30109}{30157}Je ne comprends plus.
{30162}{30205}Rien n'a changé.
{30205}{30236}Peut-être.
{30237}{30295}Ce boulot, tu étais fait pour ça.
{30295}{30355}Tu ne peux pas dire le contraire.
{30381}{30427}Je peux me tromper.
{30468}{30518}Le légiste t'envoie ça.
{30544}{30611}Il les a trouvés|dans l'estomac du gros,
{30611}{30691}mêlés à la nourriture.|Des fragments de plastique.
{30695}{30743}Pose ça sur le bureau.
{30839}{30894}On l'a... forcé à les avaler.
{33345}{33388}{y:i}GOURMANDISE
{33517}{33577}C'était sur le mur|derrière le frigo,
{33577}{33640}sur le lieu du meurtre de l'obèse.
{33656}{33692}"Longue est la route,
{33692}{33769}Et ardue, Qui de l'Enfer|monte vers la Lumière."
{33776}{33819}C'est de Milton.
{33819}{33863}"Paradis perdu."
{33894}{33927}Je nage.
{33932}{33987}Ca veut dire que ça commence.
{34023}{34081}C'était aussi derrière le frigo,
{34083}{34126}écrit avec de la graisse.
{34126}{34182}Il y a sept péchés capitaux.
{34198}{34241}La gourmandise,
{34285}{34321}I'avarice,
{34371}{34419}la paresse, la colère,
{34426}{34474}I'orgueil, la luxure
{34493}{34536}et l'envie. Sept.
{34596}{34651}Ce n'est même pas mon bureau.
{34671}{34731}Tu peux en attendre cinq de plus.
{34762}{34798}Attends !
{34826}{34879}Je ne peux pas m'en mêler.
{34970}{35009}Il l'a voulu.
{35073}{35124}Je suis en plein dessus.
{35932}{35975}Où vous allez ?
{36037}{36076}Loin d'ici.
{36373}{36428}Deux trois choses à vérifier.
{36435}{36486}Assieds-toi où tu veux.
{36490}{36526}Bonsoir.
{36550}{36594}Salut, Joyeux !
{36610}{36670}George,|les cartes refroidissent.
{36670}{36718}Le devoir m'appelle !
{37085}{37147}Messieurs, je ne comprendrai jamais.
{37212}{37255}Tous ces livres,
{37255}{37308}un monde de savoir sous les doigts,
{37308}{37356}et que faites-vous ?
{37358}{37406}Poker toute la nuit.
{37411}{37454}On a de la culture.
{37454}{37524}Ouais, elle nous sort|par le trou du cul !
{37601}{37653}Ca, c'est de la culture.
{38334}{38385}{y:i}CONTES DE CANTERBURY
{38864}{38912}{y:i}LA DIVINE COMEDIE
{39535}{39583}{y:i}FORCE A SE MUTILER
{40166}{40231}{y:i}Mills, étudiez|{y:i}les péchés capitaux :
{40231}{40315}{y:i}Le Purgatoire...|{y:i}Dictionnaire du Catholicisme
{40701}{40753}{y:i}...déchirer sa chair...
{40878}{40933}{y:i}...sept enfants massacrés !
{41432}{41470}Hé, Joyeux...
{41485}{41530}on va te manquer.
{41573}{41619}C'est bien possible.
{41674}{41724}{y:i}PLAN DE L'ENFER DE DANTE
{42374}{42410}MERCREDI
{42993}{43038}Putain de Dante !
{43046}{43108}Bordel de merde de poète de pédé !
{43154}{43190}Enfoiré !
{43449}{43492}Beau travail !
{43665}{43708}Merci du cadeau.
{43905}{43943}Excusez-moi.
{43965}{44015}Je vous cède la place.
{44310}{44339}Votre fauteuil.
{44339}{44380}Non, prenez-le.
{45319}{45355}Téléphone.
{45370}{45430}Tout va ensemble. Avec le bureau.
{45600}{45662}Chérie, ça va ?|Il y a un problème ?
{45691}{45777}Ma petite caille, je t'ai dit|de pas m'appeler au boulot.
{45818}{45861}Oui. Pourquoi ?
{45914}{45952}Pourquoi ?
{46183}{46219}Ma femme.
{46223}{46257}Pardon ?
{46283}{46331}Elle veut vous parler.
{46561}{46607}Inspecteur Somerset.
{46655}{46705}Oui, enchanté moi aussi.
{46765}{46818}C'est fort aimable, mais...
{46880}{46935}Dans ce cas, je serai charmé.
{46959}{47007}Oui, merci beaucoup.
{47345}{47381}Alors ?
{47446}{47525}Je suis invité à un souper,|chez vous. J'ai accepté.
{47571}{47607}Comment ?
{47609}{47643}Ce soir.
{47801}{47847}Bonsoir, messieurs.
{47849}{47895}- Tarée.|- Crétin.
{47947}{47978}Tracy.
{48060}{48129}Enchantée.|Je sais presque tout de vous.
{48149}{48204}Sauf, bien sûr, votre prénom.
{48230}{48266}William.
{48307}{48345}Un beau nom.
{48379}{48422}William, David.
{48434}{48475}David, William.
{48477}{48544}Je reviens.|Comment vont les enfants ?
{48549}{48607}Bien. Dans la chambre. Entrez.
{48650}{48729}Les gentils clebs ! Ca boume ?|En forme, ma beauté ?
{49021}{49060}Ca sent bon.
{49129}{49170}Enfin, merci.
{49196}{49237}Vous voulez vous asseoir ?
{49237}{49273}Un verre ?
{49276}{49333}Non, merci. Pas pour l'instant.
{49350}{49419}Posez ça quelque part.|Excusez le désordre.
{49436}{49477}On s'installe.
{49534}{49606}Vous flirtiez déjà au lycée,|tous les deux.
{49647}{49686}Ca fait cucu.
{49714}{49755}Vous savez...
{49769}{49839}j'ai su dès le début|que je l'épouserais.
{49849}{49887}C'est vrai ?
{49899}{49923}J'avais jamais
{49923}{49971}vu un type plus drôle.
{50074}{50112}C'est vrai.
{50177}{50256}C'est assez rare, de nos jours...|cette façon de...
{50290}{50326}s'engager.
{50436}{50503}Soyez tranquille,|je ne le garderai pas
{50503}{50539}à table.
{50601}{50669}J'ai beau voir des armes|tout le temps,
{50669}{50714}je ne m'y fais pas.
{50733}{50774}Moi non plus.
{51014}{51071}Pourquoi n'êtes-vous pas marié ?
{51081}{51112}Arrête !
{51112}{51158}J'ai failli l'être.
{51177}{51215}Failli, seulement.
{51215}{51256}Cela m'étonne.
{51270}{51311}Je vous assure.
{51397}{51455}Quiconque passe|un peu de temps avec moi
{51455}{51503}me trouve désagréable.
{51522}{51560}Demandez-lui.
{51560}{51596}Très vrai.
{51596}{51637}Très, très vrai.
{51668}{51721}Vous vivez ici depuis...
{51721}{51764}Trop longtemps.
{51848}{51891}Ca vous plaît ?
{51920}{51985}Oh... il faut du temps.|Se poser...
{52050}{52083}Ca ira.
{52090}{52157}On devient vacciné,|au bout d'un moment.
{52174}{52220}Dans chaque ville...
{52361}{52397}Le métro.
{52400}{52443}Ca va s'arrêter.
{52541}{52589}Le type de l'agence !
{52591}{52630}Putain d'enfoiré...
{52630}{52663}Excuse.
{52678}{52754}On visite plusieurs fois.|Je lui fais confiance.
{52754}{52843}Efficace. Tracy le trouve sympa.|Puis je commence à me demander
{52858}{52934}pourquoi on reste jamais|plus de cinq minutes...
{52939}{52989}On a su la première nuit.
{52992}{53052}Un foyer réconfortant, reposant...
{53059}{53095}vibrant.
{53306}{53344}Excusez-moi.
{53515}{53558}C'est ça, riez.
{53639}{53685}Pourquoi tu ris ?
{53773}{53814}Bon, ça va, là !
{53910}{53960}Il s'introduit dans l'immeuble
{53960}{54059}avant que les bureaux soient fermés|et gardés. Gould travaille tard...
{54064}{54140}Sûrement. C'était|le plus grand avocat criminel.
{54150}{54229}- Un type louche.|- On a découvert le corps mardi.
{54231}{54320}Le cabinet était fermé lundi.|Donc, il a pu entrer vendredi,
{54339}{54402}se cacher,|puis s'éclater sur Gould
{54406}{54490}tout le samedi, le dimanche|et peut-être même le lundi.
{54502}{54538}Regardez.
{54550}{54593}Attaché, bras droit libre.
{54593}{54646}On lui a tendu un couteau.
{54694}{54740}Regardez la balance.
{54740}{54785}Une livre de chair.
{54934}{54967}"Une livre de chair."
{54967}{55027}"Ni plus, ni moins.|Pas de cartilage."
{55027}{55063}"Pas d'os."
{55063}{55116}{y:i}Le Marchand de Venise.
{55119}{55152}J'ai pas vu.
{55152}{55226}"Cette tâche menée à bien,|il partirait libre."
{55238}{55279}La chaise était
{55279}{55315}inondée de sueur.
{55315}{55351}Bien sûr.
{55365}{55437}Le tueur voulait|que Gould prenne son temps.
{55442}{55485}Qu'il réfléchisse.
{55485}{55529}Où couper en premier.
{55529}{55564}Imaginez.
{55569}{55622}Un flingue dans la gueule.
{55629}{55682}Quelle partie du corps ?
{55692}{55735}Poignée d'amour.
{55766}{55823}Coupée le long de son estomac.
{55831}{55915}Observons-les d'un oeil neuf.|Le cadavre est là, mais...
{55927}{56003}regardez au travers.|Laissez de côté votre choc.
{56010}{56102}L'astuce, c'est de trouver un|détail et de se concentrer dessus
{56136}{56198}jusqu'à épuiser cette possibilité.
{56198}{56244}Je reprends une bière.
{56244}{56294}Du vin, s'il vous plaît.
{56503}{56539}Il prêche.
{56551}{56587}Il punit.
{56632}{56709}Les serments médiévaux|avaient recours aux péchés.
{56721}{56771}Sept vertus cardinales
{56771}{56846}et sept péchés capitaux.|Des outils de savoir.
{56855}{56935}- Comme dans "le Pasteur"... Dante.|- Vous avez lu ?
{56975}{57033}En partie.|Vous vous rappelez,
{57042}{57131}Dante et son pote montent|la colline et visent les pécheurs.
{57179}{57237}Les Sept Terrasses de Purgation.
{57265}{57347}Mais là, l'orgueil est en premier.|Pas la gourmandise.
{57349}{57380}Considérons
{57380}{57443}que les livres ont inspiré le tueur.
{57452}{57529}Le but des sermons|était l'expiation des péchés.
{57536}{57591}C'est de l'attrition forcée.
{57596}{57625}De la quoi ?
{57625}{57692}Attrition.|Quand on regrette ses péchés,
{57702}{57788}- mais pas par amour de Dieu.|- Un flingue dans la gueule !
{57889}{57932}Pas d'empreintes.
{57954}{58021}Des victimes|sans rapport entre elles.
{58037}{58090}Et pas l'ombre d'un témoin.
{58102}{58177}Je pige pas.|Fallait que cet enfoiré ressorte !
{58248}{58337}Dans les grandes villes,|la non-intervention est une science.
{58349}{58447}Pour prévenir un viol, les femmes|ne doivent pas appeler au secours,
{58462}{58536}mais crier au feu.|On ne secourt pas les gens.
{58536}{58589}"Au feu !"|Ils accourent.
{58591}{58632}C'est débile.
{58632}{58702}Il a dû laisser|un autre élément du puzzle.
{58750}{58819}Merci d'avoir discuté|de tout ça, mais...
{58819}{58889}faut que je dorme.|Que je sorte les chiens.
{58893}{58951}C'est uniquement par curiosité.
{58951}{58999}Je m'en vais samedi.
{59023}{59059}Attendez.
{59088}{59157}La femme de Gould.|Elle n'était pas en ville.
{59157}{59205}Elle a vu quelque chose.
{59205}{59239}Une menace ?
{59239}{59289}Je l'ai mise à l'abri.
{59294}{59344}Elle n'était pas ravie.
{59526}{59591}Peut-être pas|une chose qu'elle avue,
{59593}{59685}mais qu'elle aurait dû voir,|si on lui en avait donné l'occasion.
{59701}{59740}Bon. Quoi ?
{59742}{59785}Je ne sais pas.
{59824}{59881}Mais ça signifie quelque chose.
{60960}{60996}Je signe.
{61003}{61054}C'est pour madame Gould.
{61130}{61212}J'ai un téléphone,|mais je peux pas appeler en inter.
{61219}{61262}C'est intolérable.
{61380}{61435}Je suis désolé. Sincèrement.
{61456}{61504}Je ne comprends pas.
{61526}{61574}Regardez chaque photo.
{61588}{61629}Attentivement.
{61631}{61701}Voyez si quelque chose|vous semble bizarre,
{61713}{61768}ou déplacé...|N'importe quoi.
{61799}{61842}Je ne vois rien.
{61852}{61922}Je vous en prie,|je ne peux pas maintenant.
{61974}{62008}C'est urgent.
{62008}{62068}On a peut-être raté quelque chose.
{62276}{62315}Attendez...
{62336}{62368}Là.
{62449}{62507}Ce tableau. Il est à l'envers.
{62710}{62763}Ce ne sont pas vos hommes ?
{62763}{62837}Les photos ont été prises|avant leur arrivée.
{62905}{62938}Rien.
{62962}{63020}Il doit y avoir quelque chose.
{63271}{63319}Il a déplacé les vis.
{63434}{63482}C'est quoi, ce truc ?
{63511}{63552}Cran d'arrêt.
{63741}{63780}Et merde !
{63864}{63924}Il faut qu'il y ait quelque chose.
{64048}{64113}C'est pas lui|qui a peint cette merde.
{64290}{64350}Il se fout de notre gueule, voilà.
{64389}{64444}Vous voyez ça ? C'est nous.
{64480}{64521}Une minute...
{64585}{64643}Somerset escalade les meubles.
{64801}{64844}Vous rigolez !
{64851}{64895}Appelez le labo.
{65024}{65062}Oh, putain !
{65139}{65218}Honnêtement, vous aviez déjà vu|une chose pareille ?
{65348}{65377}{y:i}AIDEZ-MOI
{65377}{65429}Vu le contour des crêtes,
{65448}{65520}ce ne sont pas|les empreintes de la victime.
{65755}{65799}Je sais pas, mec.
{65799}{65849}Pour moi, il est givré.
{65890}{65933}Ca ne colle pas.
{65945}{66007}- Il ne veut pas qu'on l'arrête.|- Qui sait ?
{66007}{66038}Y a tellement de détraqués
{66038}{66105}qui font leurs saletés|sans le vouloir.
{66110}{66182}"Les voix m'ont forcé."|"Mon chien m'a forcé."
{66182}{66213}"Jodie Foster
{66213}{66252}m'a forcé."
{66256}{66350}Faut parfois trois jours pour|l'identification. Vous devriez aller
{66352}{66405}croiser vos doigts ailleurs.
{66487}{66556}Tu le pensais,|ce que tu as dit à madame Gould ?
{66556}{66607}Qu'on allait le choper.
{66681}{66743}J'aimerais penser encore comme toi.
{66786}{66856}Et à ton avis,|on fait quoi en ce moment ?
{66880}{66930}On ramasse les morceaux.
{66964}{67055}On recueille les indices, on prend|les photos, les échantillons,
{67081}{67124}on inscrit tout,
{67134}{67192}on note l'heure des événements.
{67218}{67256}C'est tout ?
{67263}{67302}C'est tout.
{67302}{67386}On empile tout ça méticuleusement,|et on le "classe"...
{67407}{67491}pour le cas improbable|où un tribunal en aurait besoin.
{67551}{67623}On ramasse des diamants|sur une île déserte
{67635}{67719}et on les garde, au cas|où l'on viendrait nous sauver.
{67779}{67822}N'importe quoi !
{67872}{67959}Les indices les plus prometteurs|mènent à d'autres indices.
{68002}{68083}Tant de cadavres retournent|au néant sans être vengés.
{68151}{68220}Ne me dis pas|que tu t'es pas pris au jeu.
{68263}{68299}Je t'ai vu.
{68323}{68362}On avance.
{68628}{68659}JEUDI
{68740}{68788}Debout, les jumeaux !
{68793}{68836}On a un gagnant.
{68974}{69060}On l'appelle Victor, mais|son vrai nom est Théodore Allen.
{69072}{69137}On a trouvé ses empreintes|sur le lieu du crime.
{69137}{69204}Il a un lourd passé|de maladies mentales.
{69221}{69295}Ses parents, baptistes,|l'ont élevé sévèrement.
{69302}{69374}Mais quelque part,|ils ont raté leur coup.
{69377}{69454}Victor est tombé dans la drogue,|l'attaque à main armée.
{69454}{69528}De la taule|pour tentative de viol sur mineur,
{69533}{69600}mais pas longtemps,|grâce à son avocat.
{69600}{69657}Qui n'est autre que|feu maître Gould,
{69657}{69708}victime du meurtre "avarice".
{69708}{69758}On emballe aujourd'hui.
{69775}{69852}Victor s'est mis au vert,|mais on a un domicile...
{69875}{69928}Tu n'y crois pas, hein ?
{69935}{69974}Ca ne lui ressemble pas.
{69974}{70019}A qui le dis-tu ?
{70031}{70086}Notre tueur a un but, lui.
{70777}{70820}T'as pris un pruneau ?
{70820}{70890}Pas une fois en 34 ans,|touchons du bois.
{70935}{70966}Je n'ai dégainé
{70966}{71034}que trois fois|avec intention de tirer.
{71036}{71074}Jamais pressé la détente.
{71074}{71113}Pas une fois.
{71117}{71151}Et toi ?
{71151}{71223}Oui, mais...|j'ai jamais pris de pruneau...
{71245}{71309}mais j'ai dégainé une fois.|Et tiré.
{71328}{71405}Ma première descente.|On était l'unité de renfort.
{71417}{71484}J'en menais pas large.|J'étais un bleu.
{71494}{71566}On enfonce la porte|pour choper ce junkie...
{71578}{71621}il ouvre le feu.
{71638}{71690}Un flic est touché au bras.
{71729}{71779}Comment il s'appelait ?
{71813}{71870}Il a tourné comme une toupie...
{71880}{71923}mais au ralenti.
{71954}{71997}Je me souviens...
{72031}{72072}de l'ambulance.
{72100}{72151}C'est là qu'il est mort.
{72199}{72256}Putain, comment il s'appelait ?
{74119}{74184}La brigade|passe avant les poulets !
{74268}{74309}Ils aiment ça.
{74330}{74364}Police !
{74867}{74906}Voie libre !
{75090}{75136}Bonjour, mon chou.
{75160}{75225}Lève-toi, fils de pute.|Maintenant !
{75448}{75496}Debout, tas de merde.
{75654}{75690}Oh, pute !
{75697}{75733}Poulets !
{75738}{75786}Venez jeter un oeil !
{76071}{76105}Nom de Dieu !
{76105}{76133}Victor ?
{76133}{76191}- C'est quoi ?|- C'est Victor.
{76196}{76265}- Appelez une ambulance.|- Tu rêves ? Un corbillard !
{76265}{76304}Les légistes.
{76304}{76351}Tout le monde dehors.
{76351}{76404}Personne ne touche à rien.
{76404}{76455}Putain de musée Grévin !
{76471}{76510}{y:i}PARESSE
{76543}{76582}La paresse.
{76833}{76869}Bordel !
{76881}{76948}Elles sont datées|d'il y a trois jours.
{77135}{77171}La première ?
{77171}{77207}Regarde.
{77215}{77279}Datée d'il y a un an|jour pour jour.
{77327}{77361}Echantillon de cheveu.
{77361}{77409}Les selles. La pisse.
{77426}{77464}Les ongles.
{77512}{77548}Il se fiche de nous.
{77548}{77598}T'as ce que tu méritais.
{77677}{77718}Il est vivant !
{77730}{77780}Cet enfoiré est vivant !
{77783}{77848}Pas de flingues !|L'ambulance, vite !
{78250}{78286}Il s'amuse.
{78286}{78327}Sans blague !
{78377}{78437}Il faut neutraliser nos émotions.
{78440}{78497}Se concentrer sur les détails.
{78502}{78557}Je carbure aux émotions, moi !
{78557}{78596}Tu m'écoutes ?
{78596}{78624}Je t'entends.
{78624}{78704}Qu'est-ce que vous foutez|sur le lieu d'un crime ?
{78713}{78773}J'ai le droit. Agence de presse.
{78792}{78840}- Dégagez !|- J'ai le droit, merde !
{78840}{78876}Dégage !
{78883}{78934}Je t'emmerde ! J'ai ta photo !
{78934}{78967}J'ai ta photo !
{78967}{79039}Inspecteur Mills. M.I.L.L.S.|Fous le camp !
{79061}{79118}- Tu sais écrire ?|- Crève !
{79123}{79181}Comment ils radinent si vite ?
{79193}{79262}Ils paient la police.|Et ils paient bien.
{79293}{79332}Excuse-moi.
{79389}{79420}Ils me font chier.
{79420}{79459}C'est pas grave.
{79459}{79528}Quelle classe,|de carburer aux émotions !
{79682}{79732}Il est resté immobile un an,
{79732}{79809}vu la dégradation des muscles|et de l'épine dorsale.
{79809}{79895}Les tests sanguins révèlent|tout un pot-pourri de drogues.
{79898}{79969}Dont un antibiotique,|sans doute administré
{79977}{80037}pour éviter|l'infection des escarres.
{80037}{80109}A-t-il essayé de parler,|ou de communiquer ?
{80135}{80207}Même si sa cervelle|n'était pas de la bouillie,
{80207}{80276}il s'est bouffé la langue|il y a longtemps.
{80379}{80444}Il n'y a aucune chance|qu'il survive ?
{80468}{80523}Il mourrait de choc à l'instant,
{80523}{80595}si on lui braquait une torche|dans les yeux.
{80600}{80658}Il a enduré plus de souffrances
{80658}{80718}qu'aucun être de ma connaissance.
{80742}{80801}Et il a encore l'enfer devant lui.
{81199}{81243}{y:i}C'est Tracy.
{81291}{81331}Tout va bien ?
{81343}{81386}{y:i}Oui, ça va.
{81401}{81442}Où est David ?
{81442}{81511}{y:i}Dans l'autre pièce.|{y:i}Il se douche.
{81521}{81583}{y:i}Excusez-moi|{y:i}de vous appeler comme ça...
{81583}{81629}Ce n'est pas grave.
{81638}{81691}Je peux vous être utile ?
{81811}{81871}J'ai besoin de parler à quelqu'un.
{81871}{81931}On pourrait se voir quelque part,
{81937}{81989}par exemple demain matin ?
{82013}{82059}Je ne comprends pas.
{82078}{82143}{y:i}Je me sens vraiment idiote, mais...
{82179}{82255}vous êtes la seule personne|que je connais ici.
{82265}{82311}Y a personne d'autre.
{82311}{82387}{y:i}Si vous pouvez,|{y:i}passez-moi un coup de fil.
{82411}{82469}{y:i}Il faut que je vous laisse.
{82471}{82514}{y:i}Bonne nuit.
{82656}{82689}VENDREDI
{82790}{82845}Vous connaissez bien la ville.
{82848}{82898}Vous êtes ici depuis...
{82900}{82941}si longtemps...
{82972}{83025}C'est dur, de vivre ici.
{83027}{83097}Je me demande|pourquoi je vous ai appelé.
{83131}{83188}C'est à lui qu'il faut parler.
{83193}{83243}De ce que vous ressentez.
{83260}{83332}Je ne peux pas.|Pas question d'être un fardeau,
{83332}{83378}surtout maintenant.
{83425}{83466}Je m'habituerai.
{83507}{83555}Je voulais juste parler
{83555}{83617}à quelqu'un|qui a vécu ici longtemps.
{83639}{83728}Dans notre région, l'environnement|est complètement différent.
{83850}{83941}Vous savez que j'enseigne en|cours moyen ? Enfin, j'enseignais.
{84006}{84049}Il m'en a parlé.
{84118}{84202}Je cours à droite à gauche,|je fais le tour des écoles...
{84250}{84329}mais ici, on travaille|dans des conditions horribles.
{84382}{84432}Et les écoles privées ?
{84478}{84521}Je ne sais pas...
{84555}{84622}Dites-moi|ce qui vous tracasse vraiment.
{84682}{84735}Nous allons avoir un bébé.
{84854}{84890}Tracy...
{84929}{85005}je ne crois pas être celui|à qui il faut parler
{85005}{85037}de tout ça.
{85037}{85087}Je déteste cette ville.
{85183}{85243}J'ai été avec une femme, une fois.
{85252}{85308}Ca ressemblait à un mariage.
{85370}{85423}Elle est tombée enceinte.
{85439}{85490}C'était il y a longtemps.
{85626}{85715}Je me souviens m'être levé un jour|pour aller travailler...
{85751}{85818}un jour comme les autres,|si ce n'est que
{85818}{85890}la veille, elle m'avait annoncé|sa grossesse.
{85945}{86003}Et j'ai ressenti de la peur...
{86017}{86068}pour la première fois.
{86118}{86159}Je me disais :
{86168}{86252}comment faire naître un enfant|dans un monde pareil ?
{86252}{86327}Comment peut-on grandir|au milieu de tout ça ?
{86509}{86576}Je lui ai dit|que je n'en voulais pas.
{86614}{86667}Et en quelques semaines,
{86691}{86746}j'ai fini par la convaincre.
{86794}{86842}Je veux des enfants.
{86957}{87019}Je peux vous dire maintenant que...
{87027}{87065}je sais...
{87130}{87175}je suis certain...
{87175}{87233}d'avoir pris la bonne décision.
{87235}{87288}Mais pas un jour ne passe
{87288}{87362}sans que je souhaite|avoir fait un autre choix.
{87468}{87518}Si vous ne gardez pas...
{87566}{87631}Le bébé,|si telle est votre décision,
{87691}{87763}ne lui dites jamais|que vous étiez enceinte.
{87792}{87863}Mais si vous choisissez|d'avoir cet enfant,
{87890}{87911}alors...
{87911}{87971}gâtez-le|autant que vous pourrez.
{88127}{88170}C'est à peu près
{88182}{88252}le seul conseil|que je puisse vous donner.
{88415}{88456}Je dois partir.
{88813}{88887}{y:i}1. Gourmandise|{y:i}2. Avarice 3. Paresse
{88911}{88990}{y:i}4. Envie 5. Colère|{y:i}6. Orgueil 7. Luxure
{89019}{89048}Dans la boîte
{89048}{89115}du proprio de Victor,|on glissait des billets
{89115}{89168}tous les premiers du mois.
{89276}{89312}Je cite :
{89316}{89376}"Je n'ai jamais entendu|l'occupant du 306
{89376}{89455}"se plaindre,|et personne ne s'est plaint de lui.
{89465}{89520}"C'était mon meilleur locataire."
{89520}{89607}Le rêve des proprios : un locataire|paralysé et sans langue.
{89628}{89681}Qui paie dans les délais.
{89693}{89734}J'en ai marre d'attendre.
{89734}{89777}C'est le boulot.
{89798}{89841}On devrait être sur le tas.
{89841}{89911}On moisit ici|en attendant que ce cinglé
{89921}{89959}recommence.
{89964}{90033}C'est réducteur|de le traiter de cinglé.
{90040}{90086}Arrête, il est cinglé !
{90086}{90184}En ce moment, il doit... danser,|vêtu d'une culotte de sa grand-mère.
{90218}{90275}Couvert de beurre de cacahuète.
{90280}{90311}Ca te va ?
{90311}{90352}Ca m'étonnerait.
{90376}{90429}Sa chance va l'abandonner.
{90453}{90508}Il ne se fie pas à la chance.
{90575}{90606}Quand on est entré
{90606}{90673}dans l'appart', il avait attaché|Victor depuis un an.
{90673}{90738}Jour pour jour.|C'est ce qu'il voulait.
{90748}{90781}C'est pas sûr.
{90781}{90813}Oh si.
{90841}{90892}Le papier qu'il a laissé.
{90892}{90940}Ses premiers mots...
{90942}{91000}"Longue est la route, et ardue,|qui de l'Enfer
{91000}{91050}monte vers la Lumière."
{91088}{91124}Le con ! Et ?
{91124}{91172}Jusqu'ici, il a raison.
{91172}{91261}Il faut une sacrée volonté|pour tenir un type attaché un an.
{91285}{91335}Pour lui couper une main
{91335}{91383}et poser des empreintes avec.
{91383}{91455}Pour lui enfoncer des tubes|dans les parties.
{91457}{91541}Il est méthodique, rigoureux|et, pire que tout, patient.
{91582}{91625}Il est ravagé !
{91630}{91724}C'est pas parce qu'il est inscrit|à une biblio que c'est un génie !
{91829}{91875}Tu as de l'argent ?
{91877}{91920}Peut-être 50 dollars.
{91920}{91968}On part se documenter.
{92066}{92131}On fait une liste.|Le "Purgatoire",
{92134}{92167}les "Contes de Canterbury",
{92167}{92234}tout ce qui parle|des péchés capitaux.
{92237}{92275}Demande-toi...
{92275}{92345}ce qu'il a étudié|pour faire ce qu'il a fait.
{92345}{92397}Ce à quoi il s'intéresse.
{92407}{92453}Jack l'Eventreur ?
{92462}{92512}- Où va-t-on ?|- Biblio.
{92512}{92560}{y:i}...Pécheur de Jérusalem...
{92560}{92618}{y:i}...Sept Péchés Capitaux...
{92841}{92898}Bons de réduction... gratis...
{92975}{93030}Ils ont dû avoir|au moins 50 amendes,
{93030}{93081}lors de l'inspection sanitaire.
{93081}{93174}Tu peux pas t'asseoir en face ?|On va croire qu'on sort ensemble.
{93196}{93241}Donne ton argent.
{93270}{93354}Voilà, mais bizarrement,|j'aimerais savoir ce qu'on fout.
{93491}{93543}Salut, Somerset. Ca gaze ?
{93546}{93601}Je prévoyais pas un ménage à trois.
{93601}{93661}C'est sans problème. Assieds-toi.
{93786}{93860}C'est bien parce que c'est toi.|Je risque gros.
{93867}{93932}- Y a pas de lézard, j'espère.|- Juré.
{94076}{94119}Dans une heure.
{94167}{94215}Faites comme chez vous.
{94265}{94323}C'est de l'argent bien dépensé !
{94594}{94675}En te disant ça, je te fais|particulièrement confiance.
{94675}{94737}Bravo ! J'allais te faire une tête !
{94783}{94879}Ce n'est sans doute rien, mais|même dans ce cas, on se mouille pas.
{94949}{95024}Le type de la pizzeria|est un copain du F.B.I.
{95065}{95110}La grosse tache ?
{95117}{95208}Le F.B.I. est relié au fichier|informatique des bibliothèques.
{95232}{95261}Les amendes.
{95261}{95326}Non, ils surveillent|ce que lisent les gens.
{95326}{95393}Ecoute...|certains livres sont fichés.
{95410}{95477}Des livres sur...|les armes nucléaires,
{95477}{95520}ou "Mein Kampf".
{95525}{95570}Tu consultes un livre fiché,
{95570}{95642}ton dossier "biblio"|est engrangé par le F.B.I.
{95642}{95697}Attends... c'est légal, ça ?
{95714}{95789}Légal, illégal...|ce n'est pas le terme exact.
{95805}{95896}On n'utilise pas l'information|directement. Ca te met sur la voie.
{95908}{95978}C'est bête,|mais pour t'inscrire à une biblio,
{95978}{96064}il faut une carte d'identité|et une facture de téléphone...
{96117}{96167}Ils entrent notre liste.
{96184}{96235}Qui lit "le Purgatoire",
{96242}{96306}"Paradis Perdu"|ou "Helter Skelter" ?
{96323}{96405}L'ordinateur va nous répondre.|Peut-être avec un nom.
{96424}{96470}Le nom d'un étudiant
{96477}{96539}qui fait une dissert' sur le crime.
{96553}{96609}Au moins, tu sors du bureau.
{96611}{96654}Fais-toi coiffer.
{96669}{96738}- Comment tu le sais ?|- Je ne sais rien.
{96740}{96800}- Et toi non plus.|- Exactement.
{96987}{97035}"La Divine Comédie".
{97047}{97095}"Histoire du Catholicisme".
{97095}{97141}"Assassins et Fous".
{97153}{97227}"L'Investigation Criminelle".|"De Sang Froid".
{97249}{97299}"Soumission Humaine". Soumission ?
{97299}{97345}Pas ce que tu crois.
{97357}{97400}Le marquis de...
{97414}{97462}- De Sade.|- C'est pareil.
{97462}{97524}Les écrits de saint Thomas Aqua...
{97524}{97577}Saint Thomas d'Aquin. Voilà !
{97577}{97647}Il a écrit|sur les sept péchés capitaux.
{97652}{97688}C'est là ?
{97728}{97786}- On essaie.|- Jonathan Doe ?
{97798}{97836}Pourquoi pas ?
{97836}{97882}On est sûr du nom ?
{97903}{97951}Tu l'as vu. John Doe.
{97968}{98023}Tu veux repartir, on repart.
{98026}{98086}Allons jeter un oeil. Lui parler.
{98100}{98141}C'est bouffon.
{98145}{98193}On va juste lui parler.
{98210}{98287}"Pardon, monsieur,|êtes-vous un tueur en série ?"
{98368}{98409}Parle-lui, toi.
{98431}{98469}Tu sais baratiner.
{98469}{98527}C'est ma femme qui te l'a dit ?
{98620}{98656}Débile.
{98663}{98716}C'est "Drôles de dames" !
{98728}{98783}Un nom donné par ordinateur.
{99157}{99210}- Tu es touché ?|- Non.
{99277}{99315}Il descend !
{99723}{99761}Cinquième !
{100239}{100277}Une sortie ?
{100313}{100351}Verrouillez.
{100409}{100462}Barrez-vous de ce couloir !
{101078}{101119}Baissez-vous !
{101159}{101193}Couché !
{105055}{105101}Tirez-vous de là !
{107511}{107547}Où tu vas ?
{107547}{107602}- J'entre.|- Non, attends !
{107626}{107690}Tu dérailles ?|Il nous a tiré dessus !
{107695}{107729}- Tu peux pas.|- Oh si !
{107730}{107811}- Il faut un mandat.|- On a les "fortes présomptions".
{107814}{107871}Réfléchis ! Comment on est là ?
{107874}{107950}- On ne peut pas parler du F.B.I.|- Enlève-toi !
{107955}{108005}On n'a aucune raison d'être là.
{108005}{108051}Tu vas m'écouter ?
{108065}{108101}Lâche-moi !
{108101}{108140}Bon, pardon.
{108142}{108200}Mais fais attention une minute.
{108204}{108288}S'il y a un trou dans l'enquête,|on ne pourra pas l'inculper.
{108288}{108353}Il sera libre !|C'est ça que tu veux ?
{108358}{108427}Avant qu'on ait un mandat...|tu déconnes !
{108430}{108509}Il nous faut une raison|pour frapper à cette porte.
{108543}{108581}Réfléchis.
{108758}{108811}Tu as raison. Je dérape.
{108823}{108873}C'est toi qui as raison.
{109101}{109154}Plus la peine de discuter.
{109183}{109228}Sauf si tu répares.
{109267}{109307}Espèce de....
{109530}{109588}Combien il nous reste de fric ?
{109597}{109677}Ouais, j'ai remarqué ce type|qui sortait beaucoup...
{109691}{109758}quand les meurtres arrivaient.|Alors...
{109785}{109820}Vous avez appelé|l'inspecteur Somerset.
{109820}{109856}C'est ça.
{109897}{109967}Salement jeté, le mec.|Et l'un des meurtres
{109969}{110017}s'est passé juste là.
{110019}{110087}Je vous ai dit le reste.|C'est tout noté ?
{110087}{110149}Faites-la signer.|Il faut signer.
{110223}{110262}C'est bien.
{110264}{110322}- Comme vous m'aviez dit.|- Tiens.
{110322}{110367}Achète-toi à manger.
{110456}{110499}Personne n'entre.
{111976}{112010}Victor.
{115472}{115510}On l'avait.
{115520}{115565}Qu'est-ce que tu racontes ?
{115565}{115604}Le putain de photographe
{115604}{115647}dans l'escalier !
{115755}{115815}On l'avait et on l'a laissé filer.
{115963}{116006}C'est bien ça ?
{116009}{116052}Ouais. C'est bon.
{116093}{116186}Pas de chèques, pas d'agenda, pas|d'adresses. Il n'y a que ce reçu.
{116193}{116241}- Continuez.|- Regardez ça.
{116241}{116282}C'était sous le lit.
{116282}{116313}Ses revenus ?
{116313}{116364}On a son fric ! Super !
{116368}{116445}Une dernière chose...|vous n'allez pas le croire.
{116445}{116510}On n'a pas trouvé|une seule empreinte.
{116512}{116582}C'est vrai, je ne vous crois pas.|Cherchez.
{116692}{116733}Il faut plus d'hommes.
{116733}{116771}Je trime !
{116786}{116817}Ca donne quoi ?
{116817}{116862}Il y a 2000 cahiers
{116869}{116932}et chaque cahier contient 250 pages.
{116939}{116994}Oublie. Et sur les meurtres ?
{117016}{117109}"Nous sommes de grotesques pantins,|dansant sur une scène vulgaire.
{117121}{117179}"Quelle joie, danser et baiser !
{117179}{117253}"Aucun souci.|Ignorant que nous ne sommes rien.
{117260}{117323}"Nous ne sommes pas|ce qui était prévu."
{117323}{117373}Attends, il y a mieux.
{117402}{117478}"Dans le métro,|un homme a engagé la conversation.
{117495}{117591}"Un solitaire, parlant de la pluie|et du beau temps. J'ai voulu être
{117622}{117654}"aimable,
{117654}{117721}"mais sa banalité|me donnait la migraine.
{117721}{117771}Presque sans le remarquer,
{117771}{117838}"tout d'un coup,|je lui ai vomi dessus.
{117850}{117903}"Il n'était pas content.
{117903}{117968}"Je ne pouvais pas|m'arrêter de rire."
{117987}{118071}Pas de dates. Placés sur les rayons|sans ordre apparent.
{118128}{118171}Son âme déversée
{118171}{118207}sur le papier.
{118207}{118241}Une vie de boulot.
{118241}{118315}Même avec cinquante hommes|lisant en permanence,
{118325}{118387}- ça prendrait deux mois.|- Je sais.
{118577}{118617}Le téléphone ?
{118718}{118768}Tout le monde se tait !
{119147}{119193}{y:i}Je vous admire.
{119212}{119305}{y:i}J'ignore comment vous m'avez|{y:i}trouvé. Imaginez ma surprise.
{119315}{119394}{y:i}Je respecte de plus en plus|{y:i}les forces de l'ordre.
{119394}{119445}Je vous remercie... John.
{119473}{119548}{y:i}Non, écoutez!|{y:i}Je vais revoir mon plan de travail
{119548}{119617}{y:i}en fonction du petit déboire|{y:i}d'aujourd'hui.
{119617}{119679}{y:i}Je voulais exprimer mon admiration.
{119679}{119742}{y:i}Désolé d'avoir blessé l'un de vous,
{119742}{119819}{y:i}mais je n'avais guère le choix,|{y:i}n'est-ce pas ?
{119819}{119917}{y:i}Acceptez mes excuses. Je me tais,|{y:i}de peur de gâcher votre surprise.
{120248}{120293}Reprenez le boulot.
{120341}{120384}Tu avais raison.
{120389}{120425}Il prêche.
{120483}{120540}Ses meurtres sont des sermons.
{120540}{120600}On le connaît, on le connaît...
{120687}{120733}Qui est la blonde ?
{120822}{120867}On dirait une gagneuse.
{120867}{120903}Peut-être.
{120906}{120970}Elle a tapé dans l'oeil de John Doe.
{121090}{121153}Il est passé le reprendre hier soir.
{121193}{121270}- Cet homme ?|- John Doe. Un nom facile. Il boite.
{121289}{121332}Quel travail c'était ?
{121332}{121376}J'ai une photo, par là.
{121376}{121421}Une belle pièce...
{121436}{121495}Je me suis dit :|il fait du "performance art".
{121495}{121539}Le genre de gars
{121546}{121613}qui pisse dans une tasse,|sur scène...
{121623}{121685}et qui la boit.|"Performance art".
{121790}{121843}Je lui ai pas pris assez cher.
{121843}{121894}Vous lui avez fait ça ?
{121896}{121956}J'ai fait des trucs plus zarbis.
{122083}{122133}Ils ont trouvé la blonde.
{122196}{122234}La photo !
{122236}{122272}La photo !
{122301}{122349}Enfoirés de poulets.
{122459}{122514}Tire-toi de cette cabine !
{122603}{122637}Par ici.
{122805}{122848}On peut couper la musique ?
{122848}{122905}On essaie. On cherche le mec.
{123215}{123265}Vous êtes de la Crime ?
{123272}{123322}Faut que vous voyiez ça.
{123342}{123380}{y:i}LUXURE
{123531}{123574}Enlevez-moi ça !
{123589}{123637}Enlevez-moi ce truc !
{123677}{123723}Sortez-le de là !
{123749}{123814}Je veux tout réentendre.|Recommencez.
{123891}{123965}Vous n'avez rien entendu,|rien vu de bizarre ?
{124056}{124116}Il m'a demandé si j'étais marié.
{124118}{124188}- Il avait un revolver.|- Où était la fille ?
{124188}{124229}Que... quoi ?
{124241}{124298}La prostituée. Où était-elle ?
{124303}{124365}On vient dans votre établissement,
{124365}{124433}on veut aller au sous-sol,|s'envoyer en l'air...
{124433}{124471}je m'en fiche...
{124471}{124524}il faut s'adresser à vous ?
{124567}{124617}Vous n'avez vu personne ?
{124617}{124706}Avec un paquet, un sac à dos ?|Quelque chose sous le bras ?
{124706}{124792}Tous les gens qui viennent ici|ont un paquet sous le bras.
{124811}{124886}Y en a qui ont des valises|pleines de machins.
{124895}{124955}Elle était... assise sur le lit...
{125111}{125171}Qui l'a attachée ? Vous ou lui ?
{125178}{125238}Ca vous plaît, votre gagne-pain ?
{125257}{125303}Ce que vous voyez ?
{125339}{125384}Ca me plaît pas.
{125413}{125459}Mais c'est la vie.
{125569}{125619}Il avait un revolver...
{125627}{125667}il fallait...
{125670}{125706}obéir...
{125742}{125794}Il m'a obligé à le faire.
{125799}{125854}Il m'a mis ce truc dessus...
{125895}{125950}il m'a forcé à le porter...
{125984}{126037}Il m'a dit de la baiser...
{126077}{126137}Et je l'ai fait ! Je l'ai baisée.
{126188}{126257}Il enfonçait son revolver|dans ma bouche !
{126269}{126334}Ce putain de flingue,|dans ma gorge !
{126442}{126499}{y:i}Oh, mon Dieu, aidez-moi.
{127008}{127058}Ca ne va pas bien finir.
{127077}{127137}Si on le chope, ce sera pas mal.
{127216}{127307}Si on chope John Doe et que c'est|le diable, Satan en personne,
{127341}{127406}ça répondrait à nos attentes.|Mais...
{127420}{127466}ce n'est pas Satan.
{127490}{127538}Ce n'est qu'un homme.
{127588}{127660}Tu râles, tu rouspètes,|tu me dis tout ça...
{127698}{127782}Si tu crois me préparer|à du grabuge... merci, mais...
{127808}{127866}Mais faut que tu sois un héros.
{127892}{127928}Un champion.
{127928}{127974}Les gens n'en veulent pas.
{127974}{128036}Ils veulent cheeseburgers,|loto et télé.
{128036}{128091}Comment tu es devenu comme ça ?
{128091}{128137}J'aimerais savoir.
{128235}{128295}Il n'y a pas qu'une seule raison.
{128331}{128362}Vas-y.
{128439}{128489}Je ne peux plus vivre en un lieu
{128489}{128540}qui célèbre et inculque...
{128540}{128604}l'apathie|comme si c'était une vertu.
{128621}{128664}Tu ne vaux pas mieux.
{128664}{128729}Je n'ai pas dit ça.|Je ne vaux pas mieux.
{128729}{128799}Au contraire, je sympathise.|Complètement.
{128806}{128861}L'apathie est une solution.
{128868}{128943}Il est plus facile|de sombrer dans la drogue...
{128954}{129005}que d'affronter la vie.
{129005}{129072}Plus facile de voler une chose|que de la gagner.
{129072}{129103}De battre un enfant
{129103}{129146}que de l'élever.
{129146}{129213}L'amour, ça demande un effort.|C'est du boulot.
{129213}{129269}On parle de malades mentaux.
{129271}{129324}On parle de... détraqués !
{129388}{129453}On parle|de la vie de tous les jours.
{129487}{129528}Tu peux pas te permettre
{129528}{129590}- d'être aussi naïf.|- Va chier !
{129640}{129679}Ecoute-toi...
{129698}{129731}Tu dis
{129731}{129786}que les gens s'en fichent.
{129810}{129863}Bon, je me fiche des gens.
{129863}{129909}C'est idiot. Pourquoi ?
{129909}{129954}Tu t'en fiches pas ?
{129959}{129988}Bien sûr que non !
{129988}{130024}Et tu vas tout changer.
{130024}{130091}Peu importe.|Ce que je veux dire, c'est que
{130091}{130165}tu ne t'en vas pas|parce que tu crois tout ça.
{130208}{130256}Tu veux croire tout ça...
{130256}{130304}parce que tu t'en vas.
{130338}{130379}Et tu veux que je sois d'accord.|Que je te dise :
{130379}{130424}"Ouais, t'as raison.
{130427}{130479}"Tout est pourri. C'est la merde.
{130479}{130549}"Y a plus qu'à aller|vivre dans les bois."
{130573}{130609}Mais non.
{130623}{130669}Je ne le dirai pas.
{130690}{130760}Je ne suis pas d'accord.|Pas une seconde !
{130856}{130894}Je peux pas.
{131122}{131165}Je vais rentrer.
{131347}{131393}Merci quand même.
{132117}{132153}Je t'aime.
{132172}{132213}Tellement...
{132402}{132438}Je sais.
{133895}{133928}DIMANCHE
{133935}{133988}Police. C'est une urgence ?
{134014}{134048}Répétez.
{134058}{134113}{y:i}Ca y est... j'ai recommencé.
{134336}{134365}{y:i}ORGUEIL
{134365}{134403}On a quoi ?
{134408}{134458}Une boîte de somnifères.
{134472}{134516}Collés à une main.
{134518}{134568}Le téléphone à l'autre.
{134592}{134628}Il l'a...
{134652}{134688}Tailladée.
{134698}{134736}Puis bandée.
{134746}{134801}Appelle à l'aide et tu vivras.
{134801}{134851}Mais tu seras défigurée.
{134887}{134954}Ou bien tu peux abréger tes souffrances.
{135002}{135043}Il lui a coupé le nez.
{135043}{135086}Pour mortifier son visage.
{135086}{135134}Et c'est tout récent.
{135314}{135350}Ecoute...
{135369}{135443}je vais rester|jusqu'à ce que ce soit terminé.
{135443}{135491}De deux choses l'une.
{135491}{135532}Ou on le chope,
{135532}{135606}ou il finit sa série de sept|et l'enquête s'éternise.
{135606}{135686}Tu n'as pas de service à me rendre.|Merci, mais...
{135688}{135774}Garde-moi comme coéquipier.|C'est toi qui me rends service.
{136074}{136129}Tu savais que je dirais oui.
{136146}{136218}Votre femme a appelé.|Achetez un répondeur !
{136290}{136328}Inspecteur !
{136359}{136405}Après, je me retire.
{136424}{136465}Tu m'étonnes !
{136554}{136597}Vous me cherchez.
{136654}{136690}Pas un geste !
{136690}{136729}Couche-toi !
{136777}{136820}Je vous connais.
{136834}{136872}Couche-toi !
{136884}{136925}Sur le ventre, fumier !
{136925}{136971}Vas-y ! Plus bas !
{136983}{137021}Enfoiré ! Par terre !
{137021}{137059}Plus vite !
{137059}{137127}Plus vite, salaud !|Le nez par terre !
{137234}{137302}Nom de Dieu !|C'est quoi, cette merde ?
{137304}{137362}J'aimerais parler à mon avocat.
{137510}{137565}Il s'arrache la peau des doigts.
{137565}{137613}D'où l'absence totale
{137613}{137671}d'empreintes dans son appartement.
{137671}{137726}Il fait ça depuis longtemps.
{137728}{137791}Et ses comptes bancaires ?|Ses armes ?
{137791}{137841}Jusqu'ici, c'est l'impasse.
{137841}{137908}Pas de revenus connus.|Pas de profession.
{137908}{137985}Un compte, ouvert il y a cinq ans|avec du liquide.
{137997}{138074}On travaille sur ses meubles.|Tout ce qu'on sait,
{138086}{138165}c'est qu'il est indépendant|financièrement, cultivé
{138198}{138237}et cinglé.
{138237}{138299}Parce qu'il est John Doe par choix.
{138304}{138333}On l'interroge ?
{138333}{138390}Non. On le remet à la justice.
{138402}{138431}Jamais
{138431}{138500}il ne se serait livré.|Ca n'a pas de sens.
{138508}{138536}Il est là.
{138536}{138589}Inutile que ça ait un sens.
{138599}{138685}- Il n'en a pas fini.|- Il nous pisse dessus, et on gobe !
{138714}{138764}Tu sais de quoi je parle.
{138771}{138855}Pour la première fois,|nous sommes entièrement d'accord.
{138862}{138906}Il va pas s'arrêter.
{138906}{138954}Alors quoi, putain ?
{138956}{139040}Il n'est qu'à deux meurtres|d'achever son chef-d'oeuvre.
{139066}{139119}Voyons sa ligne de défense.
{139186}{139241}Il y a deux autres cadavres.
{139241}{139306}Deux autres victimes,cachées quelque part.
{139306}{139373}Mon client y conduira Mills et Somerset,
{139376}{139421}mais seulement eux.
{139433}{139507}- Et seulement à 6 h, ce soir.|- Pourquoi nous ?
{139522}{139565}Il vous admire.
{139596}{139637}Ca fait partie du jeu.
{139637}{139702}Il affirme que|si les inspecteurs refusent,
{139702}{139754}on ne trouvera jamais les corps.
{139754}{139819}Je suis enclin|à les laisser pourrir.
{139838}{139910}On le tient. Il est bouclé en bas.|C'est fait.
{139941}{140004}Il aura le gîte, le couvert|et le câble !
{140004}{140064}Ma femme, elle l'a pas, le câble.
{140064}{140116}Pourquoi on parle de ça ?
{140121}{140200}Ca pue l'arnaque ! Et celui-là,|avec... Oui, toi !
{140217}{140282}Avec ton costard de luxe|et ton air béat.
{140282}{140335}Négocier pour cette merde !
{140344}{140392}La loi m'enjoint de
{140392}{140445}- défendre les intérêts...|- Arrête !
{140445}{140478}...de mes clients.
{140478}{140534}On ne fait pas d'arrangements ici.
{140534}{140572}Il vous informe
{140572}{140644}que si vous refusez,|il plaidera la démence.
{140673}{140706}Qu'il essaie.
{140706}{140740}J'aimerais !
{140740}{140833}Nous savons que, vu la nature des|crimes, je le tirerais d'affaire
{140836}{140881}en plaidant ainsi.
{140881}{140936}Pas question qu'il m'échappe.
{140946}{141023}Il dit que si vous acceptez|toutes ses conditions,
{141037}{141111}il signera des aveux complets et plaidera coupable.
{141111}{141169}C'est votre enquête. Décidez.
{141207}{141262}Des aveux complets. Je prends.
{141277}{141330}Vous devez être d'accord.
{141351}{141402}S'il plaide la démence,
{141406}{141476}cette conversation|sera versée au dossier.
{141485}{141526}Son chantage.
{141533}{141615}Mon client vous rappelle|qu'il y a deux autres morts.
{141615}{141689}La presse se déchaînerait|si la police négligeait
{141689}{141754}de les retrouver et de les enterrer.
{141756}{141804}Si ces deux morts existent.
{141804}{141848}On a le rapport du labo
{141848}{141915}sur les vêtements|et les ongles de Doe.
{141917}{141963}Il y a son propre sang,
{141963}{141996}provenant de ses doigts,
{141996}{142075}du sang de la femme|dont il a charcuté le visage,
{142082}{142162}et du sang d'une troisième|personne, non identifiée.
{142253}{142315}Vous escorteriez|un homme non armé.
{142377}{142418}Finissons-en.
{142507}{142560}Si un OVNI sort de sa tête,
{142584}{142639}je veux que tu l'aies prévu.
{142682}{142723}Ce sera fait.
{142780}{142845}Si je me coupe un nibard|avec le rasoir,
{142845}{142902}c'est un accident du travail ?
{143003}{143039}Sûrement.
{143080}{143145}Si tu as le cran|de déposer un dossier,
{143145}{143207}je t'en paie un autre de ma poche.
{143233}{143317}Si je rentre encore tard,|ma femme va avoir des doutes.
{143531}{143569}Tu sais...
{143768}{143799}Quoi ?
{146696}{146744}Qui êtes-vous, John ?
{146749}{146800}Qui êtes-vous vraiment ?
{146800}{146831}Comment cela ?
{146831}{146919}A ce stade, quel mal y a-t-il|à nous parler un peu de vous ?
{146934}{147008}Peu importe qui je suis.|Cela ne signifie rien.
{147015}{147063}Restez sur la gauche.
{147157}{147195}Où va-t-on ?
{147214}{147253}Vous verrez.
{147262}{147341}On ne va pas juste ramasser|deux cadavres, John ?
{147358}{147409}Ce serait pas assez choc.
{147411}{147481}Faut que tu penses|à la une des journaux.
{147507}{147588}Quand on veut que les gens|écoutent, il ne suffit plus
{147600}{147653}de leur taper sur l'épaule.
{147656}{147718}Il faut y aller à coups de massue.
{147720}{147780}Alors, ils sont pendus à vos lèvres.
{147790}{147838}La question, c'est :
{147840}{147912}qu'as-tu de si spécial|pour qu'ils écoutent ?
{147912}{147962}Je n'ai rien de spécial.
{147970}{148032}{y:i}Je n'ai jamais été exceptionnel.
{148039}{148118}{y:i}Mais cela, oui.|{y:i}Ce que je fais. Mon travail.
{148137}{148178}Votre travail ?
{148212}{148277}Je ne vois rien de spécial|là-dedans.
{148315}{148348}C'est faux.
{148348}{148432}Je t'assure. Et le plus drôle,|c'est que tout ce boulot,
{148456}{148547}dans deux mois, tout le monde|s'en tamponnera et l'aura oublié.
{148564}{148641}Vous ne voyez pas encore|l'ensemble du tableau.
{148660}{148711}Mais quand ce sera fait,
{148730}{148763}terminé,
{148804}{148842}ça va être...
{148912}{148979}Les gens auront du mal|à le concevoir.
{148996}{149056}Mais ils ne pourront pas le nier.
{149085}{149130}C'est d'un fumeux !
{149149}{149195}Comme précision...
{149204}{149284}J'ai hâte que vous voyiez.|Ca va être quelque chose.
{149324}{149391}Ah oui ?|Moi, je te lâche pas d'une semelle.
{149391}{149442}Quand le grand moment arrive,
{149442}{149509}préviens-moi.|Je voudrais pas rater ça.
{149523}{149566}Soyez tranquille.
{149636}{149684}Vous ne raterez rien.
{150324}{150367}Ca vous excite ?
{150386}{150437}On n'est plus très loin.
{150612}{150691}Je me pose une question.|Tu peux peut-être m'aider.
{150758}{150808}Quand quelqu'un est fou,
{150808}{150885}comme tu l'es nettement...|Tu sais que tu es fou ?
{150924}{150962}Tu lis "Fusils"
{150962}{151019}en te branlant dans ta merde.
{151019}{151070}Tu t'arrêtes et tu fais :
{151084}{151149}"C'est dément|ce que je suis frappé" ?
{151163}{151211}Ca se passe comme ça ?
{151235}{151302}C'est confortable|de me cataloguer fou.
{151302}{151345}Très confortable.
{151353}{151429}Je ne m'attends pas|à ce que vous l'admettiez...
{151444}{151513}mais je n'ai pas choisi.|J'ai été choisi.
{151518}{151592}- C'est ça.|- Je suis sûr que vous le croyez,
{151616}{151662}mais vous fermez les yeux
{151662}{151722}sur une contradiction flagrante.
{151722}{151763}C'est-à-dire ?
{151779}{151825}Merci de demander.
{151859}{151923}Si vous avez été choisi, disons, par...
{151957}{152007}une puissance supérieure,
{152014}{152067}si on vous a forcé la main,
{152070}{152149}il me semble étrange|que vous en tiriez du plaisir.
{152158}{152223}Cela vous a plu,|de torturer ces gens.
{152247}{152312}Ce qui ne cadre guère|avec le martyre.
{152501}{152554}Je n'ai pas eu plus de plaisir
{152554}{152611}que M. Mills n'en aurait, seul avec moi,
{152611}{152669}dans une pièce sans fenêtres.
{152679}{152727}N'est-ce pas la vérité ?
{152727}{152755}Vous seriez ravi
{152755}{152801}de me frapper impunément.
{152801}{152839}Tu me vexes.
{152866}{152887}Jamais...
{152887}{152949}Seulement à cause des conséquences.
{152978}{153031}Je le vois dans vos yeux.
{153048}{153127}Il n'y a pas de mal à prendre plaisir à son travail.
{153129}{153184}Je ne nie pas mon propre désir
{153192}{153259}de retourner le péché contre le pécheur.
{153276}{153348}Ah bon ? Pour moi, tu avais tué des innocents.
{153395}{153453}Innocents ? Vous plaisantez ?
{153479}{153513}Un obèse
{153520}{153582}répugnant, tenant à peine debout.
{153582}{153674}Le rencontrant dans la rue,|vous le montriez du doigt en riant.
{153690}{153743}Le voyant pendant votre repas,
{153743}{153803}vous ne pouviez plus rien avaler.
{153817}{153904}Ensuite j'ai choisi l'avocat,|et vous avez dû me remercier.
{153913}{153973}Un homme qui avait consacré sa vie
{153985}{154040}à faire de l'argent en mentant
{154043}{154129}comme il respirait, pour que|des assassins et des violeurs
{154148}{154194}- rôdent en liberté.|- Des assassins ?
{154194}{154213}Une femme...
{154213}{154266}Des assassins comme toi ?
{154271}{154338}...si laide de l'intérieur|qu'elle ne pouvait vivre
{154338}{154395}sans être belle extérieurement.
{154395}{154467}Un vendeur de drogue.|Pédéraste, de surcroît.
{154506}{154577}Sans oublier la putain|propageant l'épidémie.
{154625}{154688}Il faut que ce soit|un monde de merde,
{154688}{154774}pour qu'on ose parler d'innocents|en gardant son sérieux.
{154848}{154899}Tout le problème est là.
{154925}{155002}Nous voyons un péché capital|à chaque coin de rue,
{155004}{155071}dans chaque foyer,|et nous le tolérons.
{155086}{155136}Parce que c'est courant.
{155158}{155194}Trivial.
{155215}{155278}Nous le tolérons du matin au soir.
{155345}{155393}Mais plus maintenant.
{155445}{155493}Je donne l'exemple.
{155527}{155572}Ce que j'ai fait sera
{155572}{155620}disséqué... étudié...
{155680}{155719}et suivi...
{155755}{155795}pour toujours.
{155863}{155911}Folie des grandeurs.
{155944}{155997}Vous devriez me remercier.
{155999}{156035}Pourquoi ?
{156035}{156110}Parce qu'on se souviendra de vous|par la suite.
{156110}{156203}Rendez-vous compte que la seule|raison pour laquelle je suis là,
{156205}{156258}c'est que je l'ai voulu.
{156275}{156325}On aurait fini par t'avoir.
{156325}{156395}Vraiment ?|Et quelle était votre tactique ?
{156400}{156472}Attendre votre heure ?|Tirer les ficelles ?
{156472}{156527}Laisser cinq "innocents"...
{156544}{156606}mourir,|avant de refermer votre piège ?
{156606}{156654}Quelle preuve irréfutable
{156654}{156723}aviez-vous contre moi,|juste avant que...
{156726}{156805}je m'avance vers vous|en levant les mains en l'air ?
{156843}{156930}Du calme. Si je me souviens,|nous avons frappé à ta porte.
{156961}{157052}Mais oui. Et si je me souviens,|je vous ai arrangé le portrait.
{157179}{157251}Vous vivez|parce que je ne vous ai pas tué.
{157251}{157282}Recule-toi.
{157282}{157304}Je vous ai épargné.
{157304}{157344}Recule-toi !
{157344}{157390}Souvenez-vous-en,
{157402}{157447}en vous regardant dans la glace,
{157447}{157495}toute votre vie.|Ou pendant...
{157495}{157536}le restant de vie
{157536}{157567}que je vous laisse.
{157567}{157608}Recule, taré !
{157618}{157661}Ferme ta gueule !
{157694}{157764}T'es pas le Messie,|t'es le polar de la semaine !
{157764}{157809}Une tronche|sur un tee-shirt,
{157809}{157848}au mieux !
{158160}{158224}Ne me demandez pas|de m'apitoyer sur eux.
{158224}{158315}Je ne les pleure pas plus|que les morts de Sodome et Gomorrhe.
{158330}{158375}Est-ce à dire que...
{158375}{158440}vous accomplissiez|l'oeuvre de Dieu ?
{158514}{158584}Les voies du Seigneur|sont impénétrables.
{158639}{158689}Vous voyez ces pylônes ?
{158701}{158754}{y:i}C'est là que nous allons.
{158754}{158836}{y:i}Cale-toi à neuf heures|{y:i}et suis la route d'accès.
{159143}{159214}Je peux te dire|qu'il y a pas de guet-apens.
{159236}{159277}Y a que dalle !
{159284}{159320}Ils arrivent
{159320}{159356}dans deux minutes.
{159357}{159410}Tu vas monter. Très haut.
{159417}{159489}Dans 30 secondes,|vire à l'est à mon signal.
{160975}{161011}Je le sors.
{161167}{161210}{y:i}Descends.
{161217}{161256}Doucement.
{161316}{161352}Reste là.
{161421}{161460}C'est quoi ?
{161496}{161536}Un chien mort.
{161560}{161604}Ce n'est pas moi.
{161762}{161807}Quelle heure est-il ?
{161807}{161841}Pourquoi ?
{161841}{161886}J'aimerais savoir.
{161951}{161985}7 h 01.
{162057}{162097}On approche.
{162109}{162148}Allons voir.
{162224}{162265}C'est par là.
{163414}{163452}Baisse-toi !
{163512}{163550}Surveille-le.
{163574}{163618}Le voilà parti.
{163630}{163689}{y:i}Nous aurons le temps de parler.
{163826}{163900}Garde le type en rouge|dans ta ligne de mire !
{164080}{164121}Une camionnette arrive.
{164121}{164159}{y:i}Du nord.
{164380}{164461}Prépare-toi à tout.|Attends mon signal. Attends-moi.
{164610}{164648}Descendez !
{164696}{164728}{y:i}Dehors !
{164728}{164768}Ne tirez pas !
{164780}{164819}A distance.
{164833}{164888}Tournez.|Mains sur la tête.
{164891}{164934}{y:i}C'est quoi ?
{164941}{164975}{y:i}Que faites-vous ici ?
{164975}{165042}Je livre un paquet.|Pour un nommé David.
{165070}{165099}L'inspecteur
{165099}{165140}David Mills.
{165305}{165361}Allez le chercher, lentement.
{165653}{165723}Un mec m'a payé 500 sacs|pour l'amener ici.
{165723}{165780}Je devais arriver à 7 h pile.
{165783}{165819}Posez-le.
{165847}{165878}{y:i}Un carton.
{165878}{165943}Un carton !|Appelez les démineurs !
{165991}{166034}Face au véhicule.
{166042}{166082}Mains en l'air.
{166245}{166286}Tournez-vous.
{166312}{166348}Bon, partez.
{166348}{166396}{y:i}Allez-vous-en !
{166437}{166495}Je renvoie le chauffeur à pied.
{166576}{166607}{y:i}Vers le nord.
{166607}{166648}Interceptez-le.
{166873}{166924}Je ne sais pas trop...
{167068}{167108}Je vais l'ouvrir.
{167108}{167183}J'ai dit que je vous admirais.|J'étais sincère.
{167643}{167674}Du sang.
{167674}{167741}Vous avez réussi votre vie,|inspecteur.
{167744}{167782}Il y a de quoi être fier.
{167782}{167835}Ta gueule, tas de merde !
{168489}{168569}California, éloigne-toi.|Surtout ne t'approche pas.
{168597}{168650}{y:i}Quoique tu entendes.
{168667}{168717}John Doe mène la danse.
{168753}{168789}Il arrive.
{168806}{168830}Quoi ?
{168830}{168856}J'aurais aimé
{168856}{168931}- vivre comme vous.|- La ferme. Merde, quoi ?
{168957}{169000}Vous m'entendez ?
{169000}{169043}Je vous admire,
{169063}{169115}vous et votre jolie femme.
{169209}{169264}- Tu dérailles ?|- Je trouve inquiétant
{169264}{169336}qu'un journaliste achète|si facilement un tuyau
{169336}{169379}à vos collègues.
{169437}{169484}{y:i}Jette ton arme !
{169487}{169549}Je suis passé chez vous ce matin...
{169559}{169604}après votre départ.
{169621}{169672}J'ai voulu jouer au mari.
{169674}{169731}Goûter la vie d'un homme simple.
{169760}{169796}Ton arme !
{169796}{169842}Ca n'a pas marché.
{169851}{169887}Alors...
{169894}{169947}j'ai emporté un souvenir.
{169981}{170019}Sa jolie tête.
{170137}{170197}- Qu'est-ce qu'il raconte ?|- Donne ton arme.
{170197}{170233}Qu'y a-t-il ?
{170233}{170278}Lâche ce revolver.
{170278}{170314}Y a quoi, dans le carton ?
{170314}{170367}J'envie votre vie normale.
{170388}{170436}L'envie est mon péché.
{170436}{170477}C'était quoi ?
{170487}{170532}Dis-moi, putain !
{170542}{170568}Il vous l'a dit.
{170568}{170638}Tu mens. Enfoiré de menteur !|Ta gueule !
{170664}{170734}C'est ce qu'il veut.|Que tu le descendes.
{170827}{170863}Dis que c'est pas vrai.
{170863}{170918}- C'est pas vrai.|- Devenez vengeance.
{170918}{170949}Elle va bien.
{170949}{170995}Devenez... colère.
{171012}{171045}Dis-le !
{171057}{171103}Tuer un suspect...
{171136}{171184}c'est tout ficher en l'air.
{171184}{171228}Elle m'a supplié.
{171235}{171292}Elle m'a supplié d'épargner sa vie
{171292}{171352}et celle du bébé qu'elle portait.
{171789}{171834}Il ne savait pas.
{172153}{172199}Donne-moi ton arme.
{172384}{172427}Si tu le tues...
{172456}{172499}il aura gagné.
{173871}{173921}{y:i}Appelez quelqu’un !
{174343}{174396}On va prendre soin de lui.
{174600}{174650}Qu'il ne manque de rien.
{174669}{174708}Où tu seras ?
{174772}{174808}Pas loin.
{174911}{174957}Je serai pas loin...
{175048}{175103}{y:i}Ernest Hemingway a écrit :
{175108}{175156}{y:i}"Le monde est beau
{175158}{175228}{y:i}et vaut qu'on se batte|{y:i}pour lui."
{175235}{175309}{y:i}La seconde partie,|{y:i}je suis d'accord.
