[INFORMATION]
[TITLE]
[AUTHOR]
[SOURCE]Subtitles captured by SubRip 1.00b
[PRG]
[FILEPATH]
[DELAY]0
[CD TRACK]0
[COMMENT]
[END INFORMATION]
[SUBTITLE]
[COLF]&HFFFFFF,[STYLE]bd,[SIZE]18,[FONT]Arial
00:00:00.00,00:00:00.10


00:00:17.78,00:00:21.98
LE GUÉPARD

00:02:58.74,00:03:00.46
Deuxième Mystère douloureux ,

00:03:00.66,00:03:03.33
flagellation[br]de Jésus Christ au pilori

00:05:28.50,00:05:30.37
Pourquoi tout ce vacarme ?

00:05:31.38,00:05:32.45
Parle

00:05:32.86,00:05:33.45
Excellence...

00:05:34.26,00:05:38.41
on a trouvé un soldat mort[br]dans le jardin.

00:05:38.78,00:05:39.69
Quoi ?

00:05:42.30,00:05:46.09
Il y a de graves désordres en ville.[br]Et dans tout le pays.

00:05:46.62,00:05:47.85
Cette lettre

00:05:48.22,00:05:51.69
vient de la part du duc de Malvica.[br]C'est urgent.

00:06:00.22,00:06:03.05
"Cher Fabrizio, lis donc le journal"

00:06:09.18,00:06:11.05
"Les Piémontais ont débarqué"

00:06:11.42,00:06:12.82
"Nous sommes perdus"

00:06:14.46,00:06:18.34
"Avec toute ma famille[br]je me réfugie sur les navires anglais"

00:06:18.54,00:06:20.33
"Tu nous imiteras certainement"

00:06:26.14,00:06:28.65
"Que Dieu sauve notre Roi.[br]Je t'embrasse"

00:06:29.02,00:06:29.77
Quel froussard !

00:06:34.62,00:06:37.45
"Un acte de piraterie[br]a été commis le 11 mai"

00:06:37.82,00:06:40.33
"Des gens armés ont dèbarqué[br]à Marsala"

00:06:40.70,00:06:44.49
"On sait maintenant qu'il[br]s'agit d'une bande de 800 hommes"

00:06:44.86,00:06:46.73
"commandée par Garibaldi"

00:06:49.50,00:06:53.62
"Ces brigands ont évité soigneusement[br]les troupes royales"

00:06:53.98,00:06:56.17
"et se dirigeaient sur Castelvetrano"

00:06:56.70,00:07:00.82
"menaçant les citoyens pacifiques,[br]pillant et dévastant"

00:07:03.26,00:07:05.93
Paolo ira loger au palais[br]à Palerme

00:07:06.30,00:07:08.65
Ne laissons pas la maison inhabitée

00:07:09.02,00:07:11.69
Mais c'est dangereux...[br]C'est dangereux...

00:07:12.06,00:07:14.09
Non Fabrizio... non...

00:07:14.78,00:07:16.18
C'est la guerre

00:07:17.66,00:07:18.89
Appelle Mimi

00:07:26.78,00:07:28.50
C'est la révolution

00:08:01.98,00:08:03.05
Mimi !

00:08:04.70,00:08:06.26
Il arrive papa

00:08:09.02,00:08:10.25
Excellence, dans le jardin...

00:08:10.62,00:08:11.53
Je sais, je sais !

00:08:12.22,00:08:15.85
Mimi... dis qu'on attelle[br]les chevaux au coupé

00:08:16.22,00:08:17.29
Dépêche-toi !

00:08:21.82,00:08:23.69
Je descends à Palerme

00:08:26.94,00:08:27.69
Père Pirrone

00:08:29.42,00:08:30.90
vous venez avec moi

00:08:35.10,00:08:36.82
Que le Seigneur nous protège

00:08:38.30,00:08:39.86
Mais Fabrizio...

00:08:40.22,00:08:43.37
les routes sont pleines[br]de soldats, de malandrins...

00:08:43.74,00:08:44.81
Du calme

00:08:46.46,00:08:48.69
Vous resterez deux heures[br]au couvent avec vos amis.

00:08:48.90,00:08:50.49
On revient à 11 heures

00:08:51.90,00:08:52.97
Je t'en prie...

00:09:05.18,00:09:07.37
Dans une demi-heure à table...

00:09:09.18,00:09:10.58
tous sans exception

00:09:29.18,00:09:30.41
Que faire ?

00:09:53.82,00:09:56.97
Ces charognes puent[br]même après leur mort

00:09:57.34,00:09:59.53
Tu as averti la caserne ?

00:10:01.18,00:10:04.17
Excellence, on leur a dit[br]de venir le prendre

00:10:23.58,00:10:26.41
Sale époque[br]Excellence, sale époque !

00:10:34.30,00:10:36.65
Regardez ces feux sur la montagne

00:10:40.38,00:10:42.10
Ce sont des camps de rebelles

00:10:42.46,00:10:44.02
Je les vois, je les vois...

00:10:54.46,00:10:57.61
Votre Excellence est inquiète[br]pour don Tancredi?

00:11:01.34,00:11:04.97
Il devrait se méfier[br]de certaines amitiés...

00:11:05.66,00:11:08.33
de certaines fréquentations[br]dangereuses

00:11:08.70,00:11:11.69
La faute n'est pas à Tancredi[br]mais au temps qui court

00:11:13.82,00:11:16.81
Un jeune homme n'est même plus[br]libre de jouer aux cartes

00:11:17.18,00:11:19.85
sans être compromis[br]par des amitiés dangereuses

00:11:21.02,00:11:22.25
Ça suffit !

00:11:24.70,00:11:27.37
Vraiment...[br]avec un peu de prudence...

00:11:27.74,00:11:28.81
Enfin !

00:11:31.10,00:11:32.66
Halte ! Arrêtez !

00:11:37.66,00:11:39.22
Bonsoir Excellence

00:11:39.90,00:11:40.81
Pardonnez-nous

00:11:41.18,00:11:42.90
Vous pouvez continuer

00:11:43.26,00:11:45.45
C'est son Excellence le prince Salina !

00:11:58.94,00:12:02.09
Quel beau pays ce serait[br]Excellence si...

00:12:02.46,00:12:04.97
S'il n'y avait pas tant de Jésuites

00:12:17.34,00:12:19.69
Je passerai vous prendre[br]dans deux heures

00:12:20.38,00:12:21.61
Et bonnes prières !

00:13:09.18,00:13:10.58
Mon prince...

00:13:42.78,00:13:44.01
Bonjour, mon oncle

00:13:44.54,00:13:45.61
Tancredi...

00:13:47.10,00:13:48.82
qu'est-ce que tu as fait cette nuit ?

00:13:49.18,00:13:51.85
Cette nuit ?[br]Absolument rien mon oncle

00:13:52.38,00:13:55.37
J'ai été avec des amis.[br]Une sainte nuit

00:13:56.06,00:13:58.89
Ce n'est pas comme quelqu'un[br]de ma connaissance qui s'est amusé

00:13:59.42,00:14:00.82
à Palerme

00:14:01.66,00:14:03.49
Et ce quelqu'un c'est ?

00:14:03.70,00:14:05.93
Toi-même mon oncle

00:14:06.46,00:14:10.89
Je t'ai vu de mes yeux à la barrière[br]parler avec le sergent

00:14:12.38,00:14:14.10
C'est du propre, à ton âge !

00:14:14.46,00:14:16.81
Et avec un Révérend Père !

00:14:17.82,00:14:19.69
Les vieillesses libertines !

00:14:20.06,00:14:21.46
Au fond c'est vrai

00:14:41.82,00:14:44.49
Mais pourquoi tu t'es affublé comme ça ?

00:14:45.02,00:14:46.58
Un bal matinal ?

00:14:46.94,00:14:48.97
Je pars dans une heure

00:14:49.34,00:14:50.57
Je viens te saluer

00:14:51.10,00:14:52.01
Pourquoi ?

00:14:53.18,00:14:55.69
Où vas-tu ? Pas à un duel

00:14:56.38,00:14:59.37
Oui, à un grand duel mon oncle,[br]un duel avec le Roi

00:14:59.74,00:15:01.14
Avec Franceschiello

00:15:01.50,00:15:03.22
Je m'en vais dans la montagne

00:15:03.90,00:15:06.57
De grandes choses se préparent,[br]je ne resterai pas ici

00:15:08.22,00:15:09.78
où ils m'attraperaient

00:15:10.14,00:15:13.45
Il est insensé de se mettre[br]avec ces gens-là. C'est la Mafia

00:15:13.82,00:15:15.22
Des coquins

00:15:17.66,00:15:20.33
Un Falconeri doit rester[br]avec nous, pour le Roi

00:15:20.70,00:15:22.42
Pour le Roi certes

00:15:24.06,00:15:27.21
Mais quel Roi ?[br]Tu l'as dit si souvent toi-même

00:15:27.90,00:15:29.93
Le Roi Ferdinand, s'il vivait

00:15:30.30,00:15:32.65
Mais pas[br]Franceschiello-Dieu-le-bénisse

00:15:33.82,00:15:37.29
Tu crois que le Piémontais,[br]le "Roi-Galant-Homme" sera différent ?

00:15:37.66,00:15:40.01
Tout au plus il ne parlera pas[br]napolitain, mais piémontais

00:15:40.38,00:15:43.21
Tu voudrais la république[br]de ce Mazzini ?

00:15:46.46,00:15:49.93
Si nous n'en sommes pas nous aussi,[br]ce sera la république

00:15:51.10,00:15:53.61
Si nous voulons que tout[br]se maintienne

00:15:53.98,00:15:55.70
il faut que tout change

00:15:56.22,00:15:57.45
Suis-je clair ?

00:16:02.14,00:16:05.29
A bientôt mon oncle.[br]Je reviendrai avec les trois couleurs

00:16:06.94,00:16:08.81
Le drapeau tricolore !

00:16:09.34,00:16:12.33
Mais qu'y trouvez-vous,[br]il est quoi en comparaison

00:16:13.18,00:16:16.01
de notre drapeau blanc[br]fleurdelisé ?

00:16:16.38,00:16:18.41
Vous attendez quoi de ces couleurs ?

00:16:18.78,00:16:20.34
Attends et tu verras

00:16:20.70,00:16:21.93
Visionnaires !

00:16:23.10,00:16:24.01
Adieu

00:16:34.62,00:16:35.69
A bientôt

00:16:52.54,00:16:53.61
Au revoir !

00:17:20.22,00:17:22.89
Tancredi ! Attends

00:17:31.42,00:17:32.49
Qu'est-ce que tu fais ?

00:17:33.50,00:17:35.53
Tu subventionnes la révolution ?

00:17:35.90,00:17:37.62
Merci mon oncle

00:17:39.10,00:17:41.61
A bientôt[br]et embrasse ma tante pour moi !

00:17:54.78,00:17:56.18
Concetta. Non

00:17:56.54,00:17:58.10
Je reviendrai bientôt, tu sais

00:18:02.94,00:18:04.66
Adieu Concetta

00:18:50.78,00:18:53.13
Vous venez vous confesser[br]Excellence ?

00:18:53.66,00:18:56.01
Me confesser ? Ce n'est pas samedi

00:19:02.62,00:19:05.45
Croyez-moi, confessez-vous

00:19:09.50,00:19:11.53
Ce n'est pas nécessaire, voyez-vous...

00:19:12.54,00:19:14.10
Vous savez déjà tout

00:19:19.90,00:19:24.02
Se confesser n'est pas raconter[br]des faits mais se repentir

00:19:24.38,00:19:25.78
Je sais, je sais !

00:19:28.22,00:19:31.21
Que me voulez-vous ?[br]Je suis un homme vigoureux

00:19:31.74,00:19:35.86
Avec une épouse qui au lit fait[br]le signe de la croix à chaque baiser

00:19:37.02,00:19:39.21
Et après[br]ne dit que "Jésus et Marie"

00:19:39.58,00:19:40.77
J'ai eu sept enfants

00:19:41.34,00:19:42.41
Sept !

00:19:43.42,00:19:47.01
Et me croirez-vous ?[br]Je n'ai jamais vu son nombril

00:19:50.78,00:19:51.81
Est-ce juste ?

00:19:52.22,00:19:54.57
Je vous le demande.[br]C'est elle, la pécheresse

00:19:59.58,00:20:00.81
Excellence...

00:20:02.30,00:20:04.49
j'ai été trop brusque

00:20:05.98,00:20:08.01
Gardez-moi votre bienveillance

00:20:12.86,00:20:15.53
Mais croyez-moi, confessez-vous

00:20:16.38,00:20:18.57
Je n'en ai pas la moindre intention

00:20:20.38,00:20:21.61
Aujourd'hui du moins

00:20:25.02,00:20:27.21
J'ai fait d'importantes[br]découvertes politiques

00:20:28.54,00:20:30.73
Vous savez ce qui se passe[br]dans le pays ?

00:20:31.26,00:20:32.66
Il ne se passe rien

00:20:33.66,00:20:36.49
Rien qu'une insensible[br]substitution de classes

00:20:37.66,00:20:40.49
La classe moyenne ne veut pas[br]nous détruire...

00:20:40.86,00:20:44.33
mais prendre notre place[br]avec de bonnes manières

00:20:44.86,00:20:48.17
en nous mettant s'il le faut[br]des ducats dans la poche

00:20:48.70,00:20:50.57
Ainsi tout peut rester comme c'est

00:20:52.22,00:20:55.49
Mon père, notre pays[br]est celui des arrangements

00:20:56.38,00:21:00.01
En somme vous les seigneurs[br]vous vous entendez avec les libéraux

00:21:00.54,00:21:02.37
Même avec les francs-maçons

00:21:03.26,00:21:05.69
A nos dépens, aux dépens de l'Eglise

00:21:06.14,00:21:09.77
Nos biens[br]qui sont le patrimoine des pauvres

00:21:10.14,00:21:13.45
seront saisis et partagés[br]entre les meneurs les plus impudents

00:21:15.42,00:21:16.33
Et après ?

00:21:16.70,00:21:20.49
Qui rassasiera les malheureux que[br]l'Eglise aide encore aujourd'hui ?

00:21:21.18,00:21:24.14
Qui apaisera la foule des désespérés ?[br]Je vais vous le dire.

00:21:24.86,00:21:28.17
On leur jettera une portion[br]et puis une autre

00:21:28.54,00:21:30.89
et puis tout l'ensemble de vos terres

00:21:35.90,00:21:39.53
Jésus guérissait les aveugles de corps.[br]Mais les aveugles d'esprit

00:21:39.98,00:21:41.46
ils finiront où ?

00:21:47.74,00:21:50.41
Nous ne sommes pas aveugles[br]d'esprit mon Père...

00:21:53.02,00:21:56.81
mais des êtres humains[br]dans un monde en transformation

00:21:57.82,00:21:59.22
Alors qu'y faire ?

00:22:00.38,00:22:03.53
Une promesse d'immortalité[br]a été faite à l'Eglise

00:22:04.06,00:22:05.78
Mais pas à nous, classe sociale

00:22:06.46,00:22:10.58
Pour nous le remède pour vivre[br]encore cent ans est l'éternité

00:22:12.22,00:22:16.18
Au-delà de ce que nous pouvons[br]espérer, nous n'avons pas d'obligations

00:22:16.54,00:22:18.10
L'Eglise en a...

00:22:18.78,00:22:21.45
parce qu'elle est destinée[br]à ne pas mourir

00:22:21.82,00:22:24.33
Dans son désespoir[br]il y a déjà de la consolation

00:22:24.74,00:22:27.38
Croyez-vous que si un jour l'Eglise...

00:22:28.38,00:22:32.34
pouvait se sauver en nous sacrifiant[br]elle hésiterait ?

00:22:34.62,00:22:36.18
Elle n'hésiterait pas

00:22:36.54,00:22:37.94
Et elle aurait raison !

00:22:48.22,00:22:51.05
Vous aurez deux péchés[br]à me confesser samedi

00:22:51.42,00:22:55.17
Un péché de la chair cette nuit,[br]un péché de l'esprit aujourd'hui

00:22:57.02,00:23:00.33
Regardez comme c'est beau mon Père

00:23:01.50,00:23:04.49
Il en faudra des Victor Emmanuel[br]pour changer cette potion

00:23:04.86,00:23:07.05
qui nous est administrée[br]chaque jour

00:24:36.38,00:24:39.69
Laissez-le ! Assassins ! Mon enfant !

00:24:47.74,00:24:48.49
En avant !

00:24:51.42,00:24:53.29
En joue ! Feu !

00:25:08.38,00:25:11.85
Allez traîtres ! Charognes !

00:25:23.74,00:25:25.14
Le voilà !

00:25:45.02,00:25:47.05
Pendons-le !

00:26:41.66,00:26:42.73
En avant !

00:26:48.38,00:26:49.78
La voie est libre...

00:27:11.42,00:27:13.29
Longez le mur. Suivez-moi !

00:27:29.98,00:27:31.05
Aide-moi

00:27:36.70,00:27:38.73
C'était un sbire, un assassin

00:27:39.10,00:27:40.93
Nous l'avons exécuté. C'était un lâche !

00:27:44.86,00:27:46.42
Allons ! Suivez-moi !

00:27:51.10,00:27:53.13
La cavalerie. Ne tirez pas

00:27:53.50,00:27:55.22
Ne tirez pas encore

00:27:56.70,00:27:57.77
Feu !

00:28:11.50,00:28:12.61
En avant !

00:28:21.06,00:28:21.77
Premier peloton...

00:28:22.26,00:28:23.45
...en avant !

00:28:24.38,00:28:25.81
Deuxième peloton...

00:28:27.22,00:28:28.29
A terre !

00:28:28.94,00:28:30.05
En joue...

00:28:30.46,00:28:31.41
...feu !

00:29:17.34,00:29:18.85
Vite, de l'eau !

00:29:20.42,00:29:21.93
Attention aux barricades !

00:29:27.86,00:29:29.18
Courage les gars.

00:29:29.50,00:29:31.61
Hé là ! Brave femme...

00:29:31.82,00:29:32.85
Viens ici

00:29:33.06,00:29:34.17
Qu'est-ce que tu veux ?

00:29:34.78,00:29:36.29
Qu'est-ce qui se passe? Où sont-ils ?

00:29:36.50,00:29:38.73
Ils avancent, ils sont au port

00:29:39.10,00:29:40.66
En avant les gars

00:30:50.58,00:30:51.57
Que dites-vous mon Père ?

00:30:55.58,00:30:59.05
Ces temps glorieux nous[br]donneront-ils des routes meilleures ?

00:31:06.94,00:31:08.13
Le Gouvernement...

00:32:31.26,00:32:35.05
On ne passe pas ! Halte !

00:32:35.98,00:32:36.81
Au large !

00:32:37.18,00:32:40.17
Halte ! On ne passe pas.[br]C'est bloqué

00:32:40.54,00:32:43.69
- Nous avons un laissez-passer[br]- La route pour Bisacquino est barrée

00:32:44.06,00:32:47.33
Arrêtez ! Arrêtez les voitures !

00:32:50.62,00:32:54.74
Je regrette, défense de passer.[br]Arrêtez, on ne passe pas

00:32:55.90,00:32:57.46
Le laissez-passer

00:33:02.94,00:33:04.97
Le nôtre n'a pas l'air valide

00:33:05.34,00:33:06.74
Je n'ai pas dit ça

00:33:07.10,00:33:11.69
Mais les laissez-passer civils[br]sont considérés comme suspendus

00:33:12.22,00:33:14.09
Vous croyez que ça nous amuse ?

00:33:14.46,00:33:16.33
Il faudra retourner sur vos pas

00:33:16.70,00:33:19.53
Place ![br]Les voitures doivent continuer !

00:33:19.90,00:33:21.93
Halte ! Où penses-tu aller ?

00:33:22.30,00:33:24.49
Les voitures ne passent pas ici

00:33:24.86,00:33:27.85
Je suis le capitaine Prince Falconeri.[br]J'ai combattu avec vous à Palerme

00:33:28.22,00:33:29.78
Mais j'ai reçu des ordres

00:33:30.14,00:33:32.97
Ça aussi c'est un ordre ![br]Ouvrez le passage !

00:33:33.66,00:33:34.57
Laissez-nous passer

00:33:57.26,00:33:58.58
En avant ! En avant !

00:34:39.90,00:34:42.57
Mais toi, qui vis avec les nobles...

00:34:42.94,00:34:46.90
qu'en pensent-ils les seigneurs[br]de ce grand incendie

00:34:47.58,00:34:50.09
Qu'en dit le Prince Salina...

00:34:50.46,00:34:52.97
irritable et orgueilleux comme il est !

00:34:54.90,00:34:58.21
Voyez-vous,[br]les "seigneurs" comme vous dites...

00:34:58.58,00:35:00.77
ne sont pas faciles à comprendre

00:35:01.30,00:35:05.89
Ils vivent dans un univers[br]particulier, non créé par Dieu...

00:35:07.06,00:35:08.46
mais par eux-mêmes...

00:35:08.82,00:35:11.49
durant des siècles d'expériences[br]très spéciales...

00:35:11.86,00:35:14.21
de douleurs et de joies...[br]des joies à eux

00:35:14.58,00:35:19.01
Eux, ils souffrent[br]et jouissent pour des choses...

00:35:20.02,00:35:23.65
qui ne nous touchent pas[br]mais qui leur sont essentielles

00:35:25.82,00:35:28.78
Je ne dis pas que les nobles[br]soient méchants...

00:35:30.90,00:35:32.93
Ils sont différents

00:35:33.38,00:35:37.73
Ils négligent des choses qui[br]pour nous sont très importantes...

00:35:38.42,00:35:40.93
et ils ont des craintes[br]que nous ignorons

00:35:41.30,00:35:43.17
Pour le Prince Salina...

00:35:43.54,00:35:45.26
ce serait une tragédie...

00:35:45.62,00:35:49.41
que de renoncer à la villégiature[br]à Donnafugata où nous allons

00:35:52.02,00:35:55.81
Mais si on lui demande[br]ce qu'il pense de la révolution...

00:35:57.30,00:35:59.97
il dit qu'elle n'a pas eu lieu...

00:36:00.66,00:36:03.38
- Et que tout va continuer comme avant[br]- Il ne manquerait plus que ça !

00:36:05.14,00:36:07.01
Oui, il ne manquerait plus que ça !

00:36:08.02,00:36:10.37
Lisons notre bréviaire, c'est mieux

00:36:12.02,00:36:13.01
Voyons...

00:36:15.66,00:36:17.41
Psaume 44

00:37:45.94,00:37:47.01
Dépêchez-vous !

00:37:51.38,00:37:53.25
Etends-la comme il faut

00:37:53.62,00:37:56.13
Toi prends les bouteilles[br]et toi les verres

00:37:59.86,00:38:01.26
Allez, vite...

00:38:06.42,00:38:08.14
nos maîtres arrivent

00:38:11.70,00:38:14.93
Avec tous ces coups de canon[br]espèrons que tout finira bien.

00:38:15.14,00:38:17.05
Bien,[br]comme votre Excellence voudra.

00:38:17.26,00:38:19.65
Je suis heureux de voir[br]votre Excellence

00:38:20.98,00:38:22.54
Nous nous reposerons un peu

00:38:22.90,00:38:24.93
Ici vous pouvez manger[br]tranquillement

00:38:25.30,00:38:27.65
Dans une demi-heure nous repartons[br]pour Donnafugata

00:38:28.02,00:38:30.85
Les soldats sont passés ici aussi ?[br]Beaucoup de dégâts ?

00:38:44.26,00:38:46.93
Que c'est bon ![br]Tu veux te rafraîchir aussi ?

00:38:47.30,00:38:48.37
Prends

00:38:50.50,00:38:52.37
Rafraîchis-toi les tempes

00:38:56.74,00:38:57.97
Comme c'est frais...

00:39:01.22,00:39:02.62
Quel plaisir !

00:39:03.94,00:39:05.01
Ça va mieux ?

00:39:07.30,00:39:10.45
Rejoignons-les[br]ou nous n'aurons plus rien à manger

00:39:22.50,00:39:23.57
Tu me le rends ?

00:39:28.58,00:39:29.81
Allons, viens

00:39:33.06,00:39:34.29
Tu as faim ?

00:39:56.90,00:40:01.49
On disait tous "Cette année[br]le prince ne quittera pas Palerme"

00:40:02.18,00:40:05.17
"Comment bouger[br]par des temps pareils ?"

00:40:05.54,00:40:08.69
"Qui sait ce qui est arrivé[br]au prince et à sa famille"

00:40:09.06,00:40:11.37
"Que le Seigneur les protège".[br]Mais voilà...

00:40:11.58,00:40:13.81
qu'ils sont tous sains et saufs

00:40:14.18,00:40:15.74
Dieu soit loué

00:40:16.10,00:40:18.61
Que voulez-vous qu'il nous arrivât ?

00:40:19.62,00:40:21.34
Tout a été très simple

00:40:23.62,00:40:26.81
"En effet, peu après l'entrée[br]de Garibaldi à Palerme..."

00:40:27.02,00:40:30.05
"Tancredi amena à la maison[br]un général sympathique..."

00:40:30.26,00:40:32.65
"qui voulait admirer[br]les fresques de la villa..."

00:40:32.86,00:40:37.01
"et qui ensuite nous fit obtenir[br]le laissez-passer pour Donnafugata"

00:40:38.98,00:40:43.49
Ma famille et moi nous sommes[br]heureux de vous recevoir général

00:40:43.70,00:40:45.65
Merci... Excellence

00:40:54.66,00:40:58.78
Le général t'a appelé "Excellence".[br]Il a enfreint les ordres de Garibaldi

00:41:09.62,00:41:13.45
Mon général, vous vouliez voir[br]les fresques de la villa

00:41:13.66,00:41:15.73
Bien volontiers Excellence

00:41:18.50,00:41:19.73
Voici au centre...

00:41:20.26,00:41:22.13
Jupiter Tonnant et Junon...

00:41:22.34,00:41:24.69
Mars, Vénus et Mercure...

00:41:25.54,00:41:28.85
Là-bas Thétis précédée de tritons[br]et de dryades...

00:41:29.86,00:41:31.89
Apollon entouré de nuages

00:41:32.26,00:41:35.09
Tous exaltant la gloire[br]de la famille Salina

00:41:52.42,00:41:54.14
Tu veux une dragée à la menthe ?

00:41:54.50,00:41:56.85
Merci, justement celles que j'aime

00:41:57.46,00:41:59.10
Je les ai apportées pour toi

00:42:16.42,00:42:18.14
Qu'il est pâle...

00:42:18.82,00:42:20.54
Sa blessure n'est pas grave ?

00:42:32.90,00:42:36.37
Une promotion au champ d'honneur[br]vaut bien une blessure

00:43:06.18,00:43:08.37
Les voitures !

00:43:09.06,00:43:12.21
Les berlines arrivent ! Les berlines !

00:44:23.14,00:44:26.13
Je suis heureux de souhaiter[br]la bienvenue à leurs Excellences

00:44:26.50,00:44:28.22
Don Onofrio comment allez-vous ?

00:44:28.58,00:44:30.89
Bien Excellence.[br]Je vous rends le palais...

00:44:31.14,00:44:33.65
exactement comme vous l'avez laissé

00:44:55.78,00:44:59.69
Je suis fier de serrer la main[br]au glorieux blessé de Palerme

00:44:59.90,00:45:03.25
Blessé ? On m'a fait capitaine[br]pour un moucheron dans l'œil

00:45:06.18,00:45:08.49
Vous avez fait beaucoup[br]pour notre cause

00:45:08.90,00:45:10.62
Crispi m'a parlé de vous

00:45:19.30,00:45:22.61
Chère Teresina,[br]quel plaisir de te revoir !

00:45:24.74,00:45:27.89
Vous aussi bien entendu.[br]Quoi de nouveau don Ciccio ?

00:45:29.70,00:45:32.85
Je ne sais Excellence...[br]Vous permettez ?

00:45:33.22,00:45:34.45
Mais oui

00:48:55.30,00:48:57.81
Rappelle-toi les invitations[br]à dîner pour ce soir

00:48:58.90,00:49:00.38
Les femmes aussi

00:49:01.54,00:49:02.21
Pourquoi ?

00:49:02.42,00:49:03.41
C'est mieux

00:49:05.22,00:49:07.73
Invite don Calogero avec sa femme

00:49:08.58,00:49:10.30
Le notaire avec la sienne

00:49:10.98,00:49:13.65
Don Ciccio[br]qui lui heureusement n'en a pas

00:49:14.82,00:49:16.69
Et tous les autres après le dîner

00:50:21.50,00:50:22.77
Qu'est-ce que c'est ?

00:50:22.98,00:50:24.77
C'est Mimi Excellence

00:50:28.02,00:50:30.37
Le Père Pirrone demande[br]à voir Votre Excellence

00:50:30.90,00:50:32.13
Tout de suite

00:50:33.46,00:50:35.33
Bien, fais-le entrer

00:50:45.06,00:50:46.25
Ne faites pas l'idiot

00:50:47.26,00:50:50.77
Vous connaissez la nudité des âmes.[br]Celle des corps est plus innocente

00:50:51.10,00:50:53.13
Donnez-moi le peignoir plutôt

00:51:04.74,00:51:06.30
Courage mon Père

00:51:13.18,00:51:14.58
Plus fort mon Père

00:51:18.14,00:51:21.13
Et croyez-moi prenez un bain[br]vous aussi quelquefois...

00:51:24.06,00:51:25.13
Asseyez-vous

00:51:29.50,00:51:32.33
Que vouliez-vous me dire[br]de si pressé ?

00:51:35.10,00:51:36.66
Voilà Excellence...

00:51:37.34,00:51:40.65
on m'a confié une mission[br]assez délicate

00:51:41.18,00:51:44.85
Une personne qui vous est chère[br]a voulu m'ouvrir son âme...

00:51:45.06,00:51:47.17
et m'a chargé de vous dire...

00:51:47.38,00:51:50.73
certainement à cause de l'estime[br]dont vous m'honorez...

00:51:51.10,00:51:52.37
Soyez plus bref

00:51:54.46,00:51:57.13
Voyons, de qui s'agit-il ?[br]De la princesse ?

00:51:57.62,00:51:59.29
Non Excellence, non...

00:51:59.50,00:52:01.77
la princesse[br]est en train de se reposer

00:52:02.14,00:52:04.49
Il s'agit de mademoiselle Concetta

00:52:06.86,00:52:07.57
Elle est amoureuse

00:52:09.66,00:52:12.49
Mademoiselle Concetta ? Mais quoi...

00:52:15.02,00:52:16.17
Sottises !

00:52:20.30,00:52:21.57
Je ne voulais pas vous troubler...

00:52:21.78,00:52:24.50
Excellence... Je ne pensais pas...

00:52:26.46,00:52:29.61
A quarante-cinq ans[br]on peut se croire encore jeune...

00:52:30.30,00:52:33.77
mais quand on s'aperçoit[br]qu'on a des enfants en âge d'aimer...

00:52:34.78,00:52:37.29
alors la vieillesse arrive[br]tout d'un coup

00:52:42.30,00:52:45.93
Vous ne m'avez pas demandé[br]qui est l'autre...

00:52:46.78,00:52:48.05
le jeune homme...

00:52:48.26,00:52:49.61
Pas nécessaire

00:52:55.58,00:52:58.73
Pourquoi diable n'est-elle pas[br]venue me le dire ?

00:53:02.30,00:53:04.49
D'après vous[br]que devrais-je répondre ?

00:53:05.66,00:53:08.73
Le désir de fonder[br]une famille chrétienne...

00:53:08.94,00:53:10.69
est très apprécié par l'Eglise...

00:53:11.42,00:53:13.29
et Notre Seigneur aux noces de Cana

00:53:13.50,00:53:14.49
Venons au fait

00:53:15.58,00:53:19.37
Je parle de ce mariage[br]et non du mariage de Cana...

00:53:19.74,00:53:21.61
ou du mariage en général

00:53:22.78,00:53:26.21
Don Tancredi a fait des propositions ?[br]Savez-vous quand ?

00:53:26.94,00:53:30.41
Voilà Excellence...[br]des propositions proprement dites, non

00:53:30.78,00:53:34.05
Mais mademoiselle Concetta[br]n'a aucun doute à son sujet...

00:53:34.26,00:53:35.77
ses attentions, ses regards...

00:53:35.98,00:53:40.29
La princesse sent qu'elle est aimée...

00:53:40.50,00:53:43.06
et que ces propositions[br]sont imminentes

00:53:43.58,00:53:45.30
Ne vous inquiétez pas

00:53:46.14,00:53:50.10
Le danger n'est pas proche.[br]Des fantaisies de jeune fille romantique

00:53:52.22,00:53:53.94
"Le danger" ? Pourquoi ?

00:53:54.46,00:53:58.25
Imaginez-vous Concetta ambassadrice ?

00:53:58.94,00:54:00.66
A Vienne ? A Saint-Pétersbourg ?

00:54:01.02,00:54:03.37
Moi je l'aime bien. Elle me plaît...

00:54:04.06,00:54:06.41
une jeune fille tranquille,[br]obéissante...

00:54:06.78,00:54:10.09
Mais Tancredi[br]a un grand avenir devant lui

00:54:10.62,00:54:14.09
Et Concetta,[br]si passivement vertueuse...

00:54:14.46,00:54:17.93
si timide, si réservée,[br]comment pourrait-elle l'aider...

00:54:18.30,00:54:21.45
à gravir les marches glissantes[br]de la nouvelle société ?

00:54:21.82,00:54:23.85
Et Tancredi a besoin d'argent

00:54:25.14,00:54:26.89
Concetta aura sa dot

00:54:27.74,00:54:30.73
mais la fortune des Salina[br]sera divisée en sept parties.

00:54:31.58,00:54:32.65
Sept !

00:54:34.14,00:54:36.33
Lui il a besoin de bien autre chose

00:54:39.10,00:54:40.97
Une des filles Sutera

00:54:41.98,00:54:43.70
Je sais, je sais...

00:54:44.38,00:54:47.13
si laides mais si riches mon Père

00:54:48.22,00:54:49.62
Oui mais...

00:54:50.14,00:54:51.37
L'amour ?

00:54:52.70,00:54:53.93
Ah ! L'amour !

00:54:54.62,00:54:57.93
Du feu, des flammes pour un an,[br]de la cendre pour trente

00:54:58.46,00:55:00.33
Je le connais l'amour

00:55:03.90,00:55:07.21
Excellence comment[br]vous habillez-vous pour le dîner ?

00:55:09.66,00:55:13.01
Mon Père, dites à Concetta[br]que je ne suis pas fâché...

00:55:13.22,00:55:16.81
qu'on en reparlera lorsqu'il ne[br]s'agira plus de fantaisies romantiques

00:55:17.18,00:55:19.53
Un complet d'après-midi[br]naturellement

00:55:54.30,00:55:58.58
Papa, don Calogero est dans l'escalier.[br]Il est en habit !

00:56:00.06,00:56:01.29
En habit !

00:56:07.74,00:56:11.21
Cette nouvelle te frappe plus[br]que le débarquement à Marsala

00:56:11.90,00:56:15.05
C'est le signe de la révolution[br]en marche

00:56:28.22,00:56:30.86
C'est vrai, il est en habit ![br]Mais quel habit !

00:56:33.18,00:56:34.41
Et les chaussures !

00:56:38.94,00:56:41.29
Ma femme est malade, très enrhumée

00:56:41.66,00:56:42.89
Je regrette

00:56:44.22,00:56:47.65
Vos Excellences m'excuseront[br]si ma fille Angelica...

00:56:47.86,00:56:48.85
vient à sa place

00:56:50.94,00:56:52.97
Bien sûr. Venez

00:56:55.90,00:56:58.37
Il y a un mois[br]qu'elle ne parle pas d'autre chose

00:56:58.58,00:57:01.01
que du plaisir[br]qu'elle aurait à vous connaître

00:57:01.22,00:57:02.49
maintenant qu'elle est grande

00:57:02.78,00:57:04.81
Je me la rappelle petite fille

00:57:06.94,00:57:08.66
Nous serons heureux de la revoir

00:57:25.98,00:57:28.81
Ma fille n'était pas encore prête...

00:57:29.50,00:57:33.13
mais elle arrive.[br]Notre maison est à deux pas...

00:57:33.50,00:57:35.37
Oui don Calogero, nous l'attendrons

00:57:35.74,00:57:37.30
Ma femme est malade...

00:58:24.22,00:58:25.45
Charmante

00:58:26.62,00:58:28.02
Si vous permettez...

00:58:35.74,00:58:37.46
Ma petite Angelica...

00:58:38.42,00:58:41.77
il y a longtemps que je ne t'avais pas vue ![br]Tu as changé...

00:58:42.30,00:58:43.70
plutôt en mieux

00:58:48.86,00:58:50.85
Nous sommes très flattés[br]mademoiselle...

00:58:51.42,00:58:54.41
d'accueillir une si belle fleur[br]dans notre maison

00:58:54.78,00:58:56.01
J'espère...

00:58:57.18,00:58:59.21
vous y revoir très souvent

00:58:59.74,00:59:02.73
Merci Prince.[br]Votre bonté pour moi...

00:59:03.10,00:59:06.73
est celle que vous avez toujours[br]montrée pour mon cher papa

00:59:14.62,00:59:16.49
Comment allez-vous ?

00:59:17.66,00:59:19.69
Fillettes nous nous tutoyons

00:59:31.74,00:59:35.53
Monsieur le comte, permettez-moi[br]de vous présenter ma fille Angelica

00:59:44.22,00:59:45.78
Le dîner est servi

01:00:18.46,01:00:21.13
En plusieurs couches[br]comme le veut la tradition

01:00:22.46,01:00:24.02
Quelle bonne odeur !

01:00:27.42,01:00:29.29
Le voyage a été fatigant ?

01:00:30.14,01:00:33.13
On ne vous a pas servi,[br]je regrette, ça vient

01:00:36.22,01:00:37.05
Une belle fille, hein ?

01:00:37.26,01:00:38.29
Oui Concetta, oui

01:00:38.50,01:00:42.25
La villa que je me fais construire[br]princesse...

01:00:42.62,01:00:44.34
est modeste

01:00:47.18,01:00:48.13
mais très confortable

01:00:50.78,01:00:54.74
Nous avons tous très faim[br]heureusement qu'il n'y a pas de potage

01:00:55.10,01:00:57.45
Oui, nous vivons[br]une époque mouvementée

01:00:59.42,01:01:02.09
Pourtant [br]ces journées sont inoubliables

01:01:02.94,01:01:06.25
Un seul mot d'ordre ,[br]armes et gens armés

01:01:06.94,01:01:10.73
Le général avait compris que[br]lorsque les Siciliens bougent...

01:01:11.18,01:01:12.50
ils bougent sérieusement

01:01:14.46,01:01:17.13
Vous, pourquoi êtes-vous[br]devenu garibaldien ?

01:01:18.30,01:01:21.02
"Si vous ne dédaignez pas en Garibaldi[br]le frère d'armes..."

01:01:21.22,01:01:23.01
"il combattra à vos côtés"

01:01:24.06,01:01:27.41
Ce sont des paroles de Garibaldi[br]mais l'affaire a été plus dure

01:01:29.02,01:01:31.05
Je n'ai jamais tant marché

01:01:31.90,01:01:33.17
Ah ! La marche de nuit[br]sur Gibilrossa !

01:01:33.38,01:01:35.05
Vous avez connu Bixio ?

01:01:35.26,01:01:36.66
Oui, un entêté !

01:01:37.34,01:01:39.41
Tous des entêtés et des extravagants

01:01:40.66,01:01:44.97
J'ai assisté par hasard[br]à la scène entre Bixio et La Massa...

01:01:45.34,01:01:48.65
et pour un instant[br]à la prise de Porta Termini

01:02:27.90,01:02:30.09
Je me suis bien amusé mademoiselle

01:02:30.46,01:02:32.81
Je n'ai jamais tant ri que le 28 mai

01:02:33.50,01:02:36.65
Le général nous voulait en vedette[br]au monastère de l'Origliene

01:02:37.38,01:02:39.69
Mais on avait beau frapper,[br]crier, jurer...

01:02:40.06,01:02:41.57
personne n'ouvrait...

01:02:41.78,01:02:44.81
C'était un couvent[br]de religieuses cloîtrées !

01:02:48.86,01:02:50.09
A propos mon Père,

01:02:50.30,01:02:52.77
demain nous irons[br]au monastère de Santo Spirito

01:02:52.98,01:02:56.33
prier sur le tombeau[br]de la Bienheureuse Corbera

01:02:56.70,01:02:59.85
Oui... ces braves petites sœurs...

01:03:00.22,01:03:03.81
sont informées de l'arrivée[br]de Leurs Excellences...

01:03:04.02,01:03:07.37
et font déjà les préparatifs[br]pour votre visite

01:03:07.74,01:03:08.69
Nous n'y manquons jamais...

01:03:08.90,01:03:11.70
le jour qui suit notre arrivée

01:03:20.86,01:03:23.21
Alors ? Qu'est-ce qui s'est passé ?

01:03:26.70,01:03:28.34
Je vais vous le dire ,

01:03:29.18,01:03:32.49
Tassoni, Aldrighetti,[br]moi et quelques autres...

01:03:33.02,01:03:35.69
nous essayons d'enfoncer la porte ,[br]rien à faire

01:03:36.38,01:03:39.73
Nous prenons une poutre[br]d'une maison bombardée...

01:03:39.94,01:03:44.01
et enfin la porte dégringole[br]avec un boucan d'enfer 

01:03:45.02,01:03:46.74
Nous entrons, un désert

01:03:48.06,01:03:49.78
Puis des cris désespérés...

01:03:49.98,01:03:51.70
provenant d'un couloir...

01:03:52.06,01:03:55.89
Les sœurs s'étaient réfugiées dans[br]la chapelle, tout contre l'autel

01:03:57.50,01:04:00.46
Qui sait ce qu'elles craignaient[br]de la part...

01:04:00.66,01:04:01.93
de ces jeunes exaltés

01:04:06.74,01:04:09.54
Elles étaient drôles à voir,[br]vieilles, laides...

01:04:09.74,01:04:14.09
avec leurs robes noires,[br]les yeux écarquillés, toutes prêtes...

01:04:14.78,01:04:16.18
au martyre...

01:04:16.90,01:04:18.77
Elles glapissaient[br]comme des chiennes

01:04:23.74,01:04:25.01
Tassoni leur crie,

01:04:25.66,01:04:29.62
"Rien à faire mes sœurs, on reviendra[br]quand vous nous procurerez..."

01:04:29.82,01:04:31.22
"des novices"

01:04:32.70,01:04:35.21
Et nous de rire à nous rouler par terre

01:04:35.42,01:04:37.49
Nous les avons laissées[br]la bouche sèche,

01:04:37.70,01:04:39.45
pour faire[br]le coup de feu des terrasses

01:04:39.66,01:04:41.81
Dix minutes après j'ai été blessé

01:04:42.14,01:04:45.10
Quels types vous deviez être ![br]J'aurais voulu être avec vous

01:04:46.30,01:04:47.97
Si vous aviez été là...

01:04:48.18,01:04:50.74
on n'aurait pas attendu les novices

01:05:30.42,01:05:34.09
Tancredi, ces vilaines choses[br]on les dit à son confesseur...

01:05:34.54,01:05:36.97
pas aux demoiselles à table...

01:05:37.82,01:05:39.85
Au moins quand je suis là moi

01:07:07.42,01:07:09.29
Il a raison...

01:07:09.66,01:07:11.38
et moi je l'aiderai

01:07:19.10,01:07:21.93
Mais il faut convenir[br]qu'il est un peu ignoble

01:07:25.78,01:07:29.57
Oh, la belle Gigogin...

01:07:44.70,01:07:51.09
"A quinze ans je flirtais déjà"

01:07:51.30,01:07:54.05
Avance donc d'un pas

01:07:54.26,01:07:58.17
Délice de mon cœur

01:07:59.38,01:08:05.69
"A seize ans je me suis mariée"

01:08:06.34,01:08:09.22
Avance donc d'un pas

01:08:09.42,01:08:13.13
Délice de mon cœur

01:08:14.58,01:08:21.18
"A dix-sept ans je suis partie"

01:08:21.50,01:08:24.33
Avance donc d'un pas

01:08:24.54,01:08:27.85
Délice de mon cœur

01:08:30.14,01:08:32.65
Vive l'Italie ! Vive l'Italie !

01:08:39.54,01:08:41.26
Vive l'Italie Unifiée !

01:08:43.30,01:08:44.78
Vive le Plébiscite !

01:08:58.54,01:09:00.41
Ne soyez pas si triste mon Père

01:09:00.62,01:09:02.89
Nous ne sommes pas[br]à un enterrement

01:09:04.22,01:09:06.57
C'est le vent... ce sale vent...

01:09:06.94,01:09:08.66
Remerciez-en le Seigneur

01:09:09.02,01:09:11.53
Sans ce vent l'air serait putride

01:09:36.22,01:09:38.05
Il faut voter dans l'ordre

01:09:38.26,01:09:41.29
Le premier arrivé vote le premier

01:09:42.10,01:09:44.69
Ici il n'est pas question...

01:09:48.54,01:09:50.45
Le "Cavour" de Donnafugata !

01:09:54.58,01:09:58.25
Excellence.[br]C'est un grand honneur pour moi

01:10:08.74,01:10:09.93
Don Onofrio !

01:10:11.74,01:10:13.61
Rotolo Onofrio

01:10:16.70,01:10:17.93
A voté

01:10:18.30,01:10:21.29
Non,[br]le Père Pirrone n'est pas résident

01:10:22.78,01:10:25.13
On arrête un instant !

01:10:25.82,01:10:28.01
Puis-je demander[br]à Vos Seigneuries...

01:10:28.22,01:10:31.05
d'accepter un petit verre ?

01:10:34.58,01:10:35.85
Les rafraîchissements !

01:10:38.18,01:10:39.58
Je vous en prie Excellence

01:10:45.82,01:10:46.73
Pars !

01:10:52.90,01:10:53.97
Excellence

01:10:54.18,01:10:56.85
Je prendrai du blanc.[br]Il est plus léger

01:10:57.22,01:10:58.94
Blanc, le drapeau des Bourbons

01:11:01.22,01:11:03.81
Je ne peux pas boire,[br]je ne me sens pas bien

01:11:04.02,01:11:05.81
J'ai un dérangement intestinal

01:11:06.18,01:11:09.81
Un jour comme celui-ci vos troubles[br]intestinaux sont secondaires !

01:11:10.82,01:11:12.69
Merci, je ne bois jamais

01:11:17.22,01:11:18.45
Don Calogero...

01:11:18.90,01:11:21.17
J'accepte avec grand plaisir

01:11:21.38,01:11:22.41
Merci Prince

01:11:28.34,01:11:30.29
Je voudrais trouver les mots...

01:11:31.30,01:11:34.29
mais les grandes joies[br]Prince sont muettes

01:12:03.14,01:12:05.33
C'est avec une grande émotion...

01:12:05.86,01:12:07.26
que je vais vous dire...

01:12:10.18,01:12:12.69
J'ai le très grand honneur...

01:12:13.22,01:12:15.73
de vous communiquer[br]les résultats du Plébiscite...

01:12:16.42,01:12:19.09
dans notre commune[br]de Donnafugata

01:12:28.42,01:12:33.97
"Le 22 octobre 1860,[br]à Donnafugata"

01:12:34.18,01:12:36.21
"à six heures de l'après-midi"

01:12:36.58,01:12:39.57
"la commission électorale[br]communale s'est réunie"

01:12:39.94,01:12:43.53
"pour examiner les votes[br]prononcés par plébiscite"

01:12:43.74,01:12:46.62
"par la population de cette commune"

01:12:47.62,01:12:49.65
"Le peuple sicilien"

01:12:50.02,01:12:52.69
"veut l'Italie une et indivisible"

01:12:53.22,01:12:55.25
"avec Victor-Emmanuel"

01:12:55.78,01:12:59.74
"roi constitutionnel[br]et ses descendants légitimes"

01:13:08.66,01:13:10.17
Et en plus il insiste !

01:13:10.78,01:13:11.41
C'est un idiot !

01:13:16.98,01:13:19.73
"Tous les votes recueillis et..."

01:13:25.90,01:13:28.17
"Tous les votes recueillis..."

01:13:33.38,01:13:35.57
"Tous les votes recueillis..."

01:13:36.58,01:13:39.09
"et le scrutin dépouillé"

01:13:39.74,01:13:40.69
"on a obtenu"

01:13:42.02,01:13:44.37
"les résultats suivants"

01:13:44.74,01:13:48.94
"Electeurs inscrits, 515"

01:13:49.70,01:13:52.69
"Votants, 512"

01:13:53.54,01:13:56.69
"OUI, 512"

01:14:00.18,01:14:02.45
"NON, zéro"

01:15:45.38,01:15:46.78
Et vous don Ciccio...

01:15:47.70,01:15:49.34
qu'avez-vous voté ?

01:15:55.94,01:15:58.77
Que craignez-vous ?[br]Ici, il n'y a que nous...

01:15:59.34,01:16:00.69
Le vent et les chiens

01:16:01.06,01:16:03.57
Excusez Excellence,[br]mais la question est inutile

01:16:04.30,01:16:07.41
A Donnafugata tous ont voté OUI

01:16:08.74,01:16:11.89
On dit que vous avez même conseillé[br]à voter comme ça

01:16:12.42,01:16:13.49
En effet

01:16:15.78,01:16:17.18
Vous avez voté OUI ?

01:16:30.86,01:16:33.82
Non Excellence. J'avais voté NON !

01:16:35.42,01:16:36.98
Cent fois NON !

01:16:37.82,01:16:40.97
Oui, je sais Excellence[br]ce que vous m'aviez dit...

01:16:42.62,01:16:44.97
La nécessité, l'unité, l'opportunité...

01:16:45.42,01:16:46.82
et peut-être que c'est vrai

01:16:47.18,01:16:50.17
Moi la politique je n'y entends rien[br]etje n'en fais pas

01:16:50.86,01:16:53.53
Mais don Ciccio Tumeo[br]est un honnête homme

01:16:55.50,01:16:58.33
Un artiste manqué si on veut.[br]Pauvre et misérable

01:16:58.70,01:17:00.57
Avec les pantalons troués...

01:17:01.74,01:17:04.73
mais je n'ai pas oublié[br]les bienfaits reçus

01:17:05.74,01:17:07.46
Et vous le savez Excellence...

01:17:07.82,01:17:10.65
Ce fut la reine Isabelle, l'espagnole...

01:17:11.50,01:17:14.97
alors duchesse de Calabre,[br]qui me fit étudier...

01:17:16.30,01:17:18.65
et m'a permis de devenir ce que je suis

01:17:19.02,01:17:20.74
Organiste de l'Eglise...

01:17:21.02,01:17:23.93
honoré de la bienveillance[br]de Votre Excellence

01:17:27.50,01:17:31.62
Aux années de misère, quand[br]on envoyait la supplique à la Cour...

01:17:32.74,01:17:36.09
les cinq onces de secours arrivaient,[br]sûres comme la mort

01:17:38.06,01:17:41.13
Ces saints Rois et ces belles Reines...

01:17:41.34,01:17:43.77
que diront-ils du haut du ciel ?

01:17:45.26,01:17:48.29
Que le fils de Leonardo Tumeo[br]les a trahis ?

01:17:51.02,01:17:52.45
Excellence NON !

01:17:53.42,01:17:56.41
Heureusement, au paradis[br]on connaît la vérité !

01:18:01.62,01:18:03.49
J'admire votre fidélité

01:18:04.18,01:18:05.90
Mais il faut comprendre...

01:18:06.66,01:18:09.57
que le peuple était surexcité[br]par Garibaldi

01:18:11.42,01:18:14.85
Le plébiscite était le seul[br]remède contre l'anarchie

01:18:15.78,01:18:17.57
Pour nous, c'est le moindre mal

01:18:19.50,01:18:21.09
Les Savoie, au fond...

01:18:22.90,01:18:24.30
sont aussi une monarchie

01:18:25.82,01:18:28.46
Les intérêts des personnes[br]auxquelles vous êtes dévoué...

01:18:29.18,01:18:32.29
sont frustrés[br]par ces événements, certes...

01:18:34.42,01:18:36.77
mais encore en vie, valides

01:18:40.22,01:18:41.89
Quelque chose devait changer...

01:18:44.66,01:18:47.01
pour que tout reste[br]comme auparavant

01:18:49.30,01:18:51.02
La révolution est terminée

01:18:51.54,01:18:54.85
Espérons que l'Italie née[br]aujourd'hui pourra prospérer

01:18:57.30,01:18:58.89
Mais moi j'avais dit non

01:18:59.38,01:19:02.37
Et ces cochons de la municipalité[br]avalent mon opinion...

01:19:02.74,01:19:04.93
et la crachent comme ils veulent

01:19:06.34,01:19:09.25
Je dis noir et ils me font dire blanc

01:19:11.22,01:19:13.09
J'étais un "fidèle sujet"...

01:19:13.46,01:19:16.13
et maintenant "un sale bourbon"

01:19:16.98,01:19:18.70
Maintenant tous Savoyards

01:19:20.18,01:19:23.33
Les Savoyards, moi[br]je les mange avec le café

01:19:31.70,01:19:35.33
Dites-moi,[br]vous qui voyez tant de monde ici...

01:19:36.50,01:19:39.65
que pense-t-on de don Calogero[br]à Donnafugata ?

01:19:41.14,01:19:45.10
Je croyais avoir manifesté[br]clairement mon opinion

01:19:46.42,01:19:50.21
Je voudrais beaucoup savoir[br]la vérité sur lui et sa famille

01:19:53.54,01:19:55.18
La vérité Excellence...

01:19:56.34,01:19:59.17
est que don Calogero est très riche

01:20:00.66,01:20:02.22
très influent

01:20:04.18,01:20:05.25
Avare

01:20:06.10,01:20:08.13
Intelligent en diable

01:20:09.50,01:20:11.81
Excellence, il fallait le voir[br]jusqu'en mai...

01:20:12.18,01:20:15.49
aller dans la campagne,[br]pareil à une chauve-souris...

01:20:16.34,01:20:18.53
en voiture, à dos de mulet, à pied...

01:20:19.38,01:20:21.41
qu'il pleuve ou qu'il fasse beau

01:20:21.98,01:20:24.86
Et où il passait se formaient[br]des cercles secrets...

01:20:25.06,01:20:27.81
Il ouvrait la route à ceux[br]qui allaient venir

01:20:28.18,01:20:30.21
Une vraie peste !

01:20:32.82,01:20:36.13
Et ce n'est que le début[br]de la carrière de Don Calogero

01:20:36.50,01:20:39.33
Dans quelques mois il sera député

01:20:39.86,01:20:41.58
au Parlement de Turin

01:20:42.74,01:20:46.70
Plus tard, à la liquidation[br]des biens ecclésiastiques...

01:20:47.06,01:20:49.73
pour quatre sous il s'accaparera...

01:20:49.94,01:20:53.90
le fief de Marca,[br]le fief de Fondacello, le fief...

01:20:55.54,01:20:59.17
Et sera le plus grand propriétaire[br]de la province

01:21:00.98,01:21:03.01
Voilà ce qu'est don Calogero

01:21:03.70,01:21:06.37
L'homme nouveau tel qu'il doit être

01:21:09.22,01:21:10.94
C'est dommage tout de même[br]qu'il soit ainsi

01:21:16.82,01:21:18.69
Et la famille ?

01:21:19.22,01:21:20.45
Les autres ?

01:21:20.82,01:21:24.78
Sa femme, personne ne l'a vue[br]depuis des années...

01:21:26.02,01:21:27.17
sauf moi

01:21:27.86,01:21:30.77
Elle ne sort[br]que pour la messe de cinq heures

01:21:30.98,01:21:32.62
quand il n'y a personne

01:21:33.78,01:21:36.93
Moi une fois je suis tombé du lit[br]pour la voir

01:21:37.46,01:21:38.86
Parole d'honneur...

01:21:39.22,01:21:42.05
elle est belle comme le soleil

01:21:43.54,01:21:46.53
Don Calogero n'a pas tort,[br]ce vilain cafard...

01:21:46.90,01:21:49.09
de la tenir loin des hommes

01:21:50.90,01:21:53.09
Mais même les maisons[br]les mieux gardées...

01:21:53.46,01:21:57.09
laissent transpirer quelque chose,[br]les servantes parlent

01:21:57.74,01:22:01.25
Et il semble que Donna Bastiana[br]soit une sorte...

01:22:02.06,01:22:03.49
d'animal...

01:22:04.34,01:22:07.65
Elle ne sait ni lire ni écrire...

01:22:08.10,01:22:11.01
et ne sait même pas aimer sa fille

01:22:11.42,01:22:12.45
Bonne...

01:22:13.78,01:22:15.81
pour le lit c'est tout

01:22:16.34,01:22:20.46
Et ce doit être vrai.[br]Vous savez qui était son père ?

01:22:22.74,01:22:25.41
Un de vos métayers de Runci

01:22:26.26,01:22:28.45
Un certain Peppe Giunta...

01:22:29.22,01:22:32.13
si sale et si sauvage...

01:22:32.66,01:22:35.33
qu'on l'appelait "Peppe Merda"

01:22:36.66,01:22:38.53
Pardonnez le mot Excellence

01:22:39.30,01:22:42.61
Deux ans après la fuite de[br]don Calogero avec Bastiana...

01:22:42.98,01:22:46.77
on l'a trouvé mort sur[br]le sentier de Rampinzeri...

01:22:47.14,01:22:49.49
avec douze plombs de chasse[br]dans le dos

01:22:50.82,01:22:53.17
C'est un scandale !

01:22:54.34,01:22:56.85
Et moi qui espérais qu'il[br]épouserait Concetta !

01:22:57.22,01:23:00.69
C'est un traître.[br]Comme tous les libéraux de son espèce

01:23:01.54,01:23:04.05
Il a trahi le Roi, puis nous-mêmes...

01:23:05.54,01:23:07.89
avec son faux air...

01:23:09.06,01:23:13.02
avec ses phrases mielleuses[br]et ses actions venimeuses

01:23:13.70,01:23:15.89
Voilà ce qui arrive...

01:23:16.58,01:23:19.25
avec les gens qui n'ont pas[br]notre sang

01:23:23.62,01:23:24.69
Bois

01:23:32.10,01:23:35.25
Je l'ai toujours dit[br]mais personne ne m'écoute

01:23:36.42,01:23:38.29
Je ne le supporte pas ce gandin

01:23:38.66,01:23:41.01
Toi seul as perdu la tête pour lui

01:23:42.58,01:23:45.38
Et il a l'impudence de te charger toi[br]le prince Salina

01:23:45.58,01:23:49.73
père de la petite qu'il a trompée,[br]de faire ses propositions...

01:23:50.26,01:23:52.45
au père de cette catin, de cette...

01:23:52.82,01:23:55.01
Tu ne dois pas le faire,[br]tu ne dois pas !

01:23:55.54,01:23:56.61
Assez !

01:24:01.82,01:24:03.81
Tu ne sais pas ce que tu dis

01:24:04.58,01:24:06.22
Angelica n'est pas une catin

01:24:08.18,01:24:11.49
Elle le deviendra peut-être.[br]Pour le moment c'est une demoiselle

01:24:11.86,01:24:15.33
plus belle que les autres[br]qui veut faire un bon mariage

01:24:16.02,01:24:19.81
Peut-être un peu amoureuse de[br]notre Tancredi, comme tous

01:24:20.18,01:24:22.37
Et elle a de l'argent, beaucoup

01:24:23.58,01:24:27.49
Oui, de l'argent à nous, mais[br]fort bien administré par don Calogero

01:24:28.18,01:24:29.58
Tancredi en a besoin

01:24:29.98,01:24:32.57
C'est un grand seigneur.[br]Ambitieux, dépensier...

01:24:32.78,01:24:34.53
il a besoin d'argent

01:24:35.38,01:24:38.85
Il n'a jamais rien promis à Concetta,[br]donc pas de trahison

01:24:39.30,01:24:42.18
C'est un jeune homme[br]selon ces temps...

01:24:42.38,01:24:45.10
tant en politique[br]que dans sa vie privée

01:24:46.14,01:24:48.61
C'est le meilleur garçon[br]que je connaisse

01:24:48.98,01:24:50.85
Et tu le sais bien

01:25:30.26,01:25:32.61
Et je ne veux plus[br]t'entendre pleurnicher

01:25:32.98,01:25:35.17
dans ma chambre ![br]Dans mon lit !

01:25:36.34,01:25:38.06
Assez d'histoires comme ça !

01:25:38.42,01:25:41.89
C'est moi qui décide ![br]Et j'ai décidé, depuis longtemps déjà

01:25:42.58,01:25:43.65
Assez !

01:25:52.66,01:25:53.89
Dormons maintenant

01:25:57.82,01:25:59.65
Demain je vais à la chasse...

01:26:00.18,01:26:01.74
et je me lève de bonne heure

01:26:02.90,01:26:04.46
Bonne nuit Stella chérie

01:26:36.62,01:26:38.85
Vous me parlez de tout...

01:26:39.10,01:26:42.37
d'une mère sauvage,[br]d'un grand-père crotté...

01:26:42.58,01:26:46.37
mais pas de ce qui m'intéresse ,[br]de mademoiselle Angelica

01:26:48.66,01:26:51.65
Il n'y a rien à dire,[br]elle parle d'elle-même

01:26:51.86,01:26:55.37
Elle a la beauté de la mère[br]sans la puanteur du grand-père

01:26:55.58,01:26:58.54
Intelligente. Une vraie dame.

01:26:58.90,01:27:00.54
Revenue du collège...

01:27:00.74,01:27:03.97
elle m'a joué ma mazurka, chez elle

01:27:04.50,01:27:06.73
Elle jouait mal, mais...

01:27:06.94,01:27:08.81
elle était délicieuse à voir...

01:27:09.02,01:27:12.45
avec ses tresses noires,[br]ses yeux, sa peau...

01:27:12.66,01:27:14.38
ce sein...

01:27:15.02,01:27:20.30
Ses draps de lit doivent[br]avoir le parfum du paradis

01:27:20.50,01:27:23.65
Calmez-vous don Ciccio

01:27:24.30,01:27:27.61
Vous allez dorénavant parler d'elle[br]avec le respect qui lui est dû

01:27:28.10,01:27:29.50
Aujourd'hui même...

01:27:30.42,01:27:34.13
je demanderai sa main[br]pour mon neveu Tancredi.

01:27:34.74,01:27:38.13
Vous êtes le premier à savoir[br]et vous allez payer cet avantage

01:27:38.38,01:27:41.65
Je vous enfermerai dans la salle[br]des fusils avec les chiens...

01:27:42.02,01:27:46.09
ainsi rien ne transpirera avant[br]que j'en parle à don Calogero

01:27:46.82,01:27:47.73
Allons...

01:27:48.10,01:27:50.45
Excellence, c'est une saleté

01:27:51.30,01:27:54.93
Un neveu à vous ne doit pas épouser[br]la fille d'un de vos ennemis...

01:27:55.30,01:27:57.65
qui vous ont toujours[br]tiré dans les jambes

01:27:57.86,01:28:01.17
La séduire aurait été[br]un acte de conquérant

01:28:01.42,01:28:03.73
mais là c'est sans conditions

01:28:04.90,01:28:07.93
C'est la fin des Falconeri...[br]et des Salina !

01:28:21.86,01:28:24.01
Ce mariage n'est la fin de rien

01:28:24.22,01:28:26.29
mais le début de tout

01:28:26.62,01:28:29.34
Et selon les meilleures traditions

01:28:31.94,01:28:34.29
Ce sont des choses que[br]vous ne pouvez comprendre !

01:28:37.06,01:28:38.29
Allons !

01:28:39.54,01:28:41.18
D'accord n'est-ce pas ?

01:29:25.42,01:29:29.21
Ne compliquons pas les choses.[br]C'est un simple baiser

01:29:30.98,01:29:32.70
Et c'est moi qui vous ai fait appeler

01:29:33.06,01:29:34.46
C'est vrai, mais...

01:29:40.58,01:29:42.93
Je voulais vous communiquer[br]une lettre...

01:29:43.30,01:29:44.86
de mon neveu...

01:29:45.38,01:29:46.61
arrivée hier soir...

01:29:47.14,01:29:49.81
non, cette nuit pour être exact

01:29:51.46,01:29:55.25
Il y déclare sa passion[br]pour mademoiselle...

01:29:55.94,01:29:57.17
votre fille

01:29:58.98,01:30:00.85
Et il me charge officiellement...

01:30:03.14,01:30:05.33
de vous demander sa main

01:30:16.26,01:30:18.93
Maintenant c'est à vous[br]de vous prononcer

01:30:25.14,01:30:27.78
Excusez-moi Prince...

01:30:29.54,01:30:32.85
cette belle surprise[br]m'a coupé la parole

01:30:33.98,01:30:37.97
Moi qui lis dans le cœur[br]et l'esprit d'Angelica...

01:30:38.50,01:30:41.77
je crois pouvoir dire[br]que l'attachement de don Tancredi...

01:30:41.98,01:30:43.89
-qui nous honore tant-

01:30:44.62,01:30:46.45
est sincèrement partagé

01:31:06.18,01:31:08.69
Que Dieu protége ces noces

01:31:09.06,01:31:10.93
Votre joie est la mienne

01:31:19.26,01:31:20.37
Le temps se gâte

01:31:22.98,01:31:26.77
Inutile de vous dire combien[br]les Falconeri sont illustres

01:31:27.62,01:31:29.93
Venus en Sicile[br]avec Charles d'Anjou...

01:31:30.14,01:31:34.05
ils ont prospéré sous les Aragons,[br]les Espagnols et les Bourbons...

01:31:34.26,01:31:37.01
s'il m'est permis[br]de les nommer devant vous

01:31:37.70,01:31:41.66
Pairs du royaume, Grands d'Espagne,[br]Chevaliers de Santiago

01:31:45.38,01:31:48.05
Mais s'il est superflu[br]que je vous parle...

01:31:48.58,01:31:50.61
des mérites de la famille Falconeri

01:31:50.98,01:31:54.45
il est également inutile[br]de vous dire, hélas...

01:31:54.82,01:31:57.81
que la situation économique[br]de mon neveu Tancredi...

01:31:58.18,01:32:00.37
n'est pas à la hauteur de son nom

01:32:01.30,01:32:05.01
Mon beau-frère Ferdinando[br]n'a pas été un père prévoyant

01:32:05.22,01:32:07.21
Ses munificences de grand seigneur...

01:32:07.42,01:32:10.22
ont compromis le patrimoine[br]de mon neveu

01:32:11.66,01:32:12.77
Mais, don Calogero !

01:32:13.90,01:32:15.54
le résultat de tous ces désastres...

01:32:17.90,01:32:19.17
c'est Tancredi

01:32:20.10,01:32:22.05
Nous le savons bien nous autres

01:32:22.86,01:32:25.42
Il est impossible d'être aussi...

01:32:26.38,01:32:28.61
distingué, sensible...

01:32:29.30,01:32:31.25
et séduisant que Tancredi...

01:32:31.46,01:32:34.53
sans qu'aient été dilapidés[br]une douzaine de patrimoines

01:32:34.90,01:32:36.13
C'est ainsi en Sicile

01:32:36.66,01:32:39.49
Je sais tout cela,[br]et d'autres choses encore

01:32:39.86,01:32:43.01
Mais l'amour Excellence,[br]l'amour est tout

01:32:43.70,01:32:45.57
Je le sais bien moi

01:32:47.42,01:32:48.29
Ecoutez-moi...

01:32:49.42,01:32:52.77
En homme du monde[br]je veux jouer cartes sur table

01:32:53.50,01:32:56.46
Les jeunes gens doivent savoir[br]sur quoi compter

01:32:58.86,01:33:00.77
Par contrat de mariage...

01:33:01.58,01:33:03.49
je donnerai à ma fille...

01:33:04.18,01:33:06.53
le fief de Settesoli

01:33:13.62,01:33:15.81
1010 hectares

01:33:18.38,01:33:19.65
tout en blé

01:33:20.86,01:33:21.97
Des terres...

01:33:22.58,01:33:24.22
fraîches et aérées

01:33:24.42,01:33:27.65
Et 500 hectares de vignes et d'oliviers

01:33:29.26,01:33:30.53
à Gibildolce

01:33:42.94,01:33:45.33
Le jour du mariage,[br]je remettrai à l'époux...

01:33:45.54,01:33:47.77
vingt sacs de dix mille onces...

01:33:53.86,01:33:55.73
Ma famille est tout pour moi

01:33:57.66,01:34:00.69
"Personne n'a vu la femme de[br]don Calogero depuis des années"

01:34:01.70,01:34:02.93
"Excepté moi"

01:34:03.30,01:34:05.65
"Elle ne sort que pour[br]la première messe, à cinq heures"

01:34:06.06,01:34:07.73
"Quand il n'y a personne"

01:34:08.90,01:34:11.89
"Une fois je me suis[br]tiré du lit pour la voir"

01:34:12.90,01:34:14.46
"Parole d'honneur Excellence..."

01:34:14.82,01:34:17.17
"elle est belle comme le Soleil"

01:34:28.90,01:34:31.89
"Don Calogero n'a pas tort,[br]le vilain cafard..."

01:34:32.26,01:34:34.61
"de la garder loin[br]des autres hommes"

01:34:45.54,01:34:47.73
Il est vrai que[br]je demeure les mains vides

01:34:48.10,01:34:50.61
Mais une fille est une fille

01:34:51.50,01:34:53.97
Je sais déjà que ce que je vais vous dire...

01:34:54.38,01:34:56.69
fera peu d'impression[br]sur vous qui descendez...

01:34:57.06,01:34:59.89
de l'empereur Titus et[br]de la reine Bérénice

01:35:00.42,01:35:02.45
Mais les Sedara aussi...

01:35:03.14,01:35:06.29
par un titre qu'accorda[br]Sa Majeté Ferdinand IV...

01:35:06.90,01:35:08.54
sont nobles

01:35:09.86,01:35:12.05
Bravo, bravo don Calogero ![br]Au revoir

01:35:12.42,01:35:15.73
J'ai tous les papiers en règle.[br]Il reste les formalités

01:35:16.10,01:35:18.61
Et un jour[br]on saura que votre neveu...

01:35:20.02,01:35:23.53
a épousé la fille[br]du baron Sedara del Biscotto

01:35:23.74,01:35:25.49
Compliments !

01:35:27.46,01:35:30.13
J'ai tous les papiers, il ne manque...

01:35:47.74,01:35:50.77
Je regrette mais[br]je ne pouvais pas agir autrement

01:35:51.14,01:35:52.70
Je comprends ça Excellence

01:35:53.50,01:35:54.93
Tout a bien marché au moins ?

01:35:56.90,01:35:58.62
On ne peut mieux

01:36:01.98,01:36:03.57
Au revoir don Ciccio

01:36:05.86,01:36:07.26
Et excusez-moi

01:36:21.66,01:36:24.62
"C'était une froide journée[br]de janvier"

01:36:24.82,01:36:28.25
"L'atmosphère rendue rigide[br]par un vent glacé"

01:36:28.46,01:36:31.02
"paraissait plus lourde[br]dans son calme mortel"

01:36:31.22,01:36:34.29
"Depuis des heures[br]il neigeait à gros flocons"

01:36:34.50,01:36:38.05
"mais sur la route déserte[br]un pauvre petit cheval"

01:36:38.26,01:36:41.85
"avec sur le dos[br]une couverture grossière"

01:36:45.02,01:36:48.57
"traînait péniblement[br]une charrette à deux roues"

01:36:48.94,01:36:51.17
"Hue ! Maudite bête !"

01:36:51.38,01:36:54.97
"Criait le vilain qui[br]par habitude parlait à son cheval"

01:37:09.94,01:37:12.74
Excellence,[br]Monsieur Tancredi est arrivé !

01:37:13.02,01:37:16.09
Il fait décharger ses bagages

01:37:26.06,01:37:27.25
Oncle !

01:37:31.46,01:37:33.85
Ne me touche pas, je suis une éponge

01:37:35.98,01:37:38.97
Comme je suis content de te revoir !

01:37:41.74,01:37:44.25
Excusez mon émotion

01:37:44.58,01:37:47.17
J'ai amené avec moi[br]le comte Cavriaghi de Milan

01:37:47.38,01:37:50.18
qui était venu à la villa[br]avec le général

01:37:50.46,01:37:53.29
Et là c'est mon ordonnance,[br]le lancier Moroni

01:38:08.54,01:38:10.89
Et on disait que chez vous[br]il ne pleuvait jamais !

01:38:11.90,01:38:13.93
Deux jours que nous barbotons

01:38:23.42,01:38:25.61
Excusez-moi, je suis trempé

01:38:30.46,01:38:33.05
Je me suis permis d'amener[br]le comte Cavriaghi

01:38:33.26,01:38:35.85
Tu l'as connu[br]à Palerme avec le général...

01:38:36.22,01:38:37.62
notre général

01:38:43.46,01:38:47.21
En Sicile quelquefois[br]nous avons de vrais déluges

01:38:48.54,01:38:52.50
Et même des pneumonies,[br]faites attention ou vous prendrez mal

01:38:54.94,01:38:58.57
Du feu dans la chambre de Tancredi[br]et la chambre d'amis.

01:38:58.94,01:39:01.77
Prépare la petite pièce[br]pour le soldat

01:39:14.14,01:39:16.53
Je ne comprends pas, expliquez-moi

01:39:16.74,01:39:19.09
vous étiez rouges[br]comme des langoustes

01:39:21.46,01:39:25.01
Les Garibaldiens ne portent plus[br]la chemise rouge ?

01:39:26.70,01:39:28.34
Plus question de Garibaldi[br]et de Garibaldiens

01:39:28.74,01:39:30.61
On l'était, on ne l'est plus

01:39:31.34,01:39:32.90
Cavriaghi et moi...

01:39:33.26,01:39:37.05
nous sommes officiers de l'armée[br]de SM le roi d'Italie

01:39:37.98,01:39:41.01
Quand l'armée de Garibaldi[br]a été dissoute, on nous a proposé

01:39:41.22,01:39:43.89
ou de renter chez nous,[br]ou d'entrer dans les armées royales

01:39:44.10,01:39:47.98
Lui, moi et tant d'autres[br]avons choisi l'armée, la vraie

01:39:48.18,01:39:50.93
Avec les autres[br]ce n'était plus possible

01:39:51.14,01:39:52.33
Quelle racaille !

01:39:52.78,01:39:53.65
Miséricorde !

01:39:53.86,01:39:55.81
Bonne pour tirailler et c'est tout

01:39:56.02,01:39:58.98
Maintenant nous sommes officiers[br]pour de bon...

01:39:59.30,01:40:02.18
on ne vole plus les poulets

01:40:02.74,01:40:04.46
De Palerme jusqu'ici

01:40:05.02,01:40:08.25
on disait [br]"Service de Sa Majesté"

01:40:08.46,01:40:09.69
et on nous changeait les chevaux

01:40:10.22,01:40:12.09
Vous nous direz tout plus tard

01:40:12.46,01:40:14.49
Maintenant prenez votre bain

01:40:16.30,01:40:17.86
Avec ta permission...

01:40:20.94,01:40:24.09
Non ![br]Je dois vous montrer la bague

01:40:25.10,01:40:26.82
La bague pour Angelica

01:40:33.42,01:40:34.98
Qu'elle est belle !

01:40:40.94,01:40:43.45
C'est beau... Très beau

01:40:46.54,01:40:47.77
N'est-ce pas ?

01:40:49.02,01:40:49.85
Elle te plaît ?

01:40:50.06,01:40:51.13
Beaucoup

01:41:00.38,01:41:02.17
Ça t'a coûté cher ?

01:41:02.66,01:41:04.41
J'ai su choisir convenablement

01:41:04.78,01:41:08.74
Les 220 onces que tu m'as données[br]m'ont suffi aussi...

01:41:09.10,01:41:11.77
Pour de petits cadeaux d'adieu.[br]Je vois ça.

01:41:13.53,01:41:16.17
Voici notre lieutenant ![br]Qu'est-ce que c'est ?

01:41:16.53,01:41:19.05
Un petit hommage pour[br]mademoiselle Concetta

01:41:20.85,01:41:22.57
Les "Chants" d'Aleardi ?

01:41:23.89,01:41:25.93
Espérons que cela lui plaira

01:41:34.45,01:41:36.01
Mademoiselle Concetta...

01:41:36.49,01:41:39.16
C'est Aleardi, mon poète préféré

01:41:39.53,01:41:41.73
Je me suis permis de vous l'apporter

01:41:42.41,01:41:44.61
j'ai fait graver vos initiales

01:41:46.89,01:41:48.61
"Toujours sourde"

01:41:49.13,01:41:51.01
Sourde ? Mais j'entends très bien

01:41:51.37,01:41:52.44
Sourde à mes soupirs

01:41:59.21,01:42:02.84
Je peux entrer ?[br]Excusez, mais j'ai appris...

01:42:15.77,01:42:17.41
Tiens ma belle...

01:42:19.49,01:42:21.72
Un cadeau de ton Tancredi

01:42:23.37,01:42:25.57
Et remercie aussi mon oncle

01:42:28.65,01:42:29.56
Viens

01:43:31.69,01:43:33.09
Où vas-tu ?

01:43:39.21,01:43:40.77
C'est plein de rats

01:44:10.89,01:44:12.12
On y va ?

01:44:41.77,01:44:43.49
Où tu es ?

01:45:18.41,01:45:19.97
Tancredi, où tu es ?

01:45:36.81,01:45:39.61
Quelle peur ![br]Vous savez qu'il y a des rats ?

01:45:39.81,01:45:42.69
Le contraire m'étonnerait.[br]Et Tancredi ?

01:45:43.05,01:45:44.77
Je ne le trouve plus

01:45:46.37,01:45:47.65
Venez

01:45:53.25,01:45:55.00
Je t'ai fait peur ?

01:45:58.25,01:46:00.29
La voici encore... Fuyons

01:46:00.65,01:46:01.56
Viens

01:46:02.41,01:46:06.04
Ça suffit. Mais où allez-vous ?[br]Je suis fatigué

01:46:06.41,01:46:09.29
Qu'il est grand ce palais ![br]Combien de pièces ?

01:46:09.81,01:46:12.48
Personne ne le sait.[br]Pas même mon oncle

01:46:12.85,01:46:15.32
Pour lui un palais[br]dont on connaît toutes les pièces

01:46:15.53,01:46:17.41
n'est pas digne d'être habité

01:46:21.01,01:46:22.41
La pauvre, elle est restée seule

01:46:22.77,01:46:23.68
Et les autres ?

01:46:24.21,01:46:26.09
Concetta est dans le jardin

01:46:27.89,01:46:29.69
Paolo est descendu à la diligence

01:46:29.89,01:46:31.61
recevoir un hôte

01:46:33.17,01:46:35.37
Quelqu'un qui arrive de Turin

01:46:36.05,01:46:38.09
Allons-nous-en. Viens

01:46:38.49,01:46:41.13
Non, je ne veux rien voir

01:46:41.33,01:46:43.37
J'ai décidé. Je pars

01:46:43.77,01:46:45.76
Pourquoi devrais-je rester ?

01:46:46.13,01:46:47.53
Concetta ne m'aime pas

01:46:47.73,01:46:49.48
Tu lui as parlé au moins ?

01:46:49.81,01:46:51.80
A quoi bon ?[br]Pour elle je ne suis...

01:46:52.33,01:46:54.21
qu'un ver de terre...

01:46:54.41,01:46:57.24
C'est donc parmi les vers de terre

01:46:57.45,01:46:58.96
que je trouverai ma compagne

01:47:00.21,01:47:03.04
Mais parle-lui. Tu décideras après

01:47:03.25,01:47:05.40
Mais c'est peut-être mieux comme ça

01:47:05.89,01:47:07.17
Je vais t'expliquer

01:47:07.85,01:47:11.00
Concetta est sicilienne,[br]elle n'a jamais quitté l'île.

01:47:11.25,01:47:14.37
Elle n'aimera pas Milan où[br]pour avoir un plat de macaroni...

01:47:14.73,01:47:16.29
il faut s'y prendre[br]un mois à l'avance

01:47:16.65,01:47:19.96
De vos macaroni,[br]je lui en aurais procuré des caisses...

01:47:20.33,01:47:21.89
Plus grandes que celle-ci

01:47:22.25,01:47:24.45
Nous deux on s'en va. Adieu...

01:47:49.93,01:47:53.08
Pauvre petit comte,[br]Concetta ne veut rien entendre

01:47:53.45,01:47:55.65
Concetta est une sotte

01:47:56.17,01:47:57.73
Que prétend-elle ?

01:47:58.09,01:48:01.08
Cavriaghi est un beau garcon,[br]il a des terres en Briance...

01:48:01.93,01:48:04.13
Un excellent parti

01:48:12.81,01:48:14.85
C'est toi que Concetta aime

01:48:19.69,01:48:21.89
C'est pour cela que tu l'as amené ici ?

01:48:25.61,01:48:27.97
C'est ça, je crois que oui

01:48:30.09,01:48:31.65
Mais pas du tout...

01:48:36.49,01:48:39.48
Alors écoute-moi bien.[br]Concetta a raison

01:48:39.93,01:48:42.76
Etre amoureuse de toi[br]et puis l'épouser lui

01:48:43.13,01:48:46.28
c'est comme boire de l'eau[br]après avoir goûté...

01:48:49.37,01:48:50.93
Goûté quoi ?

01:48:51.29,01:48:52.85
Goûté... disons...

01:48:53.37,01:48:54.77
du marsala

01:49:13.21,01:49:17.17
Quelles chambres étranges.[br]Qui donc a pu y habiter ?

01:49:17.53,01:49:20.20
Personne n'y a jamais habité[br]mon amour

01:49:20.57,01:49:22.45
Ici mes ancêtres[br]venaient commettre

01:49:22.65,01:49:24.77
leurs petites infractions aux règles

01:49:24.97,01:49:28.85
et se procurer des souvenirs[br]différents du commun des mortels

01:49:31.61,01:49:33.65
Des infractions aux règles ?

01:49:37.37,01:49:39.41
Mais oui, ils s'ennuyaient ![br]Mon amour !

01:50:04.21,01:50:06.88
Le chevalier[br]Chevalley de Monterzuolo ?

01:50:07.93,01:50:08.97
Oui, c'est moi

01:50:09.17,01:50:11.21
Je suis le fils du Prince Salina

01:50:13.81,01:50:18.25
Mon père m'a envoyé vous prier[br]de venir loger au palais

01:50:18.61,01:50:20.33
C'est bien gentil

01:50:20.69,01:50:22.89
Couvrez-vous,[br]le Soleil est très fort ici

01:50:23.25,01:50:25.29
Merci, couvrez-vous donc aussi

01:50:25.81,01:50:27.85
En vérité j'avais l'intention...

01:50:28.21,01:50:30.88
de repartir[br]après avoir parlé au prince

01:50:31.41,01:50:34.08
Pour lui parler vous devrez[br]toujours venir chez nous

01:50:34.85,01:50:36.13
Par ici

01:50:37.25,01:50:39.13
- Je m'en occupe[br]- Laissez

01:50:39.33,01:50:40.81
- Je vous prie[br]- Mais non

01:50:41.01,01:50:42.57
Vous devez accepter

01:50:42.89,01:50:44.32
- Merci[br]- Je vous en prie

01:50:45.45,01:50:47.17
- C'est lourd Prince ?[br]- Du tout

01:50:47.37,01:50:48.96
- C'est le palais là-haut ?[br]- Oui Chevalier

01:50:50.93,01:50:52.49
Ils ne sont pas là-haut,[br]je vous assure.

01:50:52.69,01:50:54.57
Peut-être dans le jardin...

01:51:35.57,01:51:37.29
Tu crois que je ne t'aime plus ?

01:51:52.85,01:51:54.08
Tu as peur ?

01:51:55.25,01:51:57.92
Je te désire[br]mais je ne te prendrai pas maintenant

01:51:58.61,01:52:00.65
seulement[br]quand tu seras ma femme

01:52:13.49,01:52:15.24
Pauvre de moi ![br]Excusez-moi...

01:52:28.37,01:52:29.85
Caterina, viens !

01:52:33.01,01:52:35.05
Regardez, voilà le visiteur

01:53:27.89,01:53:29.93
Mais que te veut-il vraiment ?

01:53:32.05,01:53:33.33
Je n'en sais rien

01:53:33.97,01:53:37.12
Il parcourt la Sicile depuis un mois

01:53:37.61,01:53:40.33
L'estomac démoli[br]par la cuisine à l'huile

01:53:40.69,01:53:44.48
et dans l'attente que[br]les brigands y fassent un trou

01:53:45.81,01:53:48.64
Je vais lui proposer[br]une partie de whist

01:53:59.81,01:54:01.13
Chevalley...

01:54:03.09,01:54:04.65
que diriez-vous[br]d'une partie de cartes ?

01:54:04.97,01:54:09.60
Excellence je vous demande une[br]entrevue pour pouvoir partir demain

01:54:09.97,01:54:12.49
Partir ? Vous n'êtes pas bien ici ?

01:54:14.81,01:54:16.09
Si, certainement

01:54:16.29,01:54:18.73
Vous êtes dans ma maison...

01:54:19.25,01:54:21.92
en otage tant que cela me plaira

01:54:23.73,01:54:24.80
Venez

01:54:25.85,01:54:28.84
Attention au révérend Père,[br]il gagne toujours

01:54:29.69,01:54:32.52
Asseyez-vous,[br]je suis votre partenaire

01:54:38.01,01:54:39.41
Je marque les points

01:55:00.89,01:55:03.09
Vous êtes vraiment de Milan ?

01:55:03.61,01:55:06.28
Et comment avez-vous échoué ici ?

01:55:06.81,01:55:10.77
J'abuse de l'hospitalité du Prince[br]et je m'en trouve très bien

01:55:46.01,01:55:48.08
Si vous voulez visiter Donnafugata...

01:55:48.29,01:55:51.33
je pourrai vous montrer[br]la maison du baron Mutolo

01:55:51.93,01:55:53.97
Francesco Paolo ![br]Ne commence pas !

01:55:54.33,01:55:56.64
Elle est vide actuellement[br]car la famille n'y vit plus...

01:55:57.05,01:55:59.69
depuis que le fils du baron...

01:55:59.89,01:56:01.96
fut séquestré par les brigands

01:56:02.61,01:56:06.00
Qui sait combien ils ont dû payer[br]pour le libérer

01:56:06.21,01:56:08.88
Ils se trouvaient déjà en difficulté...

01:56:09.09,01:56:11.56
sans argent comptant,[br]comme tout le monde ici...

01:56:12.25,01:56:16.21
Mais on leur rendit le garçon[br]quoiqu'en plusieurs versements

01:56:17.29,01:56:20.04
Plusieurs versements ?[br]Comment cela Prince ?

01:56:20.81,01:56:23.25
Oui, morceau par morceau

01:56:24.01,01:56:26.45
D'abord l'index de la main droite

01:56:26.81,01:56:29.17
Une semaine plus tard le pied gauche

01:56:29.89,01:56:30.48
Et enfin...

01:56:30.69,01:56:32.73
dans un beau panier de figues...

01:56:34.85,01:56:35.92
La tête...

01:56:37.21,01:56:39.60
Paolo, assez avec ces histoires

01:56:40.73,01:56:42.61
Moi je ne l'ai pas vu,[br]j'étais trop petit,

01:56:42.81,01:56:44.29
mon père me l'a raconté

01:56:45.73,01:56:48.56
Une police inepte, celle des Bourbons

01:56:51.01,01:56:53.84
Chez nous aussi on voyait[br]des faits pareils

01:56:54.21,01:56:56.57
Mon père était surintendant

01:56:57.25,01:57:00.64
Un emploi dangereux[br]à ce moment-là...

01:57:00.85,01:57:03.60
pour lui[br]autant que pour sa famille

01:57:03.97,01:57:07.12
Quand nos carabiniers arriveront[br]tout cela finira

01:57:07.49,01:57:10.13
En tout cas, contrairement[br]à une certaine propagande...

01:57:10.33,01:57:14.48
le respect envers l'Eglise[br]sera rétabli comme autrefois...

01:57:14.85,01:57:16.89
Un peu plus espérons-le...

01:57:17.25,01:57:20.32
Car il y a quelques années[br]le curé de Santa Ninfa...

01:57:20.53,01:57:22.49
a été assassiné pendant la messe

01:57:22.85,01:57:25.52
Quelle horreur ![br]Un coup de fusil en pleine église !

01:57:25.89,01:57:27.45
Non, vous n'y êtes pas du tout

01:57:27.81,01:57:31.44
Nous sommes trop bons catholiques[br]pour nous livrer à de tels sacrilèges

01:57:31.97,01:57:34.25
On avait mis du poison dans[br]le vin de messe

01:57:34.45,01:57:37.68
C'est plus discret[br]voire même plus liturgique

01:57:38.05,01:57:39.93
On n'en a jamais connu l'auteur

01:57:40.29,01:57:43.44
Le curé était un excellent homme[br]et n'avait pas d'ennemi

01:57:44.93,01:57:47.76
Très intéressant. Vraiment amusant

01:57:48.45,01:57:50.97
Je crois que vous pourriez[br]écrire des romans Prince

01:57:52.13,01:57:54.33
Oui, croyez-moi ce sont des histoires

01:57:54.69,01:57:56.33
Moi qui suis milanais...

01:57:56.53,01:57:58.60
la Sicile est un grand pays !

01:57:59.01,01:58:02.48
Après l'heureuse annexion,[br]je veux dire...

01:58:03.65,01:58:07.61
après "l'heureuse union" de la Sicile[br]au Royaume de Sardaigne...

01:58:08.29,01:58:10.49
le gouvernement de Turin

01:58:10.85,01:58:13.60
a l'intention de procéder à[br]la nomination d'illustres Siciliens

01:58:13.81,01:58:15.29
comme membres du Sénat

01:58:16.25,01:58:18.97
Votre nom a été choisi parmi[br]les premiers

01:58:19.21,01:58:22.33
Un nom illustre par son ancienneté,

01:58:22.53,01:58:25.68
par le prestige personnel[br]de celui qui le porte...

01:58:26.21,01:58:27.77
par ses mérites...

01:58:28.13,01:58:29.36
scientifiques...

01:58:29.73,01:58:33.85
par son attitude digne et libérale[br]dans les récents événements

01:58:34.69,01:58:36.73
Avant de clore la liste...

01:58:37.09,01:58:40.05
mes chefs ont cru de leur devoir[br]de vous en informer

01:58:40.41,01:58:43.61
et de vous demander si[br]vous agréez la proposition

01:58:44.13,01:58:47.12
Le gouvernement espère[br]que vous consentirez

01:58:48.61,01:58:51.92
C'est là l'objet de ma mission[br]qui m'a valu...

01:58:52.29,01:58:55.92
l'honneur et le plaisir de vous[br]connaître ainsi que votre famille

01:58:56.29,01:58:58.33
et ce magnifique palais

01:59:03.65,01:59:05.53
Expliquez-moi... Chevalley...

01:59:06.53,01:59:09.84
Etre Sénateur...[br]qu'est-ce que cela signifie ?

01:59:10.69,01:59:12.25
Qu'est-ce que c'est ?

01:59:13.09,01:59:15.45
Un titre honorifique,[br]une décoration ou quoi ?

01:59:15.85,01:59:19.97
Mais Prince ! Le Sénat est[br]la Chambre haute de notre Royaume

01:59:20.33,01:59:23.64
On y examine, on y débat...

01:59:24.01,01:59:26.84
on y approuve ou on y repousse

01:59:27.21,01:59:30.36
les lois que le Gouvernement[br]propose pour le progrès du pays

01:59:30.73,01:59:32.77
Quand vous serez Sénateur

01:59:33.21,01:59:36.25
votre voix sera celle[br]de votre beau pays

01:59:36.45,01:59:39.65
qui s'ouvre maintenant[br]au monde moderne

01:59:40.13,01:59:42.20
et qui a tant de plaies à guérir

01:59:42.73,01:59:45.40
tant de justes désirs à exaucer

01:59:47.37,01:59:48.60
Ecoutez-moi...

01:59:50.53,01:59:53.57
Je suis reconnaissant au Gouvernement[br]d'avoir songé à moi

01:59:54.65,01:59:56.93
S'il s'agissait d'un simple titre

01:59:57.49,02:00:01.28
à inscrire sur ma carte de visite[br]j'accepterais volontiers

02:00:02.93,02:00:05.76
Mais... je ne peux pas accepter

02:00:09.57,02:00:12.01
Je suis un représentant de[br]la vieille classe...

02:00:12.21,02:00:14.88
compromis avec l'ancien régime

02:00:15.25,02:00:18.56
et lié à celui-ci par des liens[br]de décence, sinon d'affection

02:00:19.73,02:00:21.93
Ma malheureuse génération

02:00:22.29,02:00:24.12
est à cheval entre deux mondes

02:00:24.33,02:00:26.48
et mal à l'aise[br]dans l'un et dans l'autre

02:00:26.69,02:00:29.44
En outre je n'ai aucune illusion

02:00:30.13,02:00:33.44
Que ferait le Sénat[br]d'un législateur sans expérience ?

02:00:33.81,02:00:35.77
D'un homme incapable[br]de se duper lui-même

02:00:35.97,02:00:38.88
condition essentielle[br]pour guider les autres ?

02:00:39.09,02:00:43.16
Non, en politique je ne bougerai pas[br]le petit doigt. On me mordrait

02:00:44.37,02:00:47.36
Prince je ne peux pas y croire

02:00:48.37,02:00:51.20
Sérieusement vous refusez[br]de faire votre possible

02:00:51.57,02:00:55.36
pour soulager le peuple[br]de la misère matérielle...

02:00:56.05,02:00:58.36
et morale dans laquelle[br]il se débat ?

02:01:00.37,02:01:03.04
Nous sommes vieux, très vieux

02:01:04.05,02:01:05.28
Depuis 25 siècles,

02:01:05.49,02:01:08.88
nous portons le poids[br]de civilisations hétéroclites

02:01:09.17,02:01:13.13
toutes venues du dehors,[br]pas une qui ait germé ici

02:01:13.49,02:01:16.16
Depuis 2500 ans[br]nous ne sommes qu'une colonie

02:01:16.53,02:01:18.89
Je ne le dis pas pour nous justifier

02:01:19.41,02:01:22.56
Mais nous sommes fatigués,[br]vidés, éteints

02:01:22.93,02:01:24.52
Tout ça est fini maintenant

02:01:25.49,02:01:27.85
La Sicile n'est plus[br]une terre de conquête

02:01:28.21,02:01:30.25
elle est libre dans un Etat libre

02:01:33.17,02:01:34.89
L'intention est bonne

02:01:35.57,02:01:37.29
mais elle arrive trop tard

02:02:01.81,02:02:04.96
Le sommeil mon cher Chevalley,[br]un long sommeil

02:02:05.33,02:02:07.37
voilà ce que les Siciliens désirent

02:02:07.89,02:02:11.04
Et ils haïront toujours[br]qui voudra les réveiller

02:02:11.73,02:02:14.72
même si on leur apporte[br]des dons merveilleux

02:02:15.57,02:02:18.24
Et soit dit entre nous je doute fort

02:02:18.61,02:02:21.92
que le nouveau royaume ait[br]dans son bagage des dons pour nous.

02:02:24.85,02:02:26.89
Chez nous, toute manifestation

02:02:27.41,02:02:29.77
est une aspiration à l'oubli

02:02:35.57,02:02:37.13
Notre sensualité

02:02:38.61,02:02:40.33
est un désir d'oubli

02:02:40.85,02:02:43.84
Nos coups de couteau[br]un désir de mort

02:02:45.01,02:02:46.41
Notre paresse

02:02:47.09,02:02:49.29
La douceur de nos sorbets

02:02:50.29,02:02:53.44
désir de voluptueuse immobilité,[br]c'est-à-dire

02:02:55.09,02:02:56.81
encore un désir de mort

02:03:08.85,02:03:11.21
Prince vous êtes sûr[br]de ne pas exagérer ?

02:03:12.21,02:03:14.73
A Turin j'ai connu des Siciliens

02:03:15.09,02:03:17.29
qui n'avaient pas du tout[br]l'air de dormir

02:03:18.29,02:03:20.65
Je me suis mal expliqué

02:03:21.81,02:03:24.33
Je ne devrais pas parler de Siciliens,[br]mais de Sicile

02:03:25.65,02:03:28.96
ce milieu,[br]la violence du paysage

02:03:29.65,02:03:32.64
la cruauté du climat,[br]la tension continue de toute chose

02:03:33.01,02:03:34.57
Mais on peut vaincre le climat

02:03:34.77,02:03:37.76
On peut modifier le paysage

02:03:38.29,02:03:40.96
On oublie les mauvais gouvernements

02:03:41.49,02:03:43.85
Je suis sûr que les Siciliens[br]voudront s'améliorer

02:03:44.21,02:03:48.65
Je ne nie pas que hors de l'île[br]les Siciliens ne puissent se réveiller

02:03:49.33,02:03:52.56
Mais ils doivent partir jeunes.[br]A 20 ans c'est déjà trop tard

02:03:52.77,02:03:54.57
La croûte s'est formée

02:03:54.93,02:03:58.08
Mais vous avez plutôt besoin[br]d'un homme qui sache allier

02:03:58.45,02:04:01.92
son intérêt particulier[br]à l'idéal public

02:04:05.17,02:04:08.32
Me permettez-vous un conseil[br]pour vos chefs ?

02:04:09.49,02:04:12.16
J'ai à vous proposer un nom[br]pour le Sénat

02:04:17.97,02:04:19.20
Celui de...

02:04:21.17,02:04:22.73
Calogero Sedara

02:04:23.25,02:04:25.77
Il a bien plus de mérites que moi

02:04:26.13,02:04:28.96
Sa famille m'a-t-on dit[br]est ancienne

02:04:29.97,02:04:31.37
ou le sera bientôt

02:04:31.73,02:04:35.36
Plus que ce que vous appelez prestige,[br]il a le pouvoir

02:04:36.37,02:04:38.89
Il a des intérêts pratiques

02:04:39.89,02:04:41.12
exceptionnels

02:04:41.65,02:04:44.80
Son activité a été très utile[br]pendant la crise de mai

02:04:45.65,02:04:47.21
Quant aux illusions...

02:04:52.53,02:04:54.41
il n'en a pas plus que moi

02:04:55.09,02:04:57.61
Mais il est assez fourbe[br]pour s'en créer

02:04:57.97,02:04:59.09
C'est l'homme qu'il vous faut

02:05:02.45,02:05:05.44
Oui, j'ai entendu parler de Sedara

02:05:07.17,02:05:10.08
Mais si les personnes honnêtes[br]comme vous se retirent...

02:05:10.45,02:05:14.08
les gens sans scrupules,[br]les Sedara, trouveront...

02:05:14.61,02:05:16.33
la voie libre

02:05:16.69,02:05:19.84
Et tout sera comme auparavant[br]pour des siècles encore

02:05:20.69,02:05:22.60
Ecoutez votre conscience... Prince...

02:05:22.81,02:05:25.61
et non vos orgueilleuses vérités

02:05:30.61,02:05:33.60
Je vous en prie,[br]cherchez à collaborer

02:05:37.81,02:05:39.85
Vous êtes un gentilhomme Chevalley...

02:05:41.01,02:05:43.68
et c'est pour moi un privilège[br]que de vous avoir connu

02:05:44.05,02:05:45.77
Vous avez raison sur tout

02:05:47.93,02:05:49.60
sauf quand vous dites

02:05:50.13,02:05:52.65
"Les Siciliens voudront s'améliorer"

02:05:53.01,02:05:56.32
Ils ne le voudront pas[br]parce qu'ils se croient parfaits

02:05:57.01,02:05:59.84
La vanité chez eux[br]est plus forte que la misère

02:06:03.29,02:06:04.49
Mais asseyez-vous

02:06:09.69,02:06:12.16
Un peu avant que Garibaldi[br]n'entrât à Palerme

02:06:12.37,02:06:15.84
des officiers anglais[br]des vaisseaux en rade...

02:06:16.37,02:06:19.52
me demandèrent de pouvoir[br]monter à ma terrasse

02:06:20.05,02:06:22.72
pour admirer les montagnes[br]autour de la ville

02:06:24.37,02:06:26.89
Ils furent enthousiastes du panorama

02:06:27.57,02:06:28.97
Mais ils m'avouèrent

02:06:29.17,02:06:33.93
leur stupeur pour la saleté[br]des routes d'accès

02:06:34.77,02:06:37.60
Je ne leur expliquai pas[br]comme à vous

02:06:37.97,02:06:40.17
qu'une chose était[br]la conséquence de l'autre

02:06:44.05,02:06:45.45
Ils me demandèrent ,

02:06:46.45,02:06:48.97
"Mais ces Garibaldiens,[br]que viennent-ils faire en Sicile ?

02:06:49.49,02:06:51.85
Je répondis[br]"Nous enseigner la civilité"

02:06:52.21,02:06:55.52
"Mais ils n'y réussiront pas[br]car nous sommes des dieux"

02:06:56.69,02:06:59.84
Ils ont ri.[br]Mais je doute qu'ils aient compris

02:07:06.77,02:07:08.00
Il est tard

02:07:08.37,02:07:09.28
C'est l'heure du dîner

02:07:09.97,02:07:11.69
et nous devons nous changer

02:07:12.05,02:07:15.04
Vous pourrez partir demain à l'aube[br]si vous le désirez

02:08:50.05,02:08:54.01
Prince vous ne le croyez pas[br]mais cet état de choses ne durera pas

02:08:54.53,02:08:57.57
Notre administration moderne,[br]efficiente

02:08:57.77,02:08:59.00
changera tout cela

02:08:59.21,02:09:02.73
Ça ne devrait pas pouvoir durer[br]mais ça durera toujours

02:09:02.93,02:09:05.68
Le toujours humain,[br]un ou deux siècles

02:09:06.05,02:09:09.20
Après, tout sera peut-être diffèrent[br]mais pire

02:09:11.61,02:09:14.17
Au revoir.[br]Je vous remercie de tout Prince

02:09:20.93,02:09:23.29
Nous fûmes les guépards, les lions.

02:09:24.61,02:09:27.60
Les chacals et les hyènes[br]nous remplaceront

02:09:28.13,02:09:31.92
Et tous, guépards, lions,[br]chacals, moutons...

02:09:33.09,02:09:35.76
nous nous croirons toujours[br]le sel de la terre

02:09:36.13,02:09:38.80
Je n'ai pas bien compris.[br]Comment avez-vous dit ?

02:09:39.97,02:09:41.20
Rien

02:09:41.73,02:09:43.93
Excusez-moi, je n'ai pas entendu

02:11:04.49,02:11:06.08
- Bonsoir[br]- Bonsoir Margherita

02:11:09.49,02:11:10.97
Bonsoir ma chère

02:11:11.53,02:11:12.85
Quelle joie !

02:11:13.13,02:11:15.65
Vous êtes arrivés tôt[br]mais soyez tranquilles

02:11:16.01,02:11:18.68
on n'a pas encore vu vos invités

02:11:22.57,02:11:23.80
Fabrizio comment ça va ?

02:11:24.49,02:11:27.01
Tancredi est déjà ici[br]et nous attendons Pallavicino...

02:11:27.37,02:11:29.73
le vainqueur d'Aspromonte

02:11:39.53,02:11:42.05
Je te remercie ma tante.[br]Je t'ai demandé un sacrifice...

02:11:42.41,02:11:44.45
mais les inviter était indispensable

02:11:44.81,02:11:47.80
Cette soirée sera [br]le vrai début en société pour Angelica 

02:11:48.17,02:11:49.73
Et l'habit de don Calogero ?

02:11:50.09,02:11:54.05
Ce n'est pas celui de Donnafugata.[br]Je l'ai laissé chez le meilleur tailleur

02:11:54.41,02:11:56.13
C'est don Calogero qui manque de chic

02:12:16.77,02:12:18.89
- Bonsoir Baronne[br]- Bonsoir Lieutenant

02:12:19.09,02:12:20.49
Mes hommages Baronne

02:12:20.69,02:12:21.84
Bonsoir

02:12:26.29,02:12:27.41
Comment ça va ?

02:12:28.77,02:12:31.13
Comment vas-tu ? Très bien !

02:12:32.01,02:12:35.00
Je te trouve très bien chérie. Merci

02:12:39.41,02:12:40.56
On peut aller danser ?

02:12:40.77,02:12:43.05
Bien sûr. Arrange-toi un peu

02:12:43.25,02:12:45.40
Tu es très belle, une vraie fleur !

02:12:45.81,02:12:46.93
Allez-y !

02:12:47.49,02:12:48.37
Gracieuses, hein ?

02:12:48.57,02:12:51.04
Délicieuses, vraiment délicieuses

02:12:51.25,02:12:52.84
Je n'aime pas venir à ces bals...

02:12:53.05,02:12:55.25
mais il le faut pour les enfants

02:13:31.37,02:13:33.73
Colonel,[br]trés honoré de vous voir

02:13:34.09,02:13:35.16
L'honneur est pour moi

02:13:35.53,02:13:39.81
Margherita, j'ai l'honneur[br]de te présenter le colonel Pallavicino

02:13:41.61,02:13:43.44
Je suis fière, heureuse...

02:13:43.65,02:13:47.41
de recevoir dans ma maison[br]le vainqueur d'Aspromonte

02:13:47.61,02:13:51.00
Princesse, c'est moi qui suis fier[br]d'une telle occasion

02:13:51.37,02:13:55.81
J'espère que vous et vos officiers[br]passerez une soirée agréable

02:14:03.05,02:14:04.61
Colonel je vous en prie

02:14:18.09,02:14:20.73
La princesse de Lampedusa

02:14:23.05,02:14:25.04
La comtesse Sutera

02:14:25.25,02:14:25.84
Très honoré

02:14:26.05,02:14:28.20
- Très heureuse de vous connaître[br]- Merci

02:14:33.61,02:14:36.33
La princesse Corbera di Salina

02:14:36.53,02:14:37.41
Bonsoir

02:14:38.97,02:14:40.93
Très heureux, Princesse

02:15:12.41,02:15:14.53
Je vais voir si Angelica est arrivée

02:15:14.89,02:15:16.77
C'est juste, va

02:15:17.45,02:15:18.52
Excuse-moi

02:15:41.77,02:15:44.44
Colonel, dites-nous,[br]c'est vrai ce qu'on raconte ?

02:15:46.77,02:15:49.57
Je pleurais comtesse,[br]je pleurais comme un enfant

02:15:49.93,02:15:50.84
Quelle émotion !

02:15:51.21,02:15:53.09
Mais lui comment était-il ?

02:15:53.61,02:15:56.92
Lui... il était beau et calme[br]comme un archange

02:15:57.29,02:15:58.52
Magnifique !

02:15:58.89,02:16:02.33
Vous êtes un vrai héros.[br]N'est-ce pas un homme extraordinaire ?

02:16:09.29,02:16:11.33
Le colonel est en train de les rassurer

02:16:11.69,02:16:14.52
mais après les coups de fusil de[br]ses bersaglieri ce n'est plus nécessaire

02:16:14.89,02:16:17.88
Vraiment opportuns ces coups de fusil !

02:16:26.93,02:16:28.28
Tu es en retard

02:16:30.77,02:16:34.21
Tu es très belle.[br]Allons, viens saluer la princesse

02:16:46.73,02:16:47.80
Princesse...

02:16:49.61,02:16:52.60
permettez-moi de vous présenter[br]ma fiancée Angelica Sedara

02:16:54.73,02:16:57.88
Laisse-toi regarder... Oui en vérité

02:16:58.41,02:17:00.93
...tu es plus belle qu'on le dit

02:17:01.93,02:17:02.84
Très belle

02:17:04.01,02:17:06.68
Ça ?[br]C'est la croix de Chevalier d'Italie

02:17:07.21,02:17:09.88
Oui mais ici elle ne suffit pas

02:17:11.01,02:17:14.21
Je n'ai jamais douté de ton bon goût

02:17:14.89,02:17:18.52
Mon beau-père,[br]le Chevalier don Calogero Sedara

02:17:24.01,02:17:25.89
C'est très beau ici Princesse

02:17:54.09,02:17:55.81
Calmez-vous mes enfants

02:17:57.93,02:18:00.76
Tu me présentes à ta fiancée ?

02:18:02.17,02:18:05.24
Je te présente[br]mon ami Gioacchino Lanza...

02:18:05.97,02:18:07.01
et celui-ci c'est Fulco

02:18:07.21,02:18:09.09
Tancredi ne protestera pas

02:18:09.45,02:18:12.44
si vous m'inscrivez dans[br]votre carnet pour la prochaine valse

02:18:12.81,02:18:16.28
Ça va mes amis, ne soyez pas pressés,[br]on a le temps

02:18:18.73,02:18:19.96
Tu es un égoïste

02:18:20.33,02:18:22.69
Désolé, mais ce n'est pas moi[br]qui décide

02:18:23.05,02:18:25.41
C'est la dame qui choisit[br]ses cavaliers

02:18:26.09,02:18:28.13
C'est une valse, elle est à moi

02:18:29.25,02:18:31.32
Mon oncle, tu le salueras après

02:18:33.93,02:18:35.33
Que veux-tu faire ?

02:19:30.89,02:19:32.77
Vous êtes très belle comme toujours

02:19:33.29,02:19:34.69
C'est la véritè

02:20:17.45,02:20:18.85
Tu t'ennuies ?

02:20:19.85,02:20:21.41
Je me disais

02:20:22.05,02:20:25.73
que trop de mariages entre cousins[br]ne favorisent pas la race

02:20:27.69,02:20:31.05
On dirait des guenons prêtes[br]à grimper sur les lustres

02:20:32.01,02:20:34.53
et à s'y balancer[br]suspendues par la queue

02:20:34.89,02:20:36.29
et montrant leurs derrières

02:21:40.17,02:21:41.89
Eleonora Giardinelli...

02:21:43.21,02:21:46.04
un cygne blanc dans[br]un étang de grenouilles !

02:21:46.73,02:21:50.36
Compliments pour les fiançailles[br]de ton neveu. Une beauté, la fiancée

02:21:50.73,02:21:52.61
L'exemple sera bientôt imité

02:21:52.97,02:21:54.53
Tu disais ?

02:21:54.89,02:21:57.72
Je disais que...[br]Il fait trop chaud ici

02:21:58.73,02:22:00.13
Oui, il fait chaud

02:22:00.97,02:22:02.85
Je n'aurais pas dû venir

02:22:05.13,02:22:06.53
Je suis un peu fatigué

02:22:07.69,02:22:10.36
Mais j'y suis[br]et il faut que j'y reste

02:22:11.37,02:22:13.73
Ce serait impoli de s'en aller

02:22:14.09,02:22:15.81
Tu as raison Fabrizio

02:23:43.45,02:23:45.04
- Bonsoir[br]- Bonsoir ma chère

02:23:45.45,02:23:48.01
Tu sais que j'ai quatre[br]danses de réservées ?

02:23:56.09,02:23:59.08
Princesse je serais très heureux[br]si vous m'accordiez...

02:23:59.45,02:24:01.01
Non, ne me refusez pas.[br]Je vous en prie...

02:24:01.37,02:24:04.20
Colonel, il y a des annèes[br]que je ne danse pas

02:24:05.65,02:24:07.56
Et avec tant de jolies femmes ici !

02:24:09.53,02:24:10.93
Et à mon âge !

02:24:40.89,02:24:43.25
C'est beau prince, vraiment beau

02:24:43.77,02:24:45.81
On n'en fait plus[br]des maisons comme ça

02:24:46.17,02:24:48.05
avec le prix actuel de l'or

02:24:49.85,02:24:52.37
Oui don Calogero, c'est beau

02:24:52.73,02:24:54.13
vraiment beau...

02:24:55.29,02:24:58.28
Mais rien ne vaut[br]nos deux jeunes gens

02:28:25.37,02:28:27.25
Angelica voulait te saluer

02:28:27.61,02:28:29.33
Pourquoi tout seul ici ?

02:28:30.17,02:28:32.53
Tu courtises la mort ?

02:28:38.65,02:28:40.37
Tu es vraiment splendide

02:28:46.81,02:28:50.09
Il est étrange que don Diego[br]conserve ce tableau mélancolique

02:28:52.41,02:28:56.17
Si don Diego entre ici une fois l'an[br]c'est un miracle

02:28:56.73,02:28:58.13
Tu as raison

02:29:00.73,02:29:03.25
Je me demande si ma mort[br]sera comme celle-ci

02:29:04.57,02:29:06.61
Le linge sera moins impeccable

02:29:07.29,02:29:10.44
Les draps des agonisants[br]sont toujours si sales

02:29:11.41,02:29:16.04
Et il faut espérer que Concetta[br]et les autres s'habilleront mieux

02:29:19.77,02:29:21.97
Mais dans l'ensemble ce sera ainsi

02:29:25.85,02:29:27.25
Mon oncle, que dis-tu ?

02:29:28.09,02:29:29.49
A quoi tu songes ?

02:29:31.61,02:29:33.33
Je pense souvent à la mort

02:29:33.69,02:29:35.73
Cette idée ne m'épouvante pas

02:29:36.89,02:29:39.09
Vous les jeunes,[br]vous ne pouvez pas comprendre

02:29:39.61,02:29:41.65
Pour vous la mort n'existe pas...

02:29:42.97,02:29:44.85
elle est à l'usage d'autrui

02:30:00.09,02:30:02.24
Il faut réparer notre tombeau[br]aux Capucins

02:30:12.73,02:30:16.20
Tancredi,[br]veux-tu me donner ton mouchoir ?

02:30:29.89,02:30:34.28
Prince nous vous savions ici[br]et nous sommes venus nous reposer

02:30:35.49,02:30:37.32
et aussi vous demander quelque chose

02:30:39.93,02:30:41.89
J'espère[br]que vous ne me le refuserez pas

02:30:49.21,02:30:52.52
Je vous demande de danser avec moi[br]la prochaine mazurka

02:30:52.89,02:30:56.68
Ne soyez pas méchant. On sait[br]que vous êtes un merveilleux danseur

02:30:58.01,02:31:00.53
Je n'ai jamais eu une proposition[br]aussi séduisante

02:31:00.89,02:31:03.01
Pour cette raison je dois refuser

02:31:03.21,02:31:05.81
Je vous en prie Prince

02:31:34.33,02:31:36.37
Merci mon enfant, tu me rajeunis

02:31:37.05,02:31:39.09
J'accepte. Mais pas la mazurka

02:31:39.61,02:31:43.40
Je me sentirais trop jeune.[br]Accorde-moi la première valse

02:31:51.41,02:31:53.64
Tu vois comme l'oncle est gentil ?

02:31:54.01,02:31:56.21
Il ne fait pas de caprice comme toi

02:31:58.81,02:32:01.64
Lui ne voulait pas que[br]je vous demande cela

02:32:02.01,02:32:03.24
Il est jaloux

02:32:08.73,02:32:12.52
Avec un oncle beau et séduisant[br]être jaloux est normal

02:32:14.17,02:32:17.00
Pour une fois je ferai une exception

02:32:19.85,02:32:20.84
Allons ?

02:32:53.13,02:32:54.20
Une valse

02:32:55.21,02:32:58.04
Comme si je m'étais mise d'accord[br]avec l'orchestre

02:33:00.17,02:33:01.57
C'est une valse...

02:33:02.25,02:33:03.76
déjà repenti ?

02:33:03.97,02:33:06.20
Non, je te prie de m'excuser

02:33:37.81,02:33:39.96
Ils sont tous si gentils avec moi

02:33:40.21,02:33:42.44
Et moi je suis si heureuse

02:33:42.65,02:33:45.01
Tancredi est un amour[br]et vous aussi

02:33:45.29,02:33:47.33
Heureusement[br]qu'il ne peut vous entendre

02:33:47.69,02:33:50.16
Je sais que je vous dois tout

02:33:50.37,02:33:51.77
Tancredi compris

02:33:51.97,02:33:53.88
Si vous n'aviez pas voulu[br]il n'aurait pas...

02:33:54.25,02:33:55.57
Il t'aurait épousée

02:33:55.77,02:33:57.25
quand même

02:33:57.77,02:33:59.81
Tu dois tout à toi seule

02:34:00.33,02:34:01.73
Ce n'est pas vrai

02:34:02.09,02:34:03.81
Oui c'est vrai

02:34:07.37,02:34:10.52
Aucun Tancredi[br]ne résisterait à ta beauté

02:34:36.01,02:34:38.65
On disait que vous étiez[br]un bon danseur...

02:34:38.85,02:34:40.97
Je regrette de t'avoir déçue

02:34:41.17,02:34:44.93
Vous êtes plus qu'un bon danseur,[br]un danseur délicieux

02:34:45.29,02:34:46.85
vraiment délicieux

02:34:50.89,02:34:52.09
Oui, c'est mon père

02:34:52.29,02:34:53.52
La prochaine

02:34:53.73,02:34:54.61
Une mazurka alors

02:34:55.37,02:34:57.41
Tout le monde nous regarde

02:35:02.17,02:35:04.61
La cavalière de votre père[br]est splendide !

02:35:05.17,02:35:06.89
Elle est très belle

02:35:36.49,02:35:38.53
Si les applaudissements[br]n'ont pas éclaté

02:35:38.73,02:35:41.88
c'est parce qu'un lion[br]de ton espèce les intimide

02:35:42.25,02:35:44.29
Mais tu méritais une ovation

02:35:44.81,02:35:47.01
Venez souper à notre table

02:35:47.37,02:35:51.49
Non Angelica, mes souvenirs[br]de jeunesse sont encore très vifs

02:35:52.01,02:35:54.84
et je sais combien un vieil oncle[br]est fastidieux

02:35:55.69,02:35:57.73
Les amoureux veulent être seuls

02:35:58.09,02:35:59.97
Et puis j'ai peu d'appétit

02:36:00.81,02:36:03.48
Va avec lui. Ne songez pas à moi

02:36:10.41,02:36:11.64
Merci mon oncle

02:36:16.89,02:36:18.72
Tu es encore un grand danseur !

02:36:18.93,02:36:20.60
Tu as été extraordinaire !

02:37:03.05,02:37:05.28
Comment ça va Fabrizio ?[br]Tu vas bien ?

02:37:09.13,02:37:11.41
Que fais-tu Fabrizio ?[br]Tu ne prends rien ?

02:37:11.61,02:37:13.09
Tu es indécis

02:37:13.29,02:37:17.25
Le choix est trop grand.[br]Donna Margherita fait bien les choses

02:37:18.41,02:37:21.24
mais il faut[br]d'autres estomacs que le mien

02:37:24.81,02:37:26.48
Quels merveilleux candélabres

02:37:26.69,02:37:28.76
Le grand-père de don Diego

02:37:28.97,02:37:32.60
les a rapportés de Madrid[br]au terme de son ambassade

02:37:33.81,02:37:36.93
Qui sait combien d'hectares[br]ils peuvent valoir

02:38:41.61,02:38:44.13
La plus forte émotion de ma vie !

02:38:45.13,02:38:47.01
Quel formidable raseur !

02:38:50.53,02:38:53.57
Prince nous faites-vous l'honneur[br]de vous asseoir à notre table ?

02:39:05.53,02:39:08.36
Et maintenant la gauche[br]veut nous crucifier...

02:39:08.57,02:39:12.28
parce que j'ai ordonné à mes hommes[br]de faire feu sur le Général

02:39:13.45,02:39:15.01
Mais dites-moi Prince

02:39:15.37,02:39:18.68
que pouvais-je faire avec les ordres[br]écrits que je portais ?

02:39:19.53,02:39:23.00
Et puis je dois avouer que[br]quand à Aspromonte

02:39:23.37,02:39:26.36
je me suis trouvé parmi[br]des centaines de débraillés

02:39:26.73,02:39:28.77
avec des visages de fanatiques

02:39:28.97,02:39:32.60
d'autres avec des gueules[br]de rebelles professionnels

02:39:36.01,02:39:38.05
J'étais heureux que mes ordres

02:39:38.41,02:39:41.24
fussent d'accord avec mon idée

02:39:47.21,02:39:49.12
Et puis je vous le dis en confidence

02:39:49.33,02:39:53.37
ma brève fusillade a profité[br]à lui, à Garibaldi

02:39:54.73,02:39:58.52
Je l'ai libéré de cette bande[br]qui s'était cramponnée à lui

02:39:58.89,02:40:01.56
pour qui sait quelles fins,[br]peut-être...

02:40:02.33,02:40:03.92
inspirée par les Tuileries

02:40:04.13,02:40:05.33
et le Palais Farnèse

02:40:05.53,02:40:06.60
C'est vrai

02:40:06.81,02:40:10.20
Des individus différents[br]de ceux débarqués à Marsala

02:40:10.53,02:40:14.21
Des gens ceux-là qui croyaient[br]vraiment faire l'Italie

02:40:14.41,02:40:16.53
par une série de coups[br]comme celui de 48

02:40:17.45,02:40:19.97
Lui... je veux dire le Général...

02:40:20.49,02:40:21.72
il sait cela

02:40:22.09,02:40:25.72
Car au moment de[br]mon fameux agenouillement

02:40:26.09,02:40:27.49
...il m'a serré la main

02:40:28.65,02:40:30.53
Et savez-vous ce qu'il m'a dit ?

02:40:31.69,02:40:33.41
"Merci colonel"

02:40:35.13,02:40:38.84
"Merci de quoi ? lui dis-je.[br]D'avoir fait de vous un boiteux ?"

02:40:40.01,02:40:44.48
Non, de lui avoir fait comprendre[br]les fanfaronnades, les lâchetés...

02:40:44.69,02:40:47.97
et pis encore[br]de ses partisans équivoques

02:40:48.61,02:40:50.25
Mais excusez-moi colonel...

02:40:50.73,02:40:53.69
avec toutes ces révérences,[br]ces coups de chapeau...

02:40:53.89,02:40:56.28
vous ne pensez pas avoir exagéré ?

02:41:02.13,02:41:03.64
Sincèrement, non

02:41:04.29,02:41:07.81
Il fallait le voir[br]ce pauvre grand homme

02:41:08.57,02:41:10.69
étendu sous un châtaignier

02:41:11.21,02:41:12.80
souffrant dans son corps

02:41:13.01,02:41:15.97
et encore plus dans son esprit

02:41:19.69,02:41:22.21
En débarquant en Sicile, il a dit

02:41:22.89,02:41:24.93
"Nous allons vers l'inconnu"

02:41:26.97,02:41:29.25
Il était difficile[br]de résister à l'émotion

02:41:30.73,02:41:32.45
Et puis pourquoi résister ?

02:41:33.77,02:41:36.44
Moi je ne baise la main qu'aux dames

02:41:39.05,02:41:42.84
Alors, aussi j'ai baisé la main[br]à la sauvagerie du royaume

02:41:43.85,02:41:45.73
comme à une dame

02:41:45.93,02:41:49.08
à laquelle nous rendons hommage[br]nous les soldats

02:41:53.77,02:41:55.97
Excusez-moi.[br]Don Diego pardon

02:42:38.37,02:42:40.73
Trois bals en une semaine[br]c'est trop

02:42:41.89,02:42:43.61
Je n'en vois pas la fin !

02:42:43.97,02:42:46.17
Quel amusement y trouvent-ils ?

02:42:46.53,02:42:48.09
Une épingle à cheveux ?

02:42:50.21,02:42:51.44
Quel ennui !

02:42:57.73,02:43:01.04
Avec toutes ces invitations,[br]il nous faut rester en ville

02:43:02.05,02:43:04.72
et moi je ne vois pas l'heure[br]de retourner à la villa

02:43:05.09,02:43:07.13
à notre vie tranquille

02:43:08.25,02:43:11.96
Quoi ? Moi je voudrais[br]que ce bal ne finisse jamais

02:43:12.17,02:43:15.77
C'est si beau ! Qui sait[br]comment sera celui des Trabia ?

02:43:16.25,02:43:19.29
J'ai commandé une robe vert clair

02:43:21.57,02:43:22.64
Et toi ?

02:43:24.85,02:43:26.33
Je suis heureuse

02:43:26.85,02:43:28.57
Tancredi est si gentil

02:43:29.09,02:43:31.13
Vous êtes tous si gentils avec moi

02:43:31.97,02:43:33.69
Je voudrais te voir plus gaie

02:43:33.89,02:43:37.85
Que veux-tu ?[br]Tous ces gens ne m'amusent pas

02:43:39.33,02:43:40.89
et la danse non plus

02:43:41.41,02:43:43.45
D'ailleurs je ne danse pas bien

02:43:45.57,02:43:47.29
Ça dépend du danseur...

02:43:47.81,02:43:49.69
cherche-toi un cavalier

02:43:50.69,02:43:52.09
Cela ne m'intéresse pas

02:43:52.93,02:43:56.72
Combien de jeunes gens[br]seraient heureux de te faire la cour

02:43:57.41,02:43:58.81
Tu les décourages

02:44:01.57,02:44:03.45
Comme ce pauvre Cavriaghi

02:44:04.29,02:44:05.69
Tu t'en souviens ?

02:44:06.69,02:44:08.41
Comment l'as-tu traité ?

02:44:12.29,02:44:15.44
Finalement ! Je te croyais perdue

02:44:15.81,02:44:17.85
On s'est mis un peu en ordre.

02:44:18.05,02:44:20.44
Toi plutôt... tu as disparu

02:44:20.65,02:44:23.40
Je suis allé écouter[br]le colonel Pallavicino

02:44:23.61,02:44:26.81
Ce n'est pas un génie[br]mais il dit des choses sensées

02:44:27.17,02:44:30.96
Le nouveau Royaume a besoin[br]d'ordre, de légalité, de lois

02:44:32.13,02:44:33.69
Il doit étouffer...

02:44:33.89,02:44:37.36
l'anarchie.[br]Plus d'aventures, plus de désordres

02:44:37.77,02:44:40.73
même s'il faut employer[br]des moyens douloureux

02:44:42.29,02:44:45.84
comme pour ces quatre exaltés[br]qui ont quitté l'armée pour Garibaldi

02:44:46.97,02:44:48.56
Tu crois qu'on les fusillera ?

02:44:48.93,02:44:51.29
Ce matin même à l'aube

02:44:51.97,02:44:54.33
Et c'estjuste, ce sont des déserteurs

02:45:11.77,02:45:13.84
Autrefois tu ne parlais pas comme ça

02:45:20.65,02:45:22.00
Tu te trompes

02:45:22.89,02:45:24.40
J'ai toujours parlé ainsi

02:45:25.41,02:45:28.24
Ce sont des choses[br]que tu ne peux pas comprendre

02:45:33.73,02:45:34.80
Attends...

02:45:36.45,02:45:37.85
Laisse-moi

02:45:40.61,02:45:42.65
Je comprends très bien au contraire

02:45:43.33,02:45:47.29
J'ai dit qu'autrefois[br]tu ne parlais pas ainsi. Ça me suffit

02:45:53.85,02:45:55.00
Laisse-moi !

02:46:06.21,02:46:07.61
Elle est charmante...

02:46:08.69,02:46:10.33
Surtout quand elle se fâche

02:46:11.81,02:46:12.88
Bravo !

02:46:14.25,02:46:17.69
Pauvre Concetta ! La vérité[br]c'est qu'elle est encore éprise de toi

02:46:20.69,02:46:23.44
Et toi ?[br]Tu es encore amoureuse de moi ?

02:50:16.21,02:50:18.01
Vous avez vu le prince Salina ?

02:50:19.65,02:50:21.53
Tu as vu le prince Salina ?

02:50:53.89,02:50:55.45
Rajustez vos habits

02:50:59.25,02:51:01.53
Un café ![br]S'il vous plaît, un café chaud

02:51:03.97,02:51:05.20
Du sucre ?

02:51:26.33,02:51:27.48
Bonne nuit

02:51:28.41,02:51:30.85
Margherita quelle fête magnifique !

02:51:31.05,02:51:32.53
Au revoir Margherita

02:51:35.29,02:51:37.01
- Bonne nuit ma chère[br]- Bonne nuit

02:51:38.45,02:51:39.65
Reposez-vous bien

02:52:31.17,02:52:32.40
Princesse...

02:52:33.57,02:52:35.88
merci pour cette inoubliable soirée

02:52:36.09,02:52:38.48
Vous partez déjà ?

02:52:38.85,02:52:40.84
Nous rentrons à la caserne...

02:52:41.05,02:52:43.44
suivant la tradition des militaires

02:52:43.65,02:52:45.53
Le devoir nous l'impose

02:52:45.89,02:52:48.49
D'ailleurs les tâches de cette nuit

02:52:48.69,02:52:50.49
ne sont pas achevées

02:52:59.81,02:53:02.96
Mettez de l'ordre[br]et éteignez les bougies

02:53:11.05,02:53:14.33
Merci infiniment. Merci pour la belle,[br]la splendide soirée

02:53:15.73,02:53:18.48
Je regrette que vous me quittiez si tôt

02:53:30.53,02:53:32.81
Toi aussi tu veux déjà t'en aller ?

02:53:49.97,02:53:52.72
Je t'ai trouvé ![br]Tante te cherche partout

02:53:53.77,02:53:55.60
On t'attend pour partir

02:53:56.73,02:53:58.88
Veux-tu me rendre un service ?

02:53:59.09,02:54:00.89
J'ai déjà salué tout le monde

02:54:01.25,02:54:04.72
Appelle la voiture pour ta tante.[br]Moi, je rentre à pied

02:54:05.09,02:54:06.49
A cette heure-ci ?

02:54:07.01,02:54:08.57
J'ai besoin d'air

02:54:09.97,02:54:10.93
Mon oncle...

02:54:12.13,02:54:13.41
Tu ne vas pas bien ?

02:54:13.61,02:54:15.76
J'ai un peu mal à la tête

02:54:16.61,02:54:18.20
Tout a bien marché ce soir[br]tu ne trouves pas ?

02:54:18.41,02:54:22.37
Merveilleusement, et merci.[br]J'aurai bientôt une bonne nouvelle

02:54:22.57,02:54:25.17
Il paraît[br]qu'aux prochaines élections

02:54:25.37,02:54:26.77
Tu seras candidat

02:54:26.97,02:54:28.25
Tu le savais ?

02:54:29.97,02:54:31.45
Excusez-moi, un instant

02:54:37.33,02:54:39.37
- Adieu Tancredi[br]- Tu es toujours la plus belle

02:54:39.57,02:54:41.37
Au revoir...[br]Content de t'avoir revue

02:54:41.57,02:54:43.61
Salue Nico de ma part,[br]n'oublie pas !

02:55:33.41,02:55:36.08
Etoile, étoile fidèle

02:55:37.21,02:55:40.76
quand me donneras-tu[br]un rendez-vous moins éphémère

02:55:40.97,02:55:43.04
loin de tout

02:55:43.25,02:55:46.16
dans ta région d'éternelle certitude ?

02:56:02.21,02:56:04.09
Une belle armée !

02:56:04.93,02:56:06.33
Elle fait les choses sérieusement

02:56:11.73,02:56:13.08
C'est ce qu'il fallait...

02:56:16.53,02:56:18.01
pour la Sicile

02:56:19.21,02:56:22.49
Maintenant[br]nous pouvons être tranquilles

