{000524}{000611}Il dort bien|parce qu'il est aimé.
{000698}{000785}Viens, mon frère.|Il est tard.
{000855}{000957}Je ferai de Rome|une merveille éternelle.
{001029}{001121}C'est ce que Gracchus et ses amis|ne comprennent pas.
{001151}{001249}Tous mes désirs font éclater|ma tête en morceaux.
{001494}{001540}Bois ce fortifiant.
{001830}{001923}Je pense que le moment propice|est pour bientôt.
{001926}{001990}Je pourrais annoncer|la dissolution du sénat...
{001993}{002049}à la célébration|en l'honneur de notre père.
{002053}{002109}Tu crois que je devrais|faire cela ?
{002148}{002204}Le peuple est-il prêt ?
{002256}{002315}Je crois que tu as besoin|de te reposer, à présent.
{002506}{002563}Peux-tu rester avec moi ?
{002566}{002625}Tu as encore peur du noir,|mon frère ?
{002846}{002890}Encore...
{002939}{002981}toujours.
{003026}{003115}- Reste avec moi, ce soir.|- Tu sais que je ne peux pas.
{003247}{003291}Alors, embrasse-moi.
{003559}{003601}Dors, mon frère.
{004170}{004214}Allez !
{004280}{004324}Prends-moi !
{004468}{004539}D'accord, ça suffît.
{005206}{005299}L'empereur veut des combats et je ne|sacrifierai pas mes meilleurs hommes.
{005301}{005411}La foule veut des batailles,|l'empereur lui donne des batailles.
{005415}{005522}- ça donne la bataille de Carthage.|- Le massacre de Carthage.
{005583}{005680}Pourquoi ne cherches-tu pas les|mendiants et les voleurs à la prison ?
{005683}{005731}On a déjà fait ça.
{005735}{005833}Si tu veux lâcher les meilleurs|gladiateurs de l'empire...
{005835}{005906}je veux que le tarif|soit doublé.
{005910}{006020}Tu auras le tarif du contrat,|ou ton contrat sera annulé.
{006023}{006066}ça ne te plaît pas ?
{006069}{006171}Tu peux toujours repartir ramper|dans le trou d'où tu viens.
{006283}{006334}Cassius, je t'en prie !|Cassius !
{007233}{007320}Gladiateur, es-tu celui|qu'on nomme l'Espagnol ?
{007322}{007360}Oui.
{007393}{007473}On m'a dit que|tu étais un géant.
{007475}{007539}Que tu pouvais écraser le crâne|d'un homme d'une seule main.
{007542}{007609}Le crâne d'un homme ? Non.
{007643}{007696}Celui d'un garçon.
{007770}{007859}- L'Espagne a de bon chevaux ?|- Parmi les meilleurs.
{007890}{007949}Voici Argento...
{007952}{008009}et voici Scarto.
{008013}{008069}Ce sont mes chevaux.
{008105}{008166}On me les a pris.
{008169}{008279}Je t'aime bien, l'Espagnol.|Je t'applaudirai.
{008283}{008393}- Tu peux regarder les jeux ?|- Mon oncle dit que ça me rend fort.
{008395}{008493}- Et que dit ton père ?|- Mon père est mort.
{008543}{008604}Maître Lucius,|il faut y aller.
{008643}{008680}Je dois y aller.
{008683}{008730}Tu t'appelles Lucius ?
{008800}{008881}Lucius Verus, d'après mon père.
{009796}{009847}Plus bas !
{010003}{010054}Claudius !
{010058}{010114}- Oui !|- Il faut plus de boucliers !
{010738}{010794}Quand l'empereur entrera...
{010798}{010880}brandissez vos armes,|saluez-le...
{010883}{010939}et parlez ensemble.
{010973}{011010}Faites face à l'empereur...
{011014}{011104}et ne lui tournez pas le dos.
{011108}{011208}Allez-y, et mourez|dans l'honneur.
{012844}{012905}Vive le tout-puissant César !
{012909}{013040}César ! César !|César ! César !
{013221}{013301}Nous qui allons mourir,|nous vous saluons !
{013380}{013429}Aujourd'hui...
{013431}{013536}nous évoquons|la sainte antiquité...
{013540}{013596}pour recréer devant vous...
{013600}{013715}la deuxième chute de|la toute puissante Carthage !
{013827}{013979}L'invincible armée...
{013983}{014083}d'Hannibal le barbare...
{014085}{014154}était sur la plaine|aride de Zama.
{014185}{014278}De féroces mercenaires|et des guerriers...
{014280}{014360}venus de toutes les nations|les plus rustres...
{014363}{014453}entrainés|à la cruauté...
{014455}{014516}la destruction...
{014520}{014571}et la conquête.
{014574}{014632}Votre empereur...
{014636}{014695}a le plaisir de vous montrer...
{014698}{014780}la horde barbare !
{015045}{015104}L'un d'entre vous a déjà|été dans l'armée ?
{015106}{015195}Oui. J'ai combattu|avec toi à Vindobona.
{015226}{015280}Tu peux m'aider.
{015311}{015370}Face à ce qui franchira|ces portes...
{015406}{015495}on a une meilleure chance de|survivre si on lutte ensemble.
{015526}{015588}Tu comprends ?
{015631}{015714}Si on reste ensemble,|on survivra.
{015716}{015788}L'empereur a le plaisir de vous|montrer les légionnaires...
{015791}{015880}de Scipion l'Africain !
{016251}{016279}A la mort !
{016394}{016450}A mort ! A mort ! A mort !
{016598}{016644}Restez proches !
{016819}{016875}Venez ensemble !
{016929}{017034}Décalez les colonnes !|Décalez les colonnes !
{017391}{017484}- Tes hommes vont tous être tués.|- Tu n'as pas une seule chance.
{017841}{017926}Serrez vos boucliers !|Restez ensemble !
{017951}{017999}Attention !
{018061}{018109}Attention !
{018111}{018149}Ensemble !
{018244}{018295}Bien joué !
{018640}{018688}Attention !
{018690}{018739}Baissez-vous !|Baissez-vous !
{018919}{018954}Oui !
{019328}{019365}Hagen !
{020088}{020193}Cette colonne vers le chariot !|Cette colonne reste avec moi !
{020303}{020354}Vite !
{020358}{020440}- Allez là-bas !|- Vite !
{021681}{021709}Maximus !
{022083}{022144}Une seule colonne !|Une seule colonne !
{023513}{023555}On a gagné !
{023710}{023810}Mes connaissances en histoire|sont un peu embrumées, mais...
{023814}{023901}les barbares ne sont-ils pas censés|perdre la bataille de Carthage ?
{023904}{023960}Oui, Sire.
{024005}{024042}Pardonnez-moi, Sire.
{024045}{024155}Non, j'aime assez|les surprises.
{024159}{024201}Qui est-il ?
{024204}{024314}On l'appelle l'Espagnol, Sire.
{024368}{024455}-Je voudrais le rencontrer.|- Oui, Sire.
{024529}{024585}Vive les barbares !
{025039}{025141}En avant ! Les armes à la main !
{025535}{025573}Lâchez vos armes.
{025713}{025808}Gladiateur, l'empereur a demandé|à te voir.
{025811}{025870}Je suis au service|de l'empereur.
{026683}{026746}Lève-toi. Lève-toi.
{027030}{027096}Ta célébrité est bien méritée,|l'Espagnol.
{027100}{027190}Aucun gladiateur ne t'a|jamais égalé.
{027193}{027305}Ce jeune homme pense que tu es|Hector réincarné. Ou Hercule ?
{027350}{027465}Et si le héros se découvrait|en nous disant son véritable nom ?
{027525}{027574}Tu as un nom ?
{027606}{027670}Mon nom, c'est|le Gladiateur.
{027758}{027831}Comment oses-tu|me tourner le dos ?
{027835}{027879}Esclave !
{027910}{028000}Retire ton casque|et dis-moi ton nom.
{028350}{028416}Mon nom est|Maximus Decimus Meridius...
{028419}{028488}commandant|des armées du nord...
{028491}{028574}général des légions Felix...
{028576}{028674}loyal serviteur du véritable|empereur, Marc Aurèle...
{028715}{028786}père d'un fils assassiné...
{028790}{028866}mari d'une épouse assassinée...
{028870}{028980}et je me vengerai,|ici-bas ou dans l'autre monde.
{029209}{029270}Aux armes !
{029659}{029741}Qu'il vive ! Qu'il vive !|Qu'il vive ! Qu'il vive !
{031143}{031219}Gardes, au repos !
{032733}{032864}Maximus ! Maximus !|Maximus ! Maximus !
{033664}{033720}Pourquoi est-il encore vivant ?
{033760}{033821}Je ne sais pas.
{033825}{033886}Il ne devrait pas être vivant.
{033890}{033933}ça me contrarie.
{033985}{034041}Je suis très contrarié.
{034371}{034430}J'ai fait ce que|je devais faire.
{034458}{034583}Si père avait fait ce qu'il|voulait, l'empire aurait été divisé.
{034585}{034644}Tu ne comprends pas ça ?
{034823}{034920}Qu'as-tu ressenti|quand tu l'as vu ?
{034985}{035041}Rien du tout.
{035095}{035164}Il t'a profondément|blessée, n'est-ce pas ?
{035203}{035259}Pas plus que je ne|l'ai blessé, moi.
{035397}{035459}Ils m'ont menti,|en Germanie.
{035518}{035579}Ils m'ont dit|qu'il était mort.
{035640}{035716}S'ils m'ont menti, ça signifie|qu'ils ne me respectent pas.
{035719}{035806}S'ils ne me respectent pas,|comment peuvent-ils m'aimer ?
{035853}{035909}Alors, tu dois|dire aux légions...
{035934}{035976}que leur trahison...
{035979}{036045}sera punie.
{036048}{036090}Ma pauvre sœur.
{036113}{036184}Je ne voudrais pas|être ton ennemi.
{036220}{036260}Que vas-tu faire ?
{036654}{036684}Par ici.
{037753}{037853}Les riches matrones paient cher|la compagnie des champions.
{037856}{037946}Je savais que ton frère|enverrait des assassins.
{037950}{038038}Je n'ai pas réalisé qu'il|enverrait les meilleurs d'entre eux.
{038080}{038120}Maximus, il ne le savait pas.
{038165}{038253}Ma famille a été brûlée et|crucifiée de son vivant.
{038255}{038344}-Je n'en savais rien--|- Ne me mens pas !
{038535}{038599}Je les ai pleurés.
{038601}{038719}Comme tu as pleuré ton père ?
{038721}{038831}Je vis dans une prison|de peur depuis ce jour-là.
{038835}{038938}Ne pas pouvoir pleurer son père|parce qu'on a peur de son frère...
{038976}{039066}vivre dans la terreur|chaque moment de chaque jour...
{039070}{039163}parce qu'on a un fils|qui est l'héritier du trône...
{039215}{039261}Oh, j'ai beaucoup pleuré.
{039294}{039341}Mon fils...
{039344}{039390}était innocent.
{039411}{039473}Le mien l'est aussi.
{039516}{039605}Mon fils doit-il aussi mourir|pour que tu me fasses confiance ?
{039666}{039774}Que vous importe ma confiance ?
{039776}{039866}Les dieux t'ont épargné.|Ne comprends-tu donc pas ?
{039870}{039970}Aujourd'hui, j'ai vu un esclave|plus important que l'empereur.
{039973}{040034}Les dieux m'ont épargné ?
{040038}{040138}Je suis à leur merci, avec|le seul pouvoir d'amuser la foule.
{040141}{040200}C'est ça, le pouvoir.
{040203}{040322}La foule, c'est Rome, et en la|contrôlant, Commodus contrôle tout.
{040360}{040419}Ecoute-moi.
{040423}{040518}Mon frère a des ennemis,|surtout au sénat.
{040520}{040581}Tant qu'il a le soutien|du peuple...
{040585}{040687}on n'oserait pas|lui résister comme tu l'as fait.
{040691}{040778}Ils s'opposent à lui,|mais ils ne font rien.
{040780}{040892}Il y a des politiciens qui ont|dédié leur vie à Rome.
{040895}{040978}Un homme en particulier.
{040980}{041075}Le rencontreras-tu, si je rends|la chose possible ?
{041079}{041143}Ne comprenez-vous|donc pas ?
{041146}{041213}Je peux mourir ce soir dans cette|cellule ou demain dans l'arène !
{041216}{041270}Je suis un esclave !
{041274}{041348}Comment puis-je changer|quoi que ce soit ?
{041351}{041427}Cet homme veut la même|chose que toi.
{041431}{041521}Alors, demandez-lui|de tuer Commodus.
{041575}{041658}Je connaissais|un homme, autrefois...
{041660}{041763}un homme noble,|un homme d'honneur...
{041765}{041844}qui aimait mon père...
{041846}{041932}et que mon père aimait.
{041966}{042040}Cet homme a bien servi Rome.
{042158}{042238}Il est parti.
{042240}{042296}Votre frère s'en est|également occupé.
{042300}{042359}Laisse-moi t'aider.
{042535}{042596}Oui...
{042600}{042656}vous pouvez m'aider.
{042730}{042789}Oubliez-moi...
{042793}{042859}et ne revenez|plus jamais ici.
{042951}{043044}Garde ! Cette dame|a terminé sa visite.
{043892}{043939}Maximus.
{043941}{044051}Tu commandais des légions ?|Tu as eu beaucoup de victoires ?
{044105}{044143}En Germanie ?
{044195}{044274}Dans beaucoup de pays.
{044301}{044345}Général !
{045806}{045865}Tu as un nom important.
{045911}{046009}Il doit tuer ton nom|avant de pouvoir te tuer.
{046270}{046310}Oui, tout au bout.
{046313}{046389}- Sénateur Gaius.|- Bonjour.
{046391}{046450}Sénateur Gracchus.
{046495}{046588}Je ne te vois pas souvent jouir|des plaisirs vulgaires de la foule.
{046590}{046678}Je ne prétends pas être|un homme du peuple, sénateur...
{046680}{046773}mais j'essaie d'être un homme|qui est pour le peuple.
{047221}{047360}César ! César !|César ! César !
{047550}{047609}Peuple de Rome !
{047666}{047753}Le 4èmejour d'Antioche...
{047755}{047876}on peut célébrer|le 64èmejour des jeux.
{047910}{048056}Et dans son immense|générosité...
{048060}{048201}l'empereur a daigné faire|une faveur au peuple de Rome...
{048204}{048328}en lui offrant|un combat historique final.
{048330}{048474}De retour au Colisée après|cinq années d'absence...
{048506}{048614}César a le plaisir|de vous montrer...
{048616}{048721}le seul champion|jamais évincé...
{048725}{048791}de l'histoire romaine...
{048795}{048905}Tigre, le Gaulois...
{048909}{048956}légendaire !
{049585}{049693}Il sait très bien comment|manipuler la foule.
{049696}{049778}Marc Aurèle avait un rêve|qui s'appelait Rome.
{049780}{049851}Et qui n'a rien à voir|avec ça !
{049855}{049935}Marc Aurèle est mort,|Maximus.
{049965}{050031}Les mortels ne sont|qu'ombre et poussière.
{050061}{050135}Ombre et poussière, Maximus !
{050139}{050239}César est fier de vous|présenter...
{050241}{050354}le représentant de l'association|de l'entraîneur Antonius Proximo...
{050358}{050486}Aelius Maximus !
{050856}{050928}Ils l'acclament comme|s'il était l'un des leurs.
{050930}{051040}La foule est volage, mon frère.|Il sera oublié dans un mois.
{051130}{051235}Non, bien avant ça.
{051273}{051320}Je me suis arrangé|pour ça.
{051878}{051963}Nous qui allons mourir,|nous te saluons.
{052071}{052145}On est avec toi, Maximus !
{054305}{054354}Tirez ! Tirez ! Tirez !
{055320}{055368}Vas-y ! Vas-y !
{056215}{056271}- Etripe-le !|- A mort ! A mort !
{056274}{056379}A mort ! A mort ! A mort !
{057009}{057058}A mort ! A mort !
{058224}{058285}Maximus le miséricordieux !
{058935}{059040}En avant, les gardes !
{059944}{060046}Que vais-je faire de toi ?
{060049}{060125}Tu te refuses...
{060129}{060171}à mourir.
{060293}{060364}Est-on vraiment très|différents, toi et moi ?
{060400}{060461}Tu ôtes la vie|quand tu le désires...
{060464}{060523}comme moi.
{060525}{060646}Je n'ai plus qu'une vie|à ôter, et ce sera fini.
{060649}{060718}Alors, ôte-la|maintenant.
{061098}{061174}On m'a dit que ton fils...
{061178}{061246}a crié comme une fille...
{061250}{061338}quand ils l'ont|cloué sur la croix...
{061366}{061410}et que ta femme...
{061450}{061530}a gémi comme une putain...
{061533}{061601}quand ils l'ont violée...
{061605}{061676}encore et encore...
{061720}{061763}et encore.
{061920}{062023}Vos jours de gloire|touchent à leur fin...
{062171}{062215}Votre Altesse.
{063020}{063062}Général !
{063095}{063125}Général !
{063270}{063344}- Général !|- Cicéron !
{063566}{063623}- Où est ton campement ?|- A Ostie.
{063824}{063908}- On t'aime, Maximus !|- Louez le vainqueur !
{063910}{063991}Dis aux hommes que leur|général est en vie.
{063994}{064031}- Avance !|- Retrouvez-moi !
{064810}{064869}Peuvent-ils t'entendre ?
{064993}{065030}Qui ?
{065034}{065105}Ta famille,|dans l'autre monde.
{065169}{065240}- Oh, oui.|- Que leur dis-tu ?
{065353}{065395}Je dis à mon fils...
{065455}{065531}que je vais le revoir bientôt|et qu'il doit garder...
{065534}{065636}les pieds bien calés en bas,|quand il fait du cheval.
{065680}{065724}Ce que je dis|à ma femme...
{065800}{065866}ça ne te regarde pas.
{066090}{066171}Maintenant, ils aiment Maximus|pour sa miséricorde.
{066220}{066323}Si je le tue, ça me rendra|encore plus cruel.
{066369}{066528}Toute cette affaire|est un vrai cauchemar.
{066530}{066586}Il te défie.
{066590}{066698}Chacune de ses victoires|est un défi.
{066701}{066824}La foule assiste à ça,|et le sénat aussi.
{066826}{066953}Les sénateurs y perdent|les cheveux qui leur restent.
{066955}{067029}- Tuez-le.|- Non !
{067071}{067145}Je ne veux pas|en faire un martyr.
{067316}{067380}On m'a parlé...
{067384}{067440}d'un serpent marin...
{067444}{067573}qui a une façon très inhabituelle|d'attirer ses proies.
{067576}{067715}Il repose au fond de l'océan|comme s'il était blessé.
{067719}{067780}Quand ses ennemis|approchent...
{067784}{067876}il continue|à demeurer immobile.
{067879}{068004}Quand ses ennemis commencent|à le mordiller par endroits...
{068006}{068124}il reste toujours immobile.
{068204}{068272}De la même façon...
{068275}{068351}nous resterons immobiles...
{068354}{068461}et nous laisserons nos ennemis|venir nous mordiller.
{068489}{068565}Fais suivre|chacun des sénateurs.
{069079}{069184}Cicéron, mon ami. Je croyais|que je ne te reverrais plus.
{069186}{069255}- Je te croyais mort.|- J'ai failli l'être.
{069286}{069368}- Vous êtes à Ostie depuis quand ?|- On y a passé l'hiver.
{069370}{069487}- Comment vont les hommes ?|- Ils sont gras et ils s'ennuient.
{069490}{069593}- Qui a le commandement ?|- Un crétin de Rome.
{069630}{069686}Quand seront-ils prêts|à se battre ?
{069690}{069744}Pour toi, demain.
{069790}{069873}Il faut que tu fasses|quelque chose pour moi.
{069999}{070138}Si vous n'êtes pas allés dans|l'arène, venez voir ce spectacle.
{070141}{070251}Le géant Maximus l'emporte|sur notre empereur Commodus.
{070255}{070368}Que peut-on y faire ?|Il les brave tous !
{070415}{070450}Mon Dieu !
{070530}{070606}- Il l'a vaincu !|- Laissez passer !
{070799}{070886}Madame ?J'étais au service|de votre père, à Vindobona.
{070889}{070940}- Recule.|- Madame.
{070943}{071006}J'étais au service|de votre père à Vindobona.
{071010}{071045}Recule !
{071049}{071123}Et du général Maximus.|Je suis toujours à son service.
{071174}{071201}Arrête-toi.
{071225}{071260}Arrête-toi.
{071314}{071360}Reculez.
{071391}{071474}Le général vous fait dire|qu'il rencontrera votre politicien.
{071539}{071583}Pour ta loyauté, soldat.
{071585}{071634}Merci, Madame.
{071931}{071975}Laissez-nous.
{072143}{072199}Sénateur Gracchus.
{072604}{072636}Général.
{072676}{072757}J'espère que ma présence ici|aujourd'hui vous prouve...
{072760}{072858}que vous pouvez|me faire confiance.
{072985}{073044}- Le sénat est avec vous ?|- Le sénat ?
{073106}{073204}Oui. Je peux|parler en leur nom.
{073206}{073289}Pouvez-vous acheter ma liberté|et me faire sortir de Rome ?
{073320}{073400}A quelles fins ?
{073403}{073482}Faites-moi sortir|des murs de la ville.
{073485}{073549}Préparez des chevaux|qui m'emmèneront à Ostie.
{073553}{073616}Mon armée a son campement|là-bas.
{073619}{073716}Le 2èmejour, à la tombée de la nuit,|je reviendrai avec 5000 hommes.
{073720}{073781}Mais toutes les légions|ont de nouveaux chefs...
{073785}{073830}qui sont fidèles|envers Commodus !
{073833}{073925}Quand mes hommes me verront vivant,|on verra s'ils lui sont fidèles !
{073929}{073993}C'est de la folie.
{073995}{074097}Aucune armée n'est entrée dans|la capitale depuis cent ans.
{074100}{074156}Je ne veux pas tomber|dans une autre dictature.
{074159}{074287}Le temps des demi-mesures|est terminé, sénateur.
{074290}{074382}Et après ce coup d'éclat|glorieux, que ferez-vous ?
{074415}{074518}Vous partirez|avec vos 5000 guerriers ?
{074520}{074586}Je partirai.
{074590}{074649}Pour votre protection,|les soldats resteront...
{074652}{074701}sous le commandement|du sénat.
{074705}{074750}Alors...
{074753}{074880}quand Rome sera à vous,|vous la rendrez au peuple ?
{074920}{074958}Dites-moi pourquoi.
{075133}{075204}Parce que c'était|le dernier souhait d'un mourant.
{075320}{075376}Je tuerai Commodus.
{075433}{075535}Et je vous confierai|le destin de Rome.
{075580}{075649}Marc Aurèle|vous faisait confiance.
{075700}{075764}Sa fille vous fait confiance.
{075881}{075940}Je vous ferai|confiance aussi.
{075944}{076020}Mais nous avons|peu de temps.
{076023}{076086}Donnez-moi deux jours...
{076089}{076181}et j'achèterai votre liberté.
{076185}{076229}Et vous--
{076273}{076354}restez vivant...
{076356}{076415}ou je suis un homme mort.
{076464}{076523}Maintenant, on doit y aller.
{076672}{076720}ça ne marchera pas.
{076752}{076845}L'empereur en sait trop.
{076849}{076905}Et en ce qui me concerne...
{076940}{076999}ça devient trop dangereux.
{077036}{077110}Vous serez payé à mon retour.
{077165}{077229}Je vous en donne ma parole.
{077231}{077313}Votre parole ?|Et si vous ne revenez pas ?
{077358}{077448}Savez-vous encore ce que c'est|que la confiance, Proximo ?
{077450}{077496}La confiance ?
{077613}{077658}En qui puis-je avoir confiance ?
{077686}{077773}-Je vais tuer Commodus.|- Pourquoi souhaiterais-je cela ?
{077803}{077859}Il m'enrichit.
{077939}{078005}Oh, je--
{078008}{078090}Je sais que vous êtes|un homme de parole, général.
{078145}{078226}Je sais que vous êtes prêt|à mourir pour l'honneur.
{078270}{078354}A mourir pour Rome.
{078356}{078423}A mourir pour la mémoire|de vos ancêtres.
{078450}{078509}Mais d'un autre côté--
{078600}{078656}Je suis un amuseur.
{078757}{078800}Garde !
{078940}{079001}Il a tué l'homme|qui vous a libéré.
{079280}{079339}Prétoriens, maître.
{079533}{079575}Halte !
{079886}{079950}Où étais-tu ?
{079954}{080010}Je t'ai envoyée chercher.
{080048}{080090}Je t'en prie, mon frère.
{080265}{080300}Pourquoi es-tu inquiet ?
{080395}{080475}Gracchus a-t-il|une nouvelle maîtresse ?
{080523}{080579}Je ne sais pas.
{080633}{080678}Je croyais que|tu l'avais vu.
{080718}{080803}Il infecte tout le monde,|comme une horrible fièvre.
{080848}{080909}Pour la santé de Rome,|le sénat doit être saigné.
{080954}{081010}Et il saignera aussi.
{081045}{081094}Très bientôt.
{081133}{081196}Mais pas ce soir.
{081626}{081685}Tu te souviens de ce que|notre père a dit un jour ?
{081757}{081811}C'est un rêve...
{081861}{081943}un rêve effrayant--
{081996}{082034}"Voilà ce qu'est la vie."""
{082119}{082185}Penses-tu que ce soit vrai ?
{082189}{082265}Je ne sais pas.
{082353}{082409}Je le pense.
{082485}{082570}Et je ne peux le partager|qu'avec toi.
{083695}{083751}Ouvre la bouche.
{084855}{084911}Tu sais que je t'aime.
{084973}{085029}Et je t'aime aussi.
{086121}{086185}Sors !
{086220}{086260}Dépêche-toi !
{086380}{086441}Félicitations, général.
{086445}{086545}Vous avez des amis|très persuasifs.
{086710}{086786}Mon frère a fait|arrêter Gracchus.
{086789}{086894}On ne peut plus attendre.|On partira ce soir.
{086896}{086985}Proximo te cherchera à minuit|pour t'emmener hors de la ville.
{087023}{087109}Ton serviteur, Cicéron,|t'attendra là avec des chevaux.
{087187}{087244}Vous avez fait tout ça ?
{087248}{087295}Oui.
{087298}{087338}Vous avez pris|trop de risques.
{087377}{087444}Je dois vous dédommager|pour beaucoup de choses.
{087505}{087561}Vous n'avez à me|dédommager pour rien.
{087565}{087673}Vous aimez votre fils.|Vous êtes forte pour lui.
{087763}{087848}J'en assez d'être forte.
{087896}{088023}Mon frère déteste le monde|entier et toi par-dessus tout.
{088025}{088140}- Car votre père m'avait choisi.|- Non.
{088170}{088239}Parce que mon père t'aimait.
{088355}{088443}Et parce que je t'aimais.
{088505}{088561}Il y a longtemps de ça.
{088699}{088755}J'étais différente|à cette époque ?
{088955}{089011}Vous riiez plus qu'aujourd'hui.
{089133}{089204}Je me suis sentie seule|toute ma vie...
{089240}{089278}sauf quand j'étais|avec toi.
{089388}{089444}Je dois y aller.
{089447}{089495}Oui.
{090321}{090388}Tiens, tiens.
{090716}{090760}Je te tiens !
{090855}{090914}N'est-il pas un peu tard|pour jouer au légionnaire ?
{090918}{090984}Je ne suis pas un légionnaire.
{090988}{091054}- Tu n'es pas un légionnaire ?|-Je suis un gladiateur.
{091101}{091165}Un gladiateur ?
{091167}{091250}Les gladiateurs ne combattent|que pour les jeux.
{091253}{091348}N'aimerais-tu pas mieux être un|grand guerrier comme Jules César ?
{091351}{091435}Je suis Maximus,|le sauveur de Rome !
{091524}{091564}Le sauveur de Rome ?
{091814}{091870}Qui a dit ça ?
{092124}{092156}Où est Lucius ?
{092215}{092260}Il est avec l'empereur.
{092375}{092429}- Elle n'a pas pu--|- Oui, elle l'a fait.
{092433}{092496}Elle l'a sorti|d'un panier...
{092536}{092636}et l'a pressé contre sa poitrine,|juste au-dessus de son coeur.
{092698}{092766}Il l'a mordu|à la poitrine ?
{092770}{092814}Oui.
{092816}{092921}Vois-tu, Lucius,|parfois, les grandes dames...
{092952}{093065}font d'étranges choses|au nom de l'amour.
{093068}{093124}Je pense que c'est idiot.
{093128}{093170}Moi aussi.
{093208}{093264}Moi aussi.
{093267}{093326}Ma soeur, viens|tejoindre à nous.
{093330}{093396}Je lisais un livre à Lucius.
{093400}{093479}-Je lisais aussi.|- Oui.
{093481}{093584}C'est un garçon très intelligent.|un jour, ce sera un grand empereur.
{093636}{093749}On lisait les aventures du|grand Antoine en Egypte.
{093753}{093811}La reine s'est tuée|avec un serpent.
{093815}{093913}Attends d'entendre ce qui est|arrivé à nos ancêtres.
{093943}{094070}Si tu es sage, demain, je te|raconterai l'histoire de Claude.
{094115}{094198}Il a été trahi...
{094200}{094269}par ceux qui étaient|le plus proches de lui...
{094316}{094365}ceux qui étaient|du même sang.
{094411}{094488}Ils chuchotaient|dans des coins sombres...
{094490}{094546}sortaient tard, dans la nuit...
{094550}{094626}et conspiraient...
{094630}{094675}sans relâche.
{094741}{094826}Mais l'empereur Claude savait|qu'ils préparaient quelque chose.
{094861}{094933}Comme des petites|abeilles très affairées.
{094993}{095105}Un jour, il s'assit|auprès de l'un d'eux...
{095108}{095193}la regarda...
{095195}{095244}et lui dit...
{095278}{095367}Dis-moi ce que|tu prépares...
{095370}{095439}ma petite abeille...
{095495}{095590}ou j'abattrai ceux|qui te sont le plus proches.
{095625}{095715}"Tu me verras me baigner|dans leur sang."""
{095815}{095889}L'empereur avait le coeur brisé.
{095955}{096026}La petite abeille l'avait|blessé plus profondément...
{096030}{096125}que tout autre.
{096172}{096244}Que s'est-il passé ensuite,|d'après toi, Lucius ?
{096286}{096345}Je ne sais pas, mon oncle.
{096528}{096594}La petite abeille|lui a tout dit.
{097785}{097893}Ouvre, au nom de l'empereur !
{097895}{097956}Proximo !
{097960}{098060}Ouvre les portes,|au nom de l'empereur !
{098185}{098229}Ouvre les portes !
{098404}{098484}Ouvre les portes, Proximo.
{098486}{098538}Tu veux mourir, vieillard ?
{098581}{098611}Tiens.
{098643}{098704}Tout est prêt.
{098708}{098781}Tu sembles avoir gagné|ta liberté.
{098835}{098894}Cours-tu le danger|de devenir bon ?
{099045}{099160}-Juba.|- Mort aux ennemis de l'empereur !
{099183}{099246}Ouvre les portes !
{099405}{099464}Tirez !
{099530}{099620}Dépêchez-vous !|Formez une colonne à gauche !
{099715}{099799}Il me faut quelques moments,|alors, soyez prudents.
{099830}{099901}Si vous ne voulez pas vous|impliquer, regagnez vos cellules.
{099905}{099961}On va t'attendre ici, Maximus.
{099965}{100051}- Force et honneur.|- Allez-y.
{100086}{100131}Force et honneur.
{100210}{100315}Visez. Courbez vos arcs !
{102320}{102358}Ombre et poussière.
{103810}{103843}Je suis désolé.
{104643}{104699}C'est fait.
{104898}{104971}Et mon neveu ?
{104975}{105034}Et sa mère ?
{105108}{105190}Doivent-ils partager|le destin de son amant ?
{105235}{105299}Ou devrais-je être|miséricordieux ?
{105375}{105431}Commodus le Miséricordieux.
{105630}{105699}Lucius restera avec moi.
{105733}{105789}Et si sa mère...
{105828}{105894}me regarde...
{105931}{106003}d'une manière qui me déplaît...
{106057}{106114}il mourra.
{106208}{106274}Si elle décide...
{106278}{106354}d'être noble...
{106357}{106419}et de s'ôter sa propre vie...
{106466}{106525}il mourra.
{106618}{106666}Quant à toi...
{106752}{106832}tu m'aimeras...
{106835}{106896}commeje t'aimais.
{106933}{107006}Tu me donneras un héritier...
{107010}{107071}de sang pur...
{107075}{107162}afin que Commodus|et sa progéniture...
{107165}{107239}gouvernent pendant|mille années.
{107370}{107441}Ne suis-je pas|miséricordieux ?
{108080}{108151}Ne suis-je pas|miséricordieux ?
{110088}{110144}Ils t'appellent.
{110198}{110246}Le général...
{110250}{110314}qui est devenu un esclave.
{110337}{110409}L'esclave|qui est devenu gladiateur.
{110450}{110535}Le gladiateur|qui a défié un empereur.
{110590}{110644}C'est une histoire saisissante.
{110678}{110765}Le peuple veut savoir comment|elle se termine.
{110846}{110905}Seule une mort glorieuse|pourra faire l'affaire.
{110966}{111071}Et qu'est-ce qui peut|être plus glorieux...
{111074}{111161}que de défier l'empereur|lui-même dans l'arène ?
{111236}{111295}Vous seriez prêt|à me combattre ?
{111299}{111331}Pourquoi pas ?
{111364}{111413}Tu crois que j'ai peur ?
{111451}{111533}Je crois que vous avez eu|peur toute votre vie.
{111535}{111660}A part Maximus l'Invincible,|qui ne connaît pas la peur ?
{111826}{111909}"Je connaissais un homme qui|disait : ""La mort sourit à tous."
{111956}{112054}"Tout ce qu'un homme peut faire,|c'est de sourire à son tour""."
{112085}{112141}Je me demande une chose.
{112144}{112241}Ton ami a-t-il souri|à sa propre mort ?
{112244}{112300}Vous devez le savoir.
{112371}{112413}C'était votre père.
{112541}{112608}Je sais que tu aimais|mon père...
{112656}{112713}mais je l'aimais aussi.
{112754}{112813}ça fait de nous des frères,|non ?
{112906}{112965}Souris-moi, maintenant,|mon frère.
{113135}{113215}Mettez-lui son armure.|Cachez la blessure.
{114854}{114928}Formez un cercle !
{118279}{118348}Quintus, ton épée.
{118350}{118435}Donne-moi ton épée !
{118509}{118570}Une épée !|Donnez-moi une épée !
{118614}{118658}Rengainez vos épées.
{123126}{123168}Libérez mes hommes.
{123214}{123290}Le sénateur Gracchus doit|être rétabli dans ses fonctions.
{123324}{123383}Il y avait un rêve|qui s'appelait Rome.
{123419}{123498}Il deviendra réalité.
{123500}{123576}Ce sont les souhaits|de Marc Aurèle.
{123599}{123668}Libérez les prisonniers !
{124499}{124536}Lucius est sain et sauf.
{125031}{125093}Va les rejoindre.
{126566}{126611}Tu es chez toi.
{127393}{127479}Rome vaut-elle la peine qu'un|homme de valeur meure pour elle ?
{127601}{127658}Nous le croyions,|autrefois.
{127749}{127793}Aidez-nous à y croire encore.
{127921}{127988}C'était un soldat de Rome.
{128096}{128153}Honorez sa mémoire.
{128156}{128227}Qui veut m'aider|à le porter ?
{129554}{129605}A présent,|nous sommes libres.
{129799}{129863}Je te reverrai.
{129945}{130016}Mais pas encore.
{130019}{130063}Pas encore.
